// Code generated by ent, DO NOT EDIT.

package shiftrotationslot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLTE(FieldID, id))
}

// RotationID applies equality check predicate on the "rotation_id" field. It's identical to RotationIDEQ.
func RotationID(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldRotationID, v))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldTenantID, v))
}

// StaffMemberID applies equality check predicate on the "staff_member_id" field. It's identical to StaffMemberIDEQ.
func StaffMemberID(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldStaffMemberID, v))
}

// CycleDay applies equality check predicate on the "cycle_day" field. It's identical to CycleDayEQ.
func CycleDay(v int) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldCycleDay, v))
}

// StartTime applies equality check predicate on the "start_time" field. It's identical to StartTimeEQ.
func StartTime(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldStartTime, v))
}

// EndTime applies equality check predicate on the "end_time" field. It's identical to EndTimeEQ.
func EndTime(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldEndTime, v))
}

// IsOffDay applies equality check predicate on the "is_off_day" field. It's identical to IsOffDayEQ.
func IsOffDay(v bool) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldIsOffDay, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldCreatedAt, v))
}

// RotationIDEQ applies the EQ predicate on the "rotation_id" field.
func RotationIDEQ(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldRotationID, v))
}

// RotationIDNEQ applies the NEQ predicate on the "rotation_id" field.
func RotationIDNEQ(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNEQ(FieldRotationID, v))
}

// RotationIDIn applies the In predicate on the "rotation_id" field.
func RotationIDIn(vs ...uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldIn(FieldRotationID, vs...))
}

// RotationIDNotIn applies the NotIn predicate on the "rotation_id" field.
func RotationIDNotIn(vs ...uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNotIn(FieldRotationID, vs...))
}

// RotationIDGT applies the GT predicate on the "rotation_id" field.
func RotationIDGT(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGT(FieldRotationID, v))
}

// RotationIDGTE applies the GTE predicate on the "rotation_id" field.
func RotationIDGTE(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGTE(FieldRotationID, v))
}

// RotationIDLT applies the LT predicate on the "rotation_id" field.
func RotationIDLT(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLT(FieldRotationID, v))
}

// RotationIDLTE applies the LTE predicate on the "rotation_id" field.
func RotationIDLTE(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLTE(FieldRotationID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLTE(FieldTenantID, v))
}

// StaffMemberIDEQ applies the EQ predicate on the "staff_member_id" field.
func StaffMemberIDEQ(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldStaffMemberID, v))
}

// StaffMemberIDNEQ applies the NEQ predicate on the "staff_member_id" field.
func StaffMemberIDNEQ(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNEQ(FieldStaffMemberID, v))
}

// StaffMemberIDIn applies the In predicate on the "staff_member_id" field.
func StaffMemberIDIn(vs ...uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldIn(FieldStaffMemberID, vs...))
}

// StaffMemberIDNotIn applies the NotIn predicate on the "staff_member_id" field.
func StaffMemberIDNotIn(vs ...uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNotIn(FieldStaffMemberID, vs...))
}

// StaffMemberIDGT applies the GT predicate on the "staff_member_id" field.
func StaffMemberIDGT(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGT(FieldStaffMemberID, v))
}

// StaffMemberIDGTE applies the GTE predicate on the "staff_member_id" field.
func StaffMemberIDGTE(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGTE(FieldStaffMemberID, v))
}

// StaffMemberIDLT applies the LT predicate on the "staff_member_id" field.
func StaffMemberIDLT(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLT(FieldStaffMemberID, v))
}

// StaffMemberIDLTE applies the LTE predicate on the "staff_member_id" field.
func StaffMemberIDLTE(v uuid.UUID) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLTE(FieldStaffMemberID, v))
}

// CycleDayEQ applies the EQ predicate on the "cycle_day" field.
func CycleDayEQ(v int) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldCycleDay, v))
}

// CycleDayNEQ applies the NEQ predicate on the "cycle_day" field.
func CycleDayNEQ(v int) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNEQ(FieldCycleDay, v))
}

// CycleDayIn applies the In predicate on the "cycle_day" field.
func CycleDayIn(vs ...int) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldIn(FieldCycleDay, vs...))
}

// CycleDayNotIn applies the NotIn predicate on the "cycle_day" field.
func CycleDayNotIn(vs ...int) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNotIn(FieldCycleDay, vs...))
}

// CycleDayGT applies the GT predicate on the "cycle_day" field.
func CycleDayGT(v int) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGT(FieldCycleDay, v))
}

// CycleDayGTE applies the GTE predicate on the "cycle_day" field.
func CycleDayGTE(v int) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGTE(FieldCycleDay, v))
}

// CycleDayLT applies the LT predicate on the "cycle_day" field.
func CycleDayLT(v int) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLT(FieldCycleDay, v))
}

// CycleDayLTE applies the LTE predicate on the "cycle_day" field.
func CycleDayLTE(v int) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLTE(FieldCycleDay, v))
}

// StartTimeEQ applies the EQ predicate on the "start_time" field.
func StartTimeEQ(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldStartTime, v))
}

// StartTimeNEQ applies the NEQ predicate on the "start_time" field.
func StartTimeNEQ(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNEQ(FieldStartTime, v))
}

// StartTimeIn applies the In predicate on the "start_time" field.
func StartTimeIn(vs ...string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldIn(FieldStartTime, vs...))
}

// StartTimeNotIn applies the NotIn predicate on the "start_time" field.
func StartTimeNotIn(vs ...string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNotIn(FieldStartTime, vs...))
}

// StartTimeGT applies the GT predicate on the "start_time" field.
func StartTimeGT(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGT(FieldStartTime, v))
}

// StartTimeGTE applies the GTE predicate on the "start_time" field.
func StartTimeGTE(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGTE(FieldStartTime, v))
}

// StartTimeLT applies the LT predicate on the "start_time" field.
func StartTimeLT(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLT(FieldStartTime, v))
}

// StartTimeLTE applies the LTE predicate on the "start_time" field.
func StartTimeLTE(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLTE(FieldStartTime, v))
}

// StartTimeContains applies the Contains predicate on the "start_time" field.
func StartTimeContains(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldContains(FieldStartTime, v))
}

// StartTimeHasPrefix applies the HasPrefix predicate on the "start_time" field.
func StartTimeHasPrefix(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldHasPrefix(FieldStartTime, v))
}

// StartTimeHasSuffix applies the HasSuffix predicate on the "start_time" field.
func StartTimeHasSuffix(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldHasSuffix(FieldStartTime, v))
}

// StartTimeEqualFold applies the EqualFold predicate on the "start_time" field.
func StartTimeEqualFold(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEqualFold(FieldStartTime, v))
}

// StartTimeContainsFold applies the ContainsFold predicate on the "start_time" field.
func StartTimeContainsFold(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldContainsFold(FieldStartTime, v))
}

// EndTimeEQ applies the EQ predicate on the "end_time" field.
func EndTimeEQ(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldEndTime, v))
}

// EndTimeNEQ applies the NEQ predicate on the "end_time" field.
func EndTimeNEQ(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNEQ(FieldEndTime, v))
}

// EndTimeIn applies the In predicate on the "end_time" field.
func EndTimeIn(vs ...string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldIn(FieldEndTime, vs...))
}

// EndTimeNotIn applies the NotIn predicate on the "end_time" field.
func EndTimeNotIn(vs ...string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNotIn(FieldEndTime, vs...))
}

// EndTimeGT applies the GT predicate on the "end_time" field.
func EndTimeGT(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGT(FieldEndTime, v))
}

// EndTimeGTE applies the GTE predicate on the "end_time" field.
func EndTimeGTE(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGTE(FieldEndTime, v))
}

// EndTimeLT applies the LT predicate on the "end_time" field.
func EndTimeLT(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLT(FieldEndTime, v))
}

// EndTimeLTE applies the LTE predicate on the "end_time" field.
func EndTimeLTE(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLTE(FieldEndTime, v))
}

// EndTimeContains applies the Contains predicate on the "end_time" field.
func EndTimeContains(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldContains(FieldEndTime, v))
}

// EndTimeHasPrefix applies the HasPrefix predicate on the "end_time" field.
func EndTimeHasPrefix(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldHasPrefix(FieldEndTime, v))
}

// EndTimeHasSuffix applies the HasSuffix predicate on the "end_time" field.
func EndTimeHasSuffix(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldHasSuffix(FieldEndTime, v))
}

// EndTimeEqualFold applies the EqualFold predicate on the "end_time" field.
func EndTimeEqualFold(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEqualFold(FieldEndTime, v))
}

// EndTimeContainsFold applies the ContainsFold predicate on the "end_time" field.
func EndTimeContainsFold(v string) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldContainsFold(FieldEndTime, v))
}

// IsOffDayEQ applies the EQ predicate on the "is_off_day" field.
func IsOffDayEQ(v bool) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldIsOffDay, v))
}

// IsOffDayNEQ applies the NEQ predicate on the "is_off_day" field.
func IsOffDayNEQ(v bool) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNEQ(FieldIsOffDay, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ShiftRotationSlot) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ShiftRotationSlot) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ShiftRotationSlot) predicate.ShiftRotationSlot {
	return predicate.ShiftRotationSlot(sql.NotPredicates(p))
}
