-- Create "room_bookings" table
CREATE TABLE "room_bookings" ("id" uuid NOT NULL, "tenant_id" uuid NOT NULL, "outlet_id" uuid NOT NULL, "confirmation_no" character varying NOT NULL, "lead_guest_name" character varying NOT NULL, "email" character varying NULL, "phone" character varying NULL, "rooms_count" bigint NOT NULL DEFAULT 1, "arrival_date" timestamptz NOT NULL, "departure_date" timestamptz NOT NULL, "inventory_rate_plan_bundle_id" uuid NULL, "market_segment" character varying NULL, "source" character varying NOT NULL DEFAULT 'staff', "crm_contact_id" uuid NULL, "status" character varying NOT NULL DEFAULT 'confirmed', "created_by" uuid NOT NULL, "metadata" jsonb NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "roombooking_tenant_id_arrival_date" to table: "room_bookings"
CREATE INDEX "roombooking_tenant_id_arrival_date" ON "room_bookings" ("tenant_id", "arrival_date");
-- Create index "roombooking_tenant_id_confirmation_no" to table: "room_bookings"
CREATE UNIQUE INDEX "roombooking_tenant_id_confirmation_no" ON "room_bookings" ("tenant_id", "confirmation_no");
-- Create index "roombooking_tenant_id_outlet_id_status" to table: "room_bookings"
CREATE INDEX "roombooking_tenant_id_outlet_id_status" ON "room_bookings" ("tenant_id", "outlet_id", "status");
-- Modify "room_guests" table
ALTER TABLE "room_guests" ADD COLUMN "first_name" character varying NULL, ADD COLUMN "last_name" character varying NULL, ADD COLUMN "email" character varying NULL, ADD COLUMN "nationality" character varying NULL, ADD COLUMN "id_type" character varying NOT NULL DEFAULT 'national_id', ADD COLUMN "id_document_url" character varying NULL, ADD COLUMN "adults" bigint NOT NULL DEFAULT 1, ADD COLUMN "children" bigint NOT NULL DEFAULT 0, ADD COLUMN "child_ages" jsonb NULL, ADD COLUMN "source" character varying NOT NULL DEFAULT 'staff', ADD COLUMN "crm_contact_id" uuid NULL, ADD COLUMN "expected_arrival_at" timestamptz NULL, ADD COLUMN "expected_departure_at" timestamptz NULL, ADD COLUMN "booking_id" uuid NULL, ADD CONSTRAINT "room_guests_room_bookings_guests" FOREIGN KEY ("booking_id") REFERENCES "room_bookings" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
