// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/cashdrawer"
	"github.com/google/uuid"
)

// CashDrawer is the model entity for the CashDrawer schema.
type CashDrawer struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// OutletID holds the value of the "outlet_id" field.
	OutletID uuid.UUID `json:"outlet_id,omitempty"`
	// DeviceID holds the value of the "device_id" field.
	DeviceID *uuid.UUID `json:"device_id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// StartingCash holds the value of the "starting_cash" field.
	StartingCash float64 `json:"starting_cash,omitempty"`
	// EndingCash holds the value of the "ending_cash" field.
	EndingCash *float64 `json:"ending_cash,omitempty"`
	// OpenedAt holds the value of the "opened_at" field.
	OpenedAt *time.Time `json:"opened_at,omitempty"`
	// ClosedAt holds the value of the "closed_at" field.
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CashDrawerQuery when eager-loading is set.
	Edges        CashDrawerEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CashDrawerEdges holds the relations/edges for other nodes in the graph.
type CashDrawerEdges struct {
	// Events holds the value of the events edge.
	Events []*CashDrawerEvent `json:"events,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e CashDrawerEdges) EventsOrErr() ([]*CashDrawerEvent, error) {
	if e.loadedTypes[0] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CashDrawer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cashdrawer.FieldDeviceID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case cashdrawer.FieldMetadata:
			values[i] = new([]byte)
		case cashdrawer.FieldStartingCash, cashdrawer.FieldEndingCash:
			values[i] = new(sql.NullFloat64)
		case cashdrawer.FieldStatus:
			values[i] = new(sql.NullString)
		case cashdrawer.FieldOpenedAt, cashdrawer.FieldClosedAt:
			values[i] = new(sql.NullTime)
		case cashdrawer.FieldID, cashdrawer.FieldTenantID, cashdrawer.FieldOutletID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CashDrawer fields.
func (_m *CashDrawer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cashdrawer.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case cashdrawer.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case cashdrawer.FieldOutletID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field outlet_id", values[i])
			} else if value != nil {
				_m.OutletID = *value
			}
		case cashdrawer.FieldDeviceID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field device_id", values[i])
			} else if value.Valid {
				_m.DeviceID = new(uuid.UUID)
				*_m.DeviceID = *value.S.(*uuid.UUID)
			}
		case cashdrawer.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case cashdrawer.FieldStartingCash:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field starting_cash", values[i])
			} else if value.Valid {
				_m.StartingCash = value.Float64
			}
		case cashdrawer.FieldEndingCash:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field ending_cash", values[i])
			} else if value.Valid {
				_m.EndingCash = new(float64)
				*_m.EndingCash = value.Float64
			}
		case cashdrawer.FieldOpenedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field opened_at", values[i])
			} else if value.Valid {
				_m.OpenedAt = new(time.Time)
				*_m.OpenedAt = value.Time
			}
		case cashdrawer.FieldClosedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field closed_at", values[i])
			} else if value.Valid {
				_m.ClosedAt = new(time.Time)
				*_m.ClosedAt = value.Time
			}
		case cashdrawer.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CashDrawer.
// This includes values selected through modifiers, order, etc.
func (_m *CashDrawer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryEvents queries the "events" edge of the CashDrawer entity.
func (_m *CashDrawer) QueryEvents() *CashDrawerEventQuery {
	return NewCashDrawerClient(_m.config).QueryEvents(_m)
}

// Update returns a builder for updating this CashDrawer.
// Note that you need to call CashDrawer.Unwrap() before calling this method if this CashDrawer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CashDrawer) Update() *CashDrawerUpdateOne {
	return NewCashDrawerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CashDrawer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CashDrawer) Unwrap() *CashDrawer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CashDrawer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CashDrawer) String() string {
	var builder strings.Builder
	builder.WriteString("CashDrawer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("outlet_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutletID))
	builder.WriteString(", ")
	if v := _m.DeviceID; v != nil {
		builder.WriteString("device_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("starting_cash=")
	builder.WriteString(fmt.Sprintf("%v", _m.StartingCash))
	builder.WriteString(", ")
	if v := _m.EndingCash; v != nil {
		builder.WriteString("ending_cash=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OpenedAt; v != nil {
		builder.WriteString("opened_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ClosedAt; v != nil {
		builder.WriteString("closed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteByte(')')
	return builder.String()
}

// CashDrawers is a parsable slice of CashDrawer.
type CashDrawers []*CashDrawer
