// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/channelintegration"
	"github.com/google/uuid"
)

// ChannelIntegration is the model entity for the ChannelIntegration schema.
type ChannelIntegration struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// ChannelName holds the value of the "channel_name" field.
	ChannelName string `json:"channel_name,omitempty"`
	// uber_eats | glovo | etc
	ChannelType string `json:"channel_type,omitempty"`
	// ConfigJSON holds the value of the "config_json" field.
	ConfigJSON map[string]interface{} `json:"config_json,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ChannelIntegration) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case channelintegration.FieldConfigJSON:
			values[i] = new([]byte)
		case channelintegration.FieldChannelName, channelintegration.FieldChannelType, channelintegration.FieldStatus:
			values[i] = new(sql.NullString)
		case channelintegration.FieldCreatedAt, channelintegration.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case channelintegration.FieldID, channelintegration.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ChannelIntegration fields.
func (_m *ChannelIntegration) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case channelintegration.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case channelintegration.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case channelintegration.FieldChannelName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_name", values[i])
			} else if value.Valid {
				_m.ChannelName = value.String
			}
		case channelintegration.FieldChannelType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel_type", values[i])
			} else if value.Valid {
				_m.ChannelType = value.String
			}
		case channelintegration.FieldConfigJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field config_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ConfigJSON); err != nil {
					return fmt.Errorf("unmarshal field config_json: %w", err)
				}
			}
		case channelintegration.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case channelintegration.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case channelintegration.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ChannelIntegration.
// This includes values selected through modifiers, order, etc.
func (_m *ChannelIntegration) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ChannelIntegration.
// Note that you need to call ChannelIntegration.Unwrap() before calling this method if this ChannelIntegration
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ChannelIntegration) Update() *ChannelIntegrationUpdateOne {
	return NewChannelIntegrationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ChannelIntegration entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ChannelIntegration) Unwrap() *ChannelIntegration {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ChannelIntegration is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ChannelIntegration) String() string {
	var builder strings.Builder
	builder.WriteString("ChannelIntegration(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("channel_name=")
	builder.WriteString(_m.ChannelName)
	builder.WriteString(", ")
	builder.WriteString("channel_type=")
	builder.WriteString(_m.ChannelType)
	builder.WriteString(", ")
	builder.WriteString("config_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConfigJSON))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ChannelIntegrations is a parsable slice of ChannelIntegration.
type ChannelIntegrations []*ChannelIntegration
