// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/druginteractioncheck"
	"github.com/google/uuid"
)

// DrugInteractionCheck is the model entity for the DrugInteractionCheck schema.
type DrugInteractionCheck struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// PrescriptionID holds the value of the "prescription_id" field.
	PrescriptionID *uuid.UUID `json:"prescription_id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID *uuid.UUID `json:"order_id,omitempty"`
	// DrugSkus holds the value of the "drug_skus" field.
	DrugSkus []string `json:"drug_skus,omitempty"`
	// Result holds the value of the "result" field.
	Result string `json:"result,omitempty"`
	// Details holds the value of the "details" field.
	Details string `json:"details,omitempty"`
	// CheckedBy holds the value of the "checked_by" field.
	CheckedBy *uuid.UUID `json:"checked_by,omitempty"`
	// CheckedAt holds the value of the "checked_at" field.
	CheckedAt time.Time `json:"checked_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*DrugInteractionCheck) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case druginteractioncheck.FieldPrescriptionID, druginteractioncheck.FieldOrderID, druginteractioncheck.FieldCheckedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case druginteractioncheck.FieldDrugSkus:
			values[i] = new([]byte)
		case druginteractioncheck.FieldResult, druginteractioncheck.FieldDetails:
			values[i] = new(sql.NullString)
		case druginteractioncheck.FieldCheckedAt, druginteractioncheck.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case druginteractioncheck.FieldID, druginteractioncheck.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the DrugInteractionCheck fields.
func (_m *DrugInteractionCheck) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case druginteractioncheck.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case druginteractioncheck.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case druginteractioncheck.FieldPrescriptionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field prescription_id", values[i])
			} else if value.Valid {
				_m.PrescriptionID = new(uuid.UUID)
				*_m.PrescriptionID = *value.S.(*uuid.UUID)
			}
		case druginteractioncheck.FieldOrderID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = new(uuid.UUID)
				*_m.OrderID = *value.S.(*uuid.UUID)
			}
		case druginteractioncheck.FieldDrugSkus:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field drug_skus", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DrugSkus); err != nil {
					return fmt.Errorf("unmarshal field drug_skus: %w", err)
				}
			}
		case druginteractioncheck.FieldResult:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field result", values[i])
			} else if value.Valid {
				_m.Result = value.String
			}
		case druginteractioncheck.FieldDetails:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value.Valid {
				_m.Details = value.String
			}
		case druginteractioncheck.FieldCheckedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field checked_by", values[i])
			} else if value.Valid {
				_m.CheckedBy = new(uuid.UUID)
				*_m.CheckedBy = *value.S.(*uuid.UUID)
			}
		case druginteractioncheck.FieldCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checked_at", values[i])
			} else if value.Valid {
				_m.CheckedAt = value.Time
			}
		case druginteractioncheck.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the DrugInteractionCheck.
// This includes values selected through modifiers, order, etc.
func (_m *DrugInteractionCheck) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this DrugInteractionCheck.
// Note that you need to call DrugInteractionCheck.Unwrap() before calling this method if this DrugInteractionCheck
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *DrugInteractionCheck) Update() *DrugInteractionCheckUpdateOne {
	return NewDrugInteractionCheckClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the DrugInteractionCheck entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *DrugInteractionCheck) Unwrap() *DrugInteractionCheck {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: DrugInteractionCheck is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *DrugInteractionCheck) String() string {
	var builder strings.Builder
	builder.WriteString("DrugInteractionCheck(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	if v := _m.PrescriptionID; v != nil {
		builder.WriteString("prescription_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OrderID; v != nil {
		builder.WriteString("order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("drug_skus=")
	builder.WriteString(fmt.Sprintf("%v", _m.DrugSkus))
	builder.WriteString(", ")
	builder.WriteString("result=")
	builder.WriteString(_m.Result)
	builder.WriteString(", ")
	builder.WriteString("details=")
	builder.WriteString(_m.Details)
	builder.WriteString(", ")
	if v := _m.CheckedBy; v != nil {
		builder.WriteString("checked_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("checked_at=")
	builder.WriteString(_m.CheckedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// DrugInteractionChecks is a parsable slice of DrugInteractionCheck.
type DrugInteractionChecks []*DrugInteractionCheck
