// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/pos-service/internal/ent/inventorysnapshot"
	"github.com/google/uuid"
)

// InventorySnapshotCreate is the builder for creating a InventorySnapshot entity.
type InventorySnapshotCreate struct {
	config
	mutation *InventorySnapshotMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *InventorySnapshotCreate) SetTenantID(v uuid.UUID) *InventorySnapshotCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetOutletID sets the "outlet_id" field.
func (_c *InventorySnapshotCreate) SetOutletID(v uuid.UUID) *InventorySnapshotCreate {
	_c.mutation.SetOutletID(v)
	return _c
}

// SetCatalogItemID sets the "catalog_item_id" field.
func (_c *InventorySnapshotCreate) SetCatalogItemID(v uuid.UUID) *InventorySnapshotCreate {
	_c.mutation.SetCatalogItemID(v)
	return _c
}

// SetQuantityOnHand sets the "quantity_on_hand" field.
func (_c *InventorySnapshotCreate) SetQuantityOnHand(v float64) *InventorySnapshotCreate {
	_c.mutation.SetQuantityOnHand(v)
	return _c
}

// SetCapturedAt sets the "captured_at" field.
func (_c *InventorySnapshotCreate) SetCapturedAt(v time.Time) *InventorySnapshotCreate {
	_c.mutation.SetCapturedAt(v)
	return _c
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_c *InventorySnapshotCreate) SetNillableCapturedAt(v *time.Time) *InventorySnapshotCreate {
	if v != nil {
		_c.SetCapturedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *InventorySnapshotCreate) SetID(v uuid.UUID) *InventorySnapshotCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *InventorySnapshotCreate) SetNillableID(v *uuid.UUID) *InventorySnapshotCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the InventorySnapshotMutation object of the builder.
func (_c *InventorySnapshotCreate) Mutation() *InventorySnapshotMutation {
	return _c.mutation
}

// Save creates the InventorySnapshot in the database.
func (_c *InventorySnapshotCreate) Save(ctx context.Context) (*InventorySnapshot, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InventorySnapshotCreate) SaveX(ctx context.Context) *InventorySnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventorySnapshotCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventorySnapshotCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InventorySnapshotCreate) defaults() {
	if _, ok := _c.mutation.CapturedAt(); !ok {
		v := inventorysnapshot.DefaultCapturedAt()
		_c.mutation.SetCapturedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := inventorysnapshot.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InventorySnapshotCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "InventorySnapshot.tenant_id"`)}
	}
	if _, ok := _c.mutation.OutletID(); !ok {
		return &ValidationError{Name: "outlet_id", err: errors.New(`ent: missing required field "InventorySnapshot.outlet_id"`)}
	}
	if _, ok := _c.mutation.CatalogItemID(); !ok {
		return &ValidationError{Name: "catalog_item_id", err: errors.New(`ent: missing required field "InventorySnapshot.catalog_item_id"`)}
	}
	if _, ok := _c.mutation.QuantityOnHand(); !ok {
		return &ValidationError{Name: "quantity_on_hand", err: errors.New(`ent: missing required field "InventorySnapshot.quantity_on_hand"`)}
	}
	if _, ok := _c.mutation.CapturedAt(); !ok {
		return &ValidationError{Name: "captured_at", err: errors.New(`ent: missing required field "InventorySnapshot.captured_at"`)}
	}
	return nil
}

func (_c *InventorySnapshotCreate) sqlSave(ctx context.Context) (*InventorySnapshot, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InventorySnapshotCreate) createSpec() (*InventorySnapshot, *sqlgraph.CreateSpec) {
	var (
		_node = &InventorySnapshot{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inventorysnapshot.Table, sqlgraph.NewFieldSpec(inventorysnapshot.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(inventorysnapshot.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.OutletID(); ok {
		_spec.SetField(inventorysnapshot.FieldOutletID, field.TypeUUID, value)
		_node.OutletID = value
	}
	if value, ok := _c.mutation.CatalogItemID(); ok {
		_spec.SetField(inventorysnapshot.FieldCatalogItemID, field.TypeUUID, value)
		_node.CatalogItemID = value
	}
	if value, ok := _c.mutation.QuantityOnHand(); ok {
		_spec.SetField(inventorysnapshot.FieldQuantityOnHand, field.TypeFloat64, value)
		_node.QuantityOnHand = value
	}
	if value, ok := _c.mutation.CapturedAt(); ok {
		_spec.SetField(inventorysnapshot.FieldCapturedAt, field.TypeTime, value)
		_node.CapturedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InventorySnapshot.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventorySnapshotUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *InventorySnapshotCreate) OnConflict(opts ...sql.ConflictOption) *InventorySnapshotUpsertOne {
	_c.conflict = opts
	return &InventorySnapshotUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InventorySnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InventorySnapshotCreate) OnConflictColumns(columns ...string) *InventorySnapshotUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InventorySnapshotUpsertOne{
		create: _c,
	}
}

type (
	// InventorySnapshotUpsertOne is the builder for "upsert"-ing
	//  one InventorySnapshot node.
	InventorySnapshotUpsertOne struct {
		create *InventorySnapshotCreate
	}

	// InventorySnapshotUpsert is the "OnConflict" setter.
	InventorySnapshotUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *InventorySnapshotUpsert) SetTenantID(v uuid.UUID) *InventorySnapshotUpsert {
	u.Set(inventorysnapshot.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *InventorySnapshotUpsert) UpdateTenantID() *InventorySnapshotUpsert {
	u.SetExcluded(inventorysnapshot.FieldTenantID)
	return u
}

// SetOutletID sets the "outlet_id" field.
func (u *InventorySnapshotUpsert) SetOutletID(v uuid.UUID) *InventorySnapshotUpsert {
	u.Set(inventorysnapshot.FieldOutletID, v)
	return u
}

// UpdateOutletID sets the "outlet_id" field to the value that was provided on create.
func (u *InventorySnapshotUpsert) UpdateOutletID() *InventorySnapshotUpsert {
	u.SetExcluded(inventorysnapshot.FieldOutletID)
	return u
}

// SetCatalogItemID sets the "catalog_item_id" field.
func (u *InventorySnapshotUpsert) SetCatalogItemID(v uuid.UUID) *InventorySnapshotUpsert {
	u.Set(inventorysnapshot.FieldCatalogItemID, v)
	return u
}

// UpdateCatalogItemID sets the "catalog_item_id" field to the value that was provided on create.
func (u *InventorySnapshotUpsert) UpdateCatalogItemID() *InventorySnapshotUpsert {
	u.SetExcluded(inventorysnapshot.FieldCatalogItemID)
	return u
}

// SetQuantityOnHand sets the "quantity_on_hand" field.
func (u *InventorySnapshotUpsert) SetQuantityOnHand(v float64) *InventorySnapshotUpsert {
	u.Set(inventorysnapshot.FieldQuantityOnHand, v)
	return u
}

// UpdateQuantityOnHand sets the "quantity_on_hand" field to the value that was provided on create.
func (u *InventorySnapshotUpsert) UpdateQuantityOnHand() *InventorySnapshotUpsert {
	u.SetExcluded(inventorysnapshot.FieldQuantityOnHand)
	return u
}

// AddQuantityOnHand adds v to the "quantity_on_hand" field.
func (u *InventorySnapshotUpsert) AddQuantityOnHand(v float64) *InventorySnapshotUpsert {
	u.Add(inventorysnapshot.FieldQuantityOnHand, v)
	return u
}

// SetCapturedAt sets the "captured_at" field.
func (u *InventorySnapshotUpsert) SetCapturedAt(v time.Time) *InventorySnapshotUpsert {
	u.Set(inventorysnapshot.FieldCapturedAt, v)
	return u
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *InventorySnapshotUpsert) UpdateCapturedAt() *InventorySnapshotUpsert {
	u.SetExcluded(inventorysnapshot.FieldCapturedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.InventorySnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(inventorysnapshot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InventorySnapshotUpsertOne) UpdateNewValues() *InventorySnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(inventorysnapshot.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InventorySnapshot.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InventorySnapshotUpsertOne) Ignore() *InventorySnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventorySnapshotUpsertOne) DoNothing() *InventorySnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventorySnapshotCreate.OnConflict
// documentation for more info.
func (u *InventorySnapshotUpsertOne) Update(set func(*InventorySnapshotUpsert)) *InventorySnapshotUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventorySnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *InventorySnapshotUpsertOne) SetTenantID(v uuid.UUID) *InventorySnapshotUpsertOne {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *InventorySnapshotUpsertOne) UpdateTenantID() *InventorySnapshotUpsertOne {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.UpdateTenantID()
	})
}

// SetOutletID sets the "outlet_id" field.
func (u *InventorySnapshotUpsertOne) SetOutletID(v uuid.UUID) *InventorySnapshotUpsertOne {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.SetOutletID(v)
	})
}

// UpdateOutletID sets the "outlet_id" field to the value that was provided on create.
func (u *InventorySnapshotUpsertOne) UpdateOutletID() *InventorySnapshotUpsertOne {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.UpdateOutletID()
	})
}

// SetCatalogItemID sets the "catalog_item_id" field.
func (u *InventorySnapshotUpsertOne) SetCatalogItemID(v uuid.UUID) *InventorySnapshotUpsertOne {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.SetCatalogItemID(v)
	})
}

// UpdateCatalogItemID sets the "catalog_item_id" field to the value that was provided on create.
func (u *InventorySnapshotUpsertOne) UpdateCatalogItemID() *InventorySnapshotUpsertOne {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.UpdateCatalogItemID()
	})
}

// SetQuantityOnHand sets the "quantity_on_hand" field.
func (u *InventorySnapshotUpsertOne) SetQuantityOnHand(v float64) *InventorySnapshotUpsertOne {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.SetQuantityOnHand(v)
	})
}

// AddQuantityOnHand adds v to the "quantity_on_hand" field.
func (u *InventorySnapshotUpsertOne) AddQuantityOnHand(v float64) *InventorySnapshotUpsertOne {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.AddQuantityOnHand(v)
	})
}

// UpdateQuantityOnHand sets the "quantity_on_hand" field to the value that was provided on create.
func (u *InventorySnapshotUpsertOne) UpdateQuantityOnHand() *InventorySnapshotUpsertOne {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.UpdateQuantityOnHand()
	})
}

// SetCapturedAt sets the "captured_at" field.
func (u *InventorySnapshotUpsertOne) SetCapturedAt(v time.Time) *InventorySnapshotUpsertOne {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.SetCapturedAt(v)
	})
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *InventorySnapshotUpsertOne) UpdateCapturedAt() *InventorySnapshotUpsertOne {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.UpdateCapturedAt()
	})
}

// Exec executes the query.
func (u *InventorySnapshotUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventorySnapshotCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventorySnapshotUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InventorySnapshotUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: InventorySnapshotUpsertOne.ID is not supported by MySQL driver. Use InventorySnapshotUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InventorySnapshotUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InventorySnapshotCreateBulk is the builder for creating many InventorySnapshot entities in bulk.
type InventorySnapshotCreateBulk struct {
	config
	err      error
	builders []*InventorySnapshotCreate
	conflict []sql.ConflictOption
}

// Save creates the InventorySnapshot entities in the database.
func (_c *InventorySnapshotCreateBulk) Save(ctx context.Context) ([]*InventorySnapshot, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InventorySnapshot, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventorySnapshotMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InventorySnapshotCreateBulk) SaveX(ctx context.Context) []*InventorySnapshot {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventorySnapshotCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventorySnapshotCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InventorySnapshot.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventorySnapshotUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *InventorySnapshotCreateBulk) OnConflict(opts ...sql.ConflictOption) *InventorySnapshotUpsertBulk {
	_c.conflict = opts
	return &InventorySnapshotUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InventorySnapshot.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InventorySnapshotCreateBulk) OnConflictColumns(columns ...string) *InventorySnapshotUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InventorySnapshotUpsertBulk{
		create: _c,
	}
}

// InventorySnapshotUpsertBulk is the builder for "upsert"-ing
// a bulk of InventorySnapshot nodes.
type InventorySnapshotUpsertBulk struct {
	create *InventorySnapshotCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InventorySnapshot.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(inventorysnapshot.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *InventorySnapshotUpsertBulk) UpdateNewValues() *InventorySnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(inventorysnapshot.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InventorySnapshot.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InventorySnapshotUpsertBulk) Ignore() *InventorySnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventorySnapshotUpsertBulk) DoNothing() *InventorySnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventorySnapshotCreateBulk.OnConflict
// documentation for more info.
func (u *InventorySnapshotUpsertBulk) Update(set func(*InventorySnapshotUpsert)) *InventorySnapshotUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventorySnapshotUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *InventorySnapshotUpsertBulk) SetTenantID(v uuid.UUID) *InventorySnapshotUpsertBulk {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *InventorySnapshotUpsertBulk) UpdateTenantID() *InventorySnapshotUpsertBulk {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.UpdateTenantID()
	})
}

// SetOutletID sets the "outlet_id" field.
func (u *InventorySnapshotUpsertBulk) SetOutletID(v uuid.UUID) *InventorySnapshotUpsertBulk {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.SetOutletID(v)
	})
}

// UpdateOutletID sets the "outlet_id" field to the value that was provided on create.
func (u *InventorySnapshotUpsertBulk) UpdateOutletID() *InventorySnapshotUpsertBulk {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.UpdateOutletID()
	})
}

// SetCatalogItemID sets the "catalog_item_id" field.
func (u *InventorySnapshotUpsertBulk) SetCatalogItemID(v uuid.UUID) *InventorySnapshotUpsertBulk {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.SetCatalogItemID(v)
	})
}

// UpdateCatalogItemID sets the "catalog_item_id" field to the value that was provided on create.
func (u *InventorySnapshotUpsertBulk) UpdateCatalogItemID() *InventorySnapshotUpsertBulk {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.UpdateCatalogItemID()
	})
}

// SetQuantityOnHand sets the "quantity_on_hand" field.
func (u *InventorySnapshotUpsertBulk) SetQuantityOnHand(v float64) *InventorySnapshotUpsertBulk {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.SetQuantityOnHand(v)
	})
}

// AddQuantityOnHand adds v to the "quantity_on_hand" field.
func (u *InventorySnapshotUpsertBulk) AddQuantityOnHand(v float64) *InventorySnapshotUpsertBulk {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.AddQuantityOnHand(v)
	})
}

// UpdateQuantityOnHand sets the "quantity_on_hand" field to the value that was provided on create.
func (u *InventorySnapshotUpsertBulk) UpdateQuantityOnHand() *InventorySnapshotUpsertBulk {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.UpdateQuantityOnHand()
	})
}

// SetCapturedAt sets the "captured_at" field.
func (u *InventorySnapshotUpsertBulk) SetCapturedAt(v time.Time) *InventorySnapshotUpsertBulk {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.SetCapturedAt(v)
	})
}

// UpdateCapturedAt sets the "captured_at" field to the value that was provided on create.
func (u *InventorySnapshotUpsertBulk) UpdateCapturedAt() *InventorySnapshotUpsertBulk {
	return u.Update(func(s *InventorySnapshotUpsert) {
		s.UpdateCapturedAt()
	})
}

// Exec executes the query.
func (u *InventorySnapshotUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InventorySnapshotCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventorySnapshotCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventorySnapshotUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
