// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/pos-service/internal/ent/inventorysnapshot"
	"github.com/bengobox/pos-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// InventorySnapshotUpdate is the builder for updating InventorySnapshot entities.
type InventorySnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *InventorySnapshotMutation
}

// Where appends a list predicates to the InventorySnapshotUpdate builder.
func (_u *InventorySnapshotUpdate) Where(ps ...predicate.InventorySnapshot) *InventorySnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTenantID sets the "tenant_id" field.
func (_u *InventorySnapshotUpdate) SetTenantID(v uuid.UUID) *InventorySnapshotUpdate {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *InventorySnapshotUpdate) SetNillableTenantID(v *uuid.UUID) *InventorySnapshotUpdate {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetOutletID sets the "outlet_id" field.
func (_u *InventorySnapshotUpdate) SetOutletID(v uuid.UUID) *InventorySnapshotUpdate {
	_u.mutation.SetOutletID(v)
	return _u
}

// SetNillableOutletID sets the "outlet_id" field if the given value is not nil.
func (_u *InventorySnapshotUpdate) SetNillableOutletID(v *uuid.UUID) *InventorySnapshotUpdate {
	if v != nil {
		_u.SetOutletID(*v)
	}
	return _u
}

// SetCatalogItemID sets the "catalog_item_id" field.
func (_u *InventorySnapshotUpdate) SetCatalogItemID(v uuid.UUID) *InventorySnapshotUpdate {
	_u.mutation.SetCatalogItemID(v)
	return _u
}

// SetNillableCatalogItemID sets the "catalog_item_id" field if the given value is not nil.
func (_u *InventorySnapshotUpdate) SetNillableCatalogItemID(v *uuid.UUID) *InventorySnapshotUpdate {
	if v != nil {
		_u.SetCatalogItemID(*v)
	}
	return _u
}

// SetQuantityOnHand sets the "quantity_on_hand" field.
func (_u *InventorySnapshotUpdate) SetQuantityOnHand(v float64) *InventorySnapshotUpdate {
	_u.mutation.ResetQuantityOnHand()
	_u.mutation.SetQuantityOnHand(v)
	return _u
}

// SetNillableQuantityOnHand sets the "quantity_on_hand" field if the given value is not nil.
func (_u *InventorySnapshotUpdate) SetNillableQuantityOnHand(v *float64) *InventorySnapshotUpdate {
	if v != nil {
		_u.SetQuantityOnHand(*v)
	}
	return _u
}

// AddQuantityOnHand adds value to the "quantity_on_hand" field.
func (_u *InventorySnapshotUpdate) AddQuantityOnHand(v float64) *InventorySnapshotUpdate {
	_u.mutation.AddQuantityOnHand(v)
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *InventorySnapshotUpdate) SetCapturedAt(v time.Time) *InventorySnapshotUpdate {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *InventorySnapshotUpdate) SetNillableCapturedAt(v *time.Time) *InventorySnapshotUpdate {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// Mutation returns the InventorySnapshotMutation object of the builder.
func (_u *InventorySnapshotUpdate) Mutation() *InventorySnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InventorySnapshotUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InventorySnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InventorySnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InventorySnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InventorySnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(inventorysnapshot.Table, inventorysnapshot.Columns, sqlgraph.NewFieldSpec(inventorysnapshot.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(inventorysnapshot.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.OutletID(); ok {
		_spec.SetField(inventorysnapshot.FieldOutletID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.CatalogItemID(); ok {
		_spec.SetField(inventorysnapshot.FieldCatalogItemID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.QuantityOnHand(); ok {
		_spec.SetField(inventorysnapshot.FieldQuantityOnHand, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantityOnHand(); ok {
		_spec.AddField(inventorysnapshot.FieldQuantityOnHand, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(inventorysnapshot.FieldCapturedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inventorysnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InventorySnapshotUpdateOne is the builder for updating a single InventorySnapshot entity.
type InventorySnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InventorySnapshotMutation
}

// SetTenantID sets the "tenant_id" field.
func (_u *InventorySnapshotUpdateOne) SetTenantID(v uuid.UUID) *InventorySnapshotUpdateOne {
	_u.mutation.SetTenantID(v)
	return _u
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (_u *InventorySnapshotUpdateOne) SetNillableTenantID(v *uuid.UUID) *InventorySnapshotUpdateOne {
	if v != nil {
		_u.SetTenantID(*v)
	}
	return _u
}

// SetOutletID sets the "outlet_id" field.
func (_u *InventorySnapshotUpdateOne) SetOutletID(v uuid.UUID) *InventorySnapshotUpdateOne {
	_u.mutation.SetOutletID(v)
	return _u
}

// SetNillableOutletID sets the "outlet_id" field if the given value is not nil.
func (_u *InventorySnapshotUpdateOne) SetNillableOutletID(v *uuid.UUID) *InventorySnapshotUpdateOne {
	if v != nil {
		_u.SetOutletID(*v)
	}
	return _u
}

// SetCatalogItemID sets the "catalog_item_id" field.
func (_u *InventorySnapshotUpdateOne) SetCatalogItemID(v uuid.UUID) *InventorySnapshotUpdateOne {
	_u.mutation.SetCatalogItemID(v)
	return _u
}

// SetNillableCatalogItemID sets the "catalog_item_id" field if the given value is not nil.
func (_u *InventorySnapshotUpdateOne) SetNillableCatalogItemID(v *uuid.UUID) *InventorySnapshotUpdateOne {
	if v != nil {
		_u.SetCatalogItemID(*v)
	}
	return _u
}

// SetQuantityOnHand sets the "quantity_on_hand" field.
func (_u *InventorySnapshotUpdateOne) SetQuantityOnHand(v float64) *InventorySnapshotUpdateOne {
	_u.mutation.ResetQuantityOnHand()
	_u.mutation.SetQuantityOnHand(v)
	return _u
}

// SetNillableQuantityOnHand sets the "quantity_on_hand" field if the given value is not nil.
func (_u *InventorySnapshotUpdateOne) SetNillableQuantityOnHand(v *float64) *InventorySnapshotUpdateOne {
	if v != nil {
		_u.SetQuantityOnHand(*v)
	}
	return _u
}

// AddQuantityOnHand adds value to the "quantity_on_hand" field.
func (_u *InventorySnapshotUpdateOne) AddQuantityOnHand(v float64) *InventorySnapshotUpdateOne {
	_u.mutation.AddQuantityOnHand(v)
	return _u
}

// SetCapturedAt sets the "captured_at" field.
func (_u *InventorySnapshotUpdateOne) SetCapturedAt(v time.Time) *InventorySnapshotUpdateOne {
	_u.mutation.SetCapturedAt(v)
	return _u
}

// SetNillableCapturedAt sets the "captured_at" field if the given value is not nil.
func (_u *InventorySnapshotUpdateOne) SetNillableCapturedAt(v *time.Time) *InventorySnapshotUpdateOne {
	if v != nil {
		_u.SetCapturedAt(*v)
	}
	return _u
}

// Mutation returns the InventorySnapshotMutation object of the builder.
func (_u *InventorySnapshotUpdateOne) Mutation() *InventorySnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the InventorySnapshotUpdate builder.
func (_u *InventorySnapshotUpdateOne) Where(ps ...predicate.InventorySnapshot) *InventorySnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InventorySnapshotUpdateOne) Select(field string, fields ...string) *InventorySnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InventorySnapshot entity.
func (_u *InventorySnapshotUpdateOne) Save(ctx context.Context) (*InventorySnapshot, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InventorySnapshotUpdateOne) SaveX(ctx context.Context) *InventorySnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InventorySnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InventorySnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *InventorySnapshotUpdateOne) sqlSave(ctx context.Context) (_node *InventorySnapshot, err error) {
	_spec := sqlgraph.NewUpdateSpec(inventorysnapshot.Table, inventorysnapshot.Columns, sqlgraph.NewFieldSpec(inventorysnapshot.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "InventorySnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, inventorysnapshot.FieldID)
		for _, f := range fields {
			if !inventorysnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != inventorysnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.TenantID(); ok {
		_spec.SetField(inventorysnapshot.FieldTenantID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.OutletID(); ok {
		_spec.SetField(inventorysnapshot.FieldOutletID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.CatalogItemID(); ok {
		_spec.SetField(inventorysnapshot.FieldCatalogItemID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.QuantityOnHand(); ok {
		_spec.SetField(inventorysnapshot.FieldQuantityOnHand, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuantityOnHand(); ok {
		_spec.AddField(inventorysnapshot.FieldQuantityOnHand, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CapturedAt(); ok {
		_spec.SetField(inventorysnapshot.FieldCapturedAt, field.TypeTime, value)
	}
	_node = &InventorySnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{inventorysnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
