// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/kdsstation"
	"github.com/bengobox/pos-service/internal/ent/kdsticket"
	"github.com/google/uuid"
)

// KDSTicket is the model entity for the KDSTicket schema.
type KDSTicket struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// FK to KDSStation
	StationID uuid.UUID `json:"station_id,omitempty"`
	// POS or online order reference
	OrderID uuid.UUID `json:"order_id,omitempty"`
	// OrderNumber holds the value of the "order_number" field.
	OrderNumber string `json:"order_number,omitempty"`
	// Status holds the value of the "status" field.
	Status kdsticket.Status `json:"status,omitempty"`
	// Line items for this station
	Items []map[string]interface{} `json:"items,omitempty"`
	// ReceivedAt holds the value of the "received_at" field.
	ReceivedAt time.Time `json:"received_at,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt *time.Time `json:"started_at,omitempty"`
	// CompletedAt holds the value of the "completed_at" field.
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the KDSTicketQuery when eager-loading is set.
	Edges        KDSTicketEdges `json:"edges"`
	selectValues sql.SelectValues
}

// KDSTicketEdges holds the relations/edges for other nodes in the graph.
type KDSTicketEdges struct {
	// Station holds the value of the station edge.
	Station *KDSStation `json:"station,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// StationOrErr returns the Station value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e KDSTicketEdges) StationOrErr() (*KDSStation, error) {
	if e.Station != nil {
		return e.Station, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: kdsstation.Label}
	}
	return nil, &NotLoadedError{edge: "station"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*KDSTicket) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case kdsticket.FieldItems:
			values[i] = new([]byte)
		case kdsticket.FieldPriority:
			values[i] = new(sql.NullInt64)
		case kdsticket.FieldOrderNumber, kdsticket.FieldStatus:
			values[i] = new(sql.NullString)
		case kdsticket.FieldReceivedAt, kdsticket.FieldStartedAt, kdsticket.FieldCompletedAt:
			values[i] = new(sql.NullTime)
		case kdsticket.FieldID, kdsticket.FieldTenantID, kdsticket.FieldStationID, kdsticket.FieldOrderID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the KDSTicket fields.
func (_m *KDSTicket) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case kdsticket.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case kdsticket.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case kdsticket.FieldStationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field station_id", values[i])
			} else if value != nil {
				_m.StationID = *value
			}
		case kdsticket.FieldOrderID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value != nil {
				_m.OrderID = *value
			}
		case kdsticket.FieldOrderNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field order_number", values[i])
			} else if value.Valid {
				_m.OrderNumber = value.String
			}
		case kdsticket.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = kdsticket.Status(value.String)
			}
		case kdsticket.FieldItems:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field items", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Items); err != nil {
					return fmt.Errorf("unmarshal field items: %w", err)
				}
			}
		case kdsticket.FieldReceivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field received_at", values[i])
			} else if value.Valid {
				_m.ReceivedAt = value.Time
			}
		case kdsticket.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = new(time.Time)
				*_m.StartedAt = value.Time
			}
		case kdsticket.FieldCompletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field completed_at", values[i])
			} else if value.Valid {
				_m.CompletedAt = new(time.Time)
				*_m.CompletedAt = value.Time
			}
		case kdsticket.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the KDSTicket.
// This includes values selected through modifiers, order, etc.
func (_m *KDSTicket) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryStation queries the "station" edge of the KDSTicket entity.
func (_m *KDSTicket) QueryStation() *KDSStationQuery {
	return NewKDSTicketClient(_m.config).QueryStation(_m)
}

// Update returns a builder for updating this KDSTicket.
// Note that you need to call KDSTicket.Unwrap() before calling this method if this KDSTicket
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *KDSTicket) Update() *KDSTicketUpdateOne {
	return NewKDSTicketClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the KDSTicket entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *KDSTicket) Unwrap() *KDSTicket {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: KDSTicket is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *KDSTicket) String() string {
	var builder strings.Builder
	builder.WriteString("KDSTicket(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("station_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StationID))
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("order_number=")
	builder.WriteString(_m.OrderNumber)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("items=")
	builder.WriteString(fmt.Sprintf("%v", _m.Items))
	builder.WriteString(", ")
	builder.WriteString("received_at=")
	builder.WriteString(_m.ReceivedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.StartedAt; v != nil {
		builder.WriteString("started_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CompletedAt; v != nil {
		builder.WriteString("completed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteByte(')')
	return builder.String()
}

// KDSTickets is a parsable slice of KDSTicket.
type KDSTickets []*KDSTicket
