// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/pos-service/internal/ent/layawayplan"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// LayawayPlanCreate is the builder for creating a LayawayPlan entity.
type LayawayPlanCreate struct {
	config
	mutation *LayawayPlanMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *LayawayPlanCreate) SetTenantID(v uuid.UUID) *LayawayPlanCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetOutletID sets the "outlet_id" field.
func (_c *LayawayPlanCreate) SetOutletID(v uuid.UUID) *LayawayPlanCreate {
	_c.mutation.SetOutletID(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *LayawayPlanCreate) SetOrderID(v uuid.UUID) *LayawayPlanCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_c *LayawayPlanCreate) SetNillableOrderID(v *uuid.UUID) *LayawayPlanCreate {
	if v != nil {
		_c.SetOrderID(*v)
	}
	return _c
}

// SetCustomerName sets the "customer_name" field.
func (_c *LayawayPlanCreate) SetCustomerName(v string) *LayawayPlanCreate {
	_c.mutation.SetCustomerName(v)
	return _c
}

// SetCustomerPhone sets the "customer_phone" field.
func (_c *LayawayPlanCreate) SetCustomerPhone(v string) *LayawayPlanCreate {
	_c.mutation.SetCustomerPhone(v)
	return _c
}

// SetNillableCustomerPhone sets the "customer_phone" field if the given value is not nil.
func (_c *LayawayPlanCreate) SetNillableCustomerPhone(v *string) *LayawayPlanCreate {
	if v != nil {
		_c.SetCustomerPhone(*v)
	}
	return _c
}

// SetCustomerEmail sets the "customer_email" field.
func (_c *LayawayPlanCreate) SetCustomerEmail(v string) *LayawayPlanCreate {
	_c.mutation.SetCustomerEmail(v)
	return _c
}

// SetNillableCustomerEmail sets the "customer_email" field if the given value is not nil.
func (_c *LayawayPlanCreate) SetNillableCustomerEmail(v *string) *LayawayPlanCreate {
	if v != nil {
		_c.SetCustomerEmail(*v)
	}
	return _c
}

// SetTotalAmount sets the "total_amount" field.
func (_c *LayawayPlanCreate) SetTotalAmount(v decimal.Decimal) *LayawayPlanCreate {
	_c.mutation.SetTotalAmount(v)
	return _c
}

// SetDepositAmount sets the "deposit_amount" field.
func (_c *LayawayPlanCreate) SetDepositAmount(v decimal.Decimal) *LayawayPlanCreate {
	_c.mutation.SetDepositAmount(v)
	return _c
}

// SetPaidAmount sets the "paid_amount" field.
func (_c *LayawayPlanCreate) SetPaidAmount(v decimal.Decimal) *LayawayPlanCreate {
	_c.mutation.SetPaidAmount(v)
	return _c
}

// SetRemainingAmount sets the "remaining_amount" field.
func (_c *LayawayPlanCreate) SetRemainingAmount(v decimal.Decimal) *LayawayPlanCreate {
	_c.mutation.SetRemainingAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *LayawayPlanCreate) SetStatus(v string) *LayawayPlanCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *LayawayPlanCreate) SetNillableStatus(v *string) *LayawayPlanCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *LayawayPlanCreate) SetNotes(v string) *LayawayPlanCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *LayawayPlanCreate) SetNillableNotes(v *string) *LayawayPlanCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetDueDate sets the "due_date" field.
func (_c *LayawayPlanCreate) SetDueDate(v time.Time) *LayawayPlanCreate {
	_c.mutation.SetDueDate(v)
	return _c
}

// SetNillableDueDate sets the "due_date" field if the given value is not nil.
func (_c *LayawayPlanCreate) SetNillableDueDate(v *time.Time) *LayawayPlanCreate {
	if v != nil {
		_c.SetDueDate(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LayawayPlanCreate) SetCreatedAt(v time.Time) *LayawayPlanCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LayawayPlanCreate) SetNillableCreatedAt(v *time.Time) *LayawayPlanCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LayawayPlanCreate) SetUpdatedAt(v time.Time) *LayawayPlanCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LayawayPlanCreate) SetNillableUpdatedAt(v *time.Time) *LayawayPlanCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *LayawayPlanCreate) SetID(v uuid.UUID) *LayawayPlanCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *LayawayPlanCreate) SetNillableID(v *uuid.UUID) *LayawayPlanCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the LayawayPlanMutation object of the builder.
func (_c *LayawayPlanCreate) Mutation() *LayawayPlanMutation {
	return _c.mutation
}

// Save creates the LayawayPlan in the database.
func (_c *LayawayPlanCreate) Save(ctx context.Context) (*LayawayPlan, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LayawayPlanCreate) SaveX(ctx context.Context) *LayawayPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LayawayPlanCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LayawayPlanCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LayawayPlanCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := layawayplan.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := layawayplan.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := layawayplan.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := layawayplan.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LayawayPlanCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "LayawayPlan.tenant_id"`)}
	}
	if _, ok := _c.mutation.OutletID(); !ok {
		return &ValidationError{Name: "outlet_id", err: errors.New(`ent: missing required field "LayawayPlan.outlet_id"`)}
	}
	if _, ok := _c.mutation.CustomerName(); !ok {
		return &ValidationError{Name: "customer_name", err: errors.New(`ent: missing required field "LayawayPlan.customer_name"`)}
	}
	if v, ok := _c.mutation.CustomerName(); ok {
		if err := layawayplan.CustomerNameValidator(v); err != nil {
			return &ValidationError{Name: "customer_name", err: fmt.Errorf(`ent: validator failed for field "LayawayPlan.customer_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TotalAmount(); !ok {
		return &ValidationError{Name: "total_amount", err: errors.New(`ent: missing required field "LayawayPlan.total_amount"`)}
	}
	if _, ok := _c.mutation.DepositAmount(); !ok {
		return &ValidationError{Name: "deposit_amount", err: errors.New(`ent: missing required field "LayawayPlan.deposit_amount"`)}
	}
	if _, ok := _c.mutation.PaidAmount(); !ok {
		return &ValidationError{Name: "paid_amount", err: errors.New(`ent: missing required field "LayawayPlan.paid_amount"`)}
	}
	if _, ok := _c.mutation.RemainingAmount(); !ok {
		return &ValidationError{Name: "remaining_amount", err: errors.New(`ent: missing required field "LayawayPlan.remaining_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "LayawayPlan.status"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LayawayPlan.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LayawayPlan.updated_at"`)}
	}
	return nil
}

func (_c *LayawayPlanCreate) sqlSave(ctx context.Context) (*LayawayPlan, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LayawayPlanCreate) createSpec() (*LayawayPlan, *sqlgraph.CreateSpec) {
	var (
		_node = &LayawayPlan{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(layawayplan.Table, sqlgraph.NewFieldSpec(layawayplan.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(layawayplan.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.OutletID(); ok {
		_spec.SetField(layawayplan.FieldOutletID, field.TypeUUID, value)
		_node.OutletID = value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(layawayplan.FieldOrderID, field.TypeUUID, value)
		_node.OrderID = &value
	}
	if value, ok := _c.mutation.CustomerName(); ok {
		_spec.SetField(layawayplan.FieldCustomerName, field.TypeString, value)
		_node.CustomerName = value
	}
	if value, ok := _c.mutation.CustomerPhone(); ok {
		_spec.SetField(layawayplan.FieldCustomerPhone, field.TypeString, value)
		_node.CustomerPhone = value
	}
	if value, ok := _c.mutation.CustomerEmail(); ok {
		_spec.SetField(layawayplan.FieldCustomerEmail, field.TypeString, value)
		_node.CustomerEmail = value
	}
	if value, ok := _c.mutation.TotalAmount(); ok {
		_spec.SetField(layawayplan.FieldTotalAmount, field.TypeFloat64, value)
		_node.TotalAmount = value
	}
	if value, ok := _c.mutation.DepositAmount(); ok {
		_spec.SetField(layawayplan.FieldDepositAmount, field.TypeFloat64, value)
		_node.DepositAmount = value
	}
	if value, ok := _c.mutation.PaidAmount(); ok {
		_spec.SetField(layawayplan.FieldPaidAmount, field.TypeFloat64, value)
		_node.PaidAmount = value
	}
	if value, ok := _c.mutation.RemainingAmount(); ok {
		_spec.SetField(layawayplan.FieldRemainingAmount, field.TypeFloat64, value)
		_node.RemainingAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(layawayplan.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(layawayplan.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.DueDate(); ok {
		_spec.SetField(layawayplan.FieldDueDate, field.TypeTime, value)
		_node.DueDate = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(layawayplan.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(layawayplan.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LayawayPlan.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LayawayPlanUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *LayawayPlanCreate) OnConflict(opts ...sql.ConflictOption) *LayawayPlanUpsertOne {
	_c.conflict = opts
	return &LayawayPlanUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LayawayPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LayawayPlanCreate) OnConflictColumns(columns ...string) *LayawayPlanUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LayawayPlanUpsertOne{
		create: _c,
	}
}

type (
	// LayawayPlanUpsertOne is the builder for "upsert"-ing
	//  one LayawayPlan node.
	LayawayPlanUpsertOne struct {
		create *LayawayPlanCreate
	}

	// LayawayPlanUpsert is the "OnConflict" setter.
	LayawayPlanUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *LayawayPlanUpsert) SetTenantID(v uuid.UUID) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdateTenantID() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldTenantID)
	return u
}

// SetOutletID sets the "outlet_id" field.
func (u *LayawayPlanUpsert) SetOutletID(v uuid.UUID) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldOutletID, v)
	return u
}

// UpdateOutletID sets the "outlet_id" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdateOutletID() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldOutletID)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *LayawayPlanUpsert) SetOrderID(v uuid.UUID) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdateOrderID() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldOrderID)
	return u
}

// ClearOrderID clears the value of the "order_id" field.
func (u *LayawayPlanUpsert) ClearOrderID() *LayawayPlanUpsert {
	u.SetNull(layawayplan.FieldOrderID)
	return u
}

// SetCustomerName sets the "customer_name" field.
func (u *LayawayPlanUpsert) SetCustomerName(v string) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldCustomerName, v)
	return u
}

// UpdateCustomerName sets the "customer_name" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdateCustomerName() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldCustomerName)
	return u
}

// SetCustomerPhone sets the "customer_phone" field.
func (u *LayawayPlanUpsert) SetCustomerPhone(v string) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldCustomerPhone, v)
	return u
}

// UpdateCustomerPhone sets the "customer_phone" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdateCustomerPhone() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldCustomerPhone)
	return u
}

// ClearCustomerPhone clears the value of the "customer_phone" field.
func (u *LayawayPlanUpsert) ClearCustomerPhone() *LayawayPlanUpsert {
	u.SetNull(layawayplan.FieldCustomerPhone)
	return u
}

// SetCustomerEmail sets the "customer_email" field.
func (u *LayawayPlanUpsert) SetCustomerEmail(v string) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldCustomerEmail, v)
	return u
}

// UpdateCustomerEmail sets the "customer_email" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdateCustomerEmail() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldCustomerEmail)
	return u
}

// ClearCustomerEmail clears the value of the "customer_email" field.
func (u *LayawayPlanUpsert) ClearCustomerEmail() *LayawayPlanUpsert {
	u.SetNull(layawayplan.FieldCustomerEmail)
	return u
}

// SetTotalAmount sets the "total_amount" field.
func (u *LayawayPlanUpsert) SetTotalAmount(v decimal.Decimal) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldTotalAmount, v)
	return u
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdateTotalAmount() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldTotalAmount)
	return u
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *LayawayPlanUpsert) AddTotalAmount(v decimal.Decimal) *LayawayPlanUpsert {
	u.Add(layawayplan.FieldTotalAmount, v)
	return u
}

// SetDepositAmount sets the "deposit_amount" field.
func (u *LayawayPlanUpsert) SetDepositAmount(v decimal.Decimal) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldDepositAmount, v)
	return u
}

// UpdateDepositAmount sets the "deposit_amount" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdateDepositAmount() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldDepositAmount)
	return u
}

// AddDepositAmount adds v to the "deposit_amount" field.
func (u *LayawayPlanUpsert) AddDepositAmount(v decimal.Decimal) *LayawayPlanUpsert {
	u.Add(layawayplan.FieldDepositAmount, v)
	return u
}

// SetPaidAmount sets the "paid_amount" field.
func (u *LayawayPlanUpsert) SetPaidAmount(v decimal.Decimal) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldPaidAmount, v)
	return u
}

// UpdatePaidAmount sets the "paid_amount" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdatePaidAmount() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldPaidAmount)
	return u
}

// AddPaidAmount adds v to the "paid_amount" field.
func (u *LayawayPlanUpsert) AddPaidAmount(v decimal.Decimal) *LayawayPlanUpsert {
	u.Add(layawayplan.FieldPaidAmount, v)
	return u
}

// SetRemainingAmount sets the "remaining_amount" field.
func (u *LayawayPlanUpsert) SetRemainingAmount(v decimal.Decimal) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldRemainingAmount, v)
	return u
}

// UpdateRemainingAmount sets the "remaining_amount" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdateRemainingAmount() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldRemainingAmount)
	return u
}

// AddRemainingAmount adds v to the "remaining_amount" field.
func (u *LayawayPlanUpsert) AddRemainingAmount(v decimal.Decimal) *LayawayPlanUpsert {
	u.Add(layawayplan.FieldRemainingAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *LayawayPlanUpsert) SetStatus(v string) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdateStatus() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldStatus)
	return u
}

// SetNotes sets the "notes" field.
func (u *LayawayPlanUpsert) SetNotes(v string) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdateNotes() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *LayawayPlanUpsert) ClearNotes() *LayawayPlanUpsert {
	u.SetNull(layawayplan.FieldNotes)
	return u
}

// SetDueDate sets the "due_date" field.
func (u *LayawayPlanUpsert) SetDueDate(v time.Time) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldDueDate, v)
	return u
}

// UpdateDueDate sets the "due_date" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdateDueDate() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldDueDate)
	return u
}

// ClearDueDate clears the value of the "due_date" field.
func (u *LayawayPlanUpsert) ClearDueDate() *LayawayPlanUpsert {
	u.SetNull(layawayplan.FieldDueDate)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LayawayPlanUpsert) SetUpdatedAt(v time.Time) *LayawayPlanUpsert {
	u.Set(layawayplan.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LayawayPlanUpsert) UpdateUpdatedAt() *LayawayPlanUpsert {
	u.SetExcluded(layawayplan.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.LayawayPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(layawayplan.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LayawayPlanUpsertOne) UpdateNewValues() *LayawayPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(layawayplan.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(layawayplan.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LayawayPlan.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LayawayPlanUpsertOne) Ignore() *LayawayPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LayawayPlanUpsertOne) DoNothing() *LayawayPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LayawayPlanCreate.OnConflict
// documentation for more info.
func (u *LayawayPlanUpsertOne) Update(set func(*LayawayPlanUpsert)) *LayawayPlanUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LayawayPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *LayawayPlanUpsertOne) SetTenantID(v uuid.UUID) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdateTenantID() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateTenantID()
	})
}

// SetOutletID sets the "outlet_id" field.
func (u *LayawayPlanUpsertOne) SetOutletID(v uuid.UUID) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetOutletID(v)
	})
}

// UpdateOutletID sets the "outlet_id" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdateOutletID() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateOutletID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *LayawayPlanUpsertOne) SetOrderID(v uuid.UUID) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdateOrderID() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *LayawayPlanUpsertOne) ClearOrderID() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.ClearOrderID()
	})
}

// SetCustomerName sets the "customer_name" field.
func (u *LayawayPlanUpsertOne) SetCustomerName(v string) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetCustomerName(v)
	})
}

// UpdateCustomerName sets the "customer_name" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdateCustomerName() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateCustomerName()
	})
}

// SetCustomerPhone sets the "customer_phone" field.
func (u *LayawayPlanUpsertOne) SetCustomerPhone(v string) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetCustomerPhone(v)
	})
}

// UpdateCustomerPhone sets the "customer_phone" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdateCustomerPhone() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateCustomerPhone()
	})
}

// ClearCustomerPhone clears the value of the "customer_phone" field.
func (u *LayawayPlanUpsertOne) ClearCustomerPhone() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.ClearCustomerPhone()
	})
}

// SetCustomerEmail sets the "customer_email" field.
func (u *LayawayPlanUpsertOne) SetCustomerEmail(v string) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetCustomerEmail(v)
	})
}

// UpdateCustomerEmail sets the "customer_email" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdateCustomerEmail() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateCustomerEmail()
	})
}

// ClearCustomerEmail clears the value of the "customer_email" field.
func (u *LayawayPlanUpsertOne) ClearCustomerEmail() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.ClearCustomerEmail()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *LayawayPlanUpsertOne) SetTotalAmount(v decimal.Decimal) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *LayawayPlanUpsertOne) AddTotalAmount(v decimal.Decimal) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdateTotalAmount() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetDepositAmount sets the "deposit_amount" field.
func (u *LayawayPlanUpsertOne) SetDepositAmount(v decimal.Decimal) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetDepositAmount(v)
	})
}

// AddDepositAmount adds v to the "deposit_amount" field.
func (u *LayawayPlanUpsertOne) AddDepositAmount(v decimal.Decimal) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.AddDepositAmount(v)
	})
}

// UpdateDepositAmount sets the "deposit_amount" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdateDepositAmount() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateDepositAmount()
	})
}

// SetPaidAmount sets the "paid_amount" field.
func (u *LayawayPlanUpsertOne) SetPaidAmount(v decimal.Decimal) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetPaidAmount(v)
	})
}

// AddPaidAmount adds v to the "paid_amount" field.
func (u *LayawayPlanUpsertOne) AddPaidAmount(v decimal.Decimal) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.AddPaidAmount(v)
	})
}

// UpdatePaidAmount sets the "paid_amount" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdatePaidAmount() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdatePaidAmount()
	})
}

// SetRemainingAmount sets the "remaining_amount" field.
func (u *LayawayPlanUpsertOne) SetRemainingAmount(v decimal.Decimal) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetRemainingAmount(v)
	})
}

// AddRemainingAmount adds v to the "remaining_amount" field.
func (u *LayawayPlanUpsertOne) AddRemainingAmount(v decimal.Decimal) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.AddRemainingAmount(v)
	})
}

// UpdateRemainingAmount sets the "remaining_amount" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdateRemainingAmount() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateRemainingAmount()
	})
}

// SetStatus sets the "status" field.
func (u *LayawayPlanUpsertOne) SetStatus(v string) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdateStatus() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *LayawayPlanUpsertOne) SetNotes(v string) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdateNotes() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *LayawayPlanUpsertOne) ClearNotes() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.ClearNotes()
	})
}

// SetDueDate sets the "due_date" field.
func (u *LayawayPlanUpsertOne) SetDueDate(v time.Time) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetDueDate(v)
	})
}

// UpdateDueDate sets the "due_date" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdateDueDate() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateDueDate()
	})
}

// ClearDueDate clears the value of the "due_date" field.
func (u *LayawayPlanUpsertOne) ClearDueDate() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.ClearDueDate()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LayawayPlanUpsertOne) SetUpdatedAt(v time.Time) *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LayawayPlanUpsertOne) UpdateUpdatedAt() *LayawayPlanUpsertOne {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LayawayPlanUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LayawayPlanCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LayawayPlanUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LayawayPlanUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: LayawayPlanUpsertOne.ID is not supported by MySQL driver. Use LayawayPlanUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LayawayPlanUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LayawayPlanCreateBulk is the builder for creating many LayawayPlan entities in bulk.
type LayawayPlanCreateBulk struct {
	config
	err      error
	builders []*LayawayPlanCreate
	conflict []sql.ConflictOption
}

// Save creates the LayawayPlan entities in the database.
func (_c *LayawayPlanCreateBulk) Save(ctx context.Context) ([]*LayawayPlan, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LayawayPlan, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LayawayPlanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LayawayPlanCreateBulk) SaveX(ctx context.Context) []*LayawayPlan {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LayawayPlanCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LayawayPlanCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LayawayPlan.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LayawayPlanUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *LayawayPlanCreateBulk) OnConflict(opts ...sql.ConflictOption) *LayawayPlanUpsertBulk {
	_c.conflict = opts
	return &LayawayPlanUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LayawayPlan.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LayawayPlanCreateBulk) OnConflictColumns(columns ...string) *LayawayPlanUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LayawayPlanUpsertBulk{
		create: _c,
	}
}

// LayawayPlanUpsertBulk is the builder for "upsert"-ing
// a bulk of LayawayPlan nodes.
type LayawayPlanUpsertBulk struct {
	create *LayawayPlanCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LayawayPlan.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(layawayplan.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *LayawayPlanUpsertBulk) UpdateNewValues() *LayawayPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(layawayplan.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(layawayplan.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LayawayPlan.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LayawayPlanUpsertBulk) Ignore() *LayawayPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LayawayPlanUpsertBulk) DoNothing() *LayawayPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LayawayPlanCreateBulk.OnConflict
// documentation for more info.
func (u *LayawayPlanUpsertBulk) Update(set func(*LayawayPlanUpsert)) *LayawayPlanUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LayawayPlanUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *LayawayPlanUpsertBulk) SetTenantID(v uuid.UUID) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdateTenantID() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateTenantID()
	})
}

// SetOutletID sets the "outlet_id" field.
func (u *LayawayPlanUpsertBulk) SetOutletID(v uuid.UUID) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetOutletID(v)
	})
}

// UpdateOutletID sets the "outlet_id" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdateOutletID() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateOutletID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *LayawayPlanUpsertBulk) SetOrderID(v uuid.UUID) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdateOrderID() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateOrderID()
	})
}

// ClearOrderID clears the value of the "order_id" field.
func (u *LayawayPlanUpsertBulk) ClearOrderID() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.ClearOrderID()
	})
}

// SetCustomerName sets the "customer_name" field.
func (u *LayawayPlanUpsertBulk) SetCustomerName(v string) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetCustomerName(v)
	})
}

// UpdateCustomerName sets the "customer_name" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdateCustomerName() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateCustomerName()
	})
}

// SetCustomerPhone sets the "customer_phone" field.
func (u *LayawayPlanUpsertBulk) SetCustomerPhone(v string) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetCustomerPhone(v)
	})
}

// UpdateCustomerPhone sets the "customer_phone" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdateCustomerPhone() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateCustomerPhone()
	})
}

// ClearCustomerPhone clears the value of the "customer_phone" field.
func (u *LayawayPlanUpsertBulk) ClearCustomerPhone() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.ClearCustomerPhone()
	})
}

// SetCustomerEmail sets the "customer_email" field.
func (u *LayawayPlanUpsertBulk) SetCustomerEmail(v string) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetCustomerEmail(v)
	})
}

// UpdateCustomerEmail sets the "customer_email" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdateCustomerEmail() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateCustomerEmail()
	})
}

// ClearCustomerEmail clears the value of the "customer_email" field.
func (u *LayawayPlanUpsertBulk) ClearCustomerEmail() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.ClearCustomerEmail()
	})
}

// SetTotalAmount sets the "total_amount" field.
func (u *LayawayPlanUpsertBulk) SetTotalAmount(v decimal.Decimal) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetTotalAmount(v)
	})
}

// AddTotalAmount adds v to the "total_amount" field.
func (u *LayawayPlanUpsertBulk) AddTotalAmount(v decimal.Decimal) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.AddTotalAmount(v)
	})
}

// UpdateTotalAmount sets the "total_amount" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdateTotalAmount() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateTotalAmount()
	})
}

// SetDepositAmount sets the "deposit_amount" field.
func (u *LayawayPlanUpsertBulk) SetDepositAmount(v decimal.Decimal) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetDepositAmount(v)
	})
}

// AddDepositAmount adds v to the "deposit_amount" field.
func (u *LayawayPlanUpsertBulk) AddDepositAmount(v decimal.Decimal) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.AddDepositAmount(v)
	})
}

// UpdateDepositAmount sets the "deposit_amount" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdateDepositAmount() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateDepositAmount()
	})
}

// SetPaidAmount sets the "paid_amount" field.
func (u *LayawayPlanUpsertBulk) SetPaidAmount(v decimal.Decimal) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetPaidAmount(v)
	})
}

// AddPaidAmount adds v to the "paid_amount" field.
func (u *LayawayPlanUpsertBulk) AddPaidAmount(v decimal.Decimal) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.AddPaidAmount(v)
	})
}

// UpdatePaidAmount sets the "paid_amount" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdatePaidAmount() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdatePaidAmount()
	})
}

// SetRemainingAmount sets the "remaining_amount" field.
func (u *LayawayPlanUpsertBulk) SetRemainingAmount(v decimal.Decimal) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetRemainingAmount(v)
	})
}

// AddRemainingAmount adds v to the "remaining_amount" field.
func (u *LayawayPlanUpsertBulk) AddRemainingAmount(v decimal.Decimal) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.AddRemainingAmount(v)
	})
}

// UpdateRemainingAmount sets the "remaining_amount" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdateRemainingAmount() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateRemainingAmount()
	})
}

// SetStatus sets the "status" field.
func (u *LayawayPlanUpsertBulk) SetStatus(v string) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdateStatus() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateStatus()
	})
}

// SetNotes sets the "notes" field.
func (u *LayawayPlanUpsertBulk) SetNotes(v string) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdateNotes() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *LayawayPlanUpsertBulk) ClearNotes() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.ClearNotes()
	})
}

// SetDueDate sets the "due_date" field.
func (u *LayawayPlanUpsertBulk) SetDueDate(v time.Time) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetDueDate(v)
	})
}

// UpdateDueDate sets the "due_date" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdateDueDate() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateDueDate()
	})
}

// ClearDueDate clears the value of the "due_date" field.
func (u *LayawayPlanUpsertBulk) ClearDueDate() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.ClearDueDate()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LayawayPlanUpsertBulk) SetUpdatedAt(v time.Time) *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LayawayPlanUpsertBulk) UpdateUpdatedAt() *LayawayPlanUpsertBulk {
	return u.Update(func(s *LayawayPlanUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LayawayPlanUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LayawayPlanCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LayawayPlanCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LayawayPlanUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
