// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/pos-service/internal/ent/loyaltytransaction"
	"github.com/bengobox/pos-service/internal/ent/predicate"
)

// LoyaltyTransactionDelete is the builder for deleting a LoyaltyTransaction entity.
type LoyaltyTransactionDelete struct {
	config
	hooks    []Hook
	mutation *LoyaltyTransactionMutation
}

// Where appends a list predicates to the LoyaltyTransactionDelete builder.
func (_d *LoyaltyTransactionDelete) Where(ps ...predicate.LoyaltyTransaction) *LoyaltyTransactionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LoyaltyTransactionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LoyaltyTransactionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LoyaltyTransactionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(loyaltytransaction.Table, sqlgraph.NewFieldSpec(loyaltytransaction.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LoyaltyTransactionDeleteOne is the builder for deleting a single LoyaltyTransaction entity.
type LoyaltyTransactionDeleteOne struct {
	_d *LoyaltyTransactionDelete
}

// Where appends a list predicates to the LoyaltyTransactionDelete builder.
func (_d *LoyaltyTransactionDeleteOne) Where(ps ...predicate.LoyaltyTransaction) *LoyaltyTransactionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LoyaltyTransactionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{loyaltytransaction.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LoyaltyTransactionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
