// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/poscatalogoverride"
	"github.com/google/uuid"
)

// POSCatalogOverride is the model entity for the POSCatalogOverride schema.
type POSCatalogOverride struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// null = applies to all outlets for this tenant
	OutletID *uuid.UUID `json:"outlet_id,omitempty"`
	// SKU from inventory-api — join key
	InventorySku string `json:"inventory_sku,omitempty"`
	// POS retail price override; nil = use inventory-api tier price
	SellingPrice *float64 `json:"selling_price,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency string `json:"currency,omitempty"`
	// taxable, tax_exempt, zero_rated
	TaxStatus string `json:"tax_status,omitempty"`
	// Treasury TaxCode.code (e.g. VAT-16) — used for computing tax at sale time
	TaxCodeID string `json:"tax_code_id,omitempty"`
	// True when selling_price already includes the tax amount (VAT-inclusive pricing)
	PriceIncludesTax bool `json:"price_includes_tax,omitempty"`
	// IsAvailable holds the value of the "is_available" field.
	IsAvailable bool `json:"is_available,omitempty"`
	// IsFeatured holds the value of the "is_featured" field.
	IsFeatured bool `json:"is_featured,omitempty"`
	// DisplayOrder holds the value of the "display_order" field.
	DisplayOrder int `json:"display_order,omitempty"`
	// RequiresPrescription holds the value of the "requires_prescription" field.
	RequiresPrescription bool `json:"requires_prescription,omitempty"`
	// IsReturnable holds the value of the "is_returnable" field.
	IsReturnable bool `json:"is_returnable,omitempty"`
	// RequiresAgeVerification holds the value of the "requires_age_verification" field.
	RequiresAgeVerification bool `json:"requires_age_verification,omitempty"`
	// IsControlledSubstance holds the value of the "is_controlled_substance" field.
	IsControlledSubstance bool `json:"is_controlled_substance,omitempty"`
	// MinimumAge holds the value of the "minimum_age" field.
	MinimumAge *int `json:"minimum_age,omitempty"`
	// Service duration for salon/appointment flow
	DurationMinutes *int `json:"duration_minutes,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*POSCatalogOverride) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case poscatalogoverride.FieldOutletID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case poscatalogoverride.FieldMetadata:
			values[i] = new([]byte)
		case poscatalogoverride.FieldPriceIncludesTax, poscatalogoverride.FieldIsAvailable, poscatalogoverride.FieldIsFeatured, poscatalogoverride.FieldRequiresPrescription, poscatalogoverride.FieldIsReturnable, poscatalogoverride.FieldRequiresAgeVerification, poscatalogoverride.FieldIsControlledSubstance:
			values[i] = new(sql.NullBool)
		case poscatalogoverride.FieldSellingPrice:
			values[i] = new(sql.NullFloat64)
		case poscatalogoverride.FieldDisplayOrder, poscatalogoverride.FieldMinimumAge, poscatalogoverride.FieldDurationMinutes:
			values[i] = new(sql.NullInt64)
		case poscatalogoverride.FieldInventorySku, poscatalogoverride.FieldCurrency, poscatalogoverride.FieldTaxStatus, poscatalogoverride.FieldTaxCodeID:
			values[i] = new(sql.NullString)
		case poscatalogoverride.FieldCreatedAt, poscatalogoverride.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case poscatalogoverride.FieldID, poscatalogoverride.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the POSCatalogOverride fields.
func (_m *POSCatalogOverride) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case poscatalogoverride.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case poscatalogoverride.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case poscatalogoverride.FieldOutletID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field outlet_id", values[i])
			} else if value.Valid {
				_m.OutletID = new(uuid.UUID)
				*_m.OutletID = *value.S.(*uuid.UUID)
			}
		case poscatalogoverride.FieldInventorySku:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field inventory_sku", values[i])
			} else if value.Valid {
				_m.InventorySku = value.String
			}
		case poscatalogoverride.FieldSellingPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field selling_price", values[i])
			} else if value.Valid {
				_m.SellingPrice = new(float64)
				*_m.SellingPrice = value.Float64
			}
		case poscatalogoverride.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		case poscatalogoverride.FieldTaxStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_status", values[i])
			} else if value.Valid {
				_m.TaxStatus = value.String
			}
		case poscatalogoverride.FieldTaxCodeID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tax_code_id", values[i])
			} else if value.Valid {
				_m.TaxCodeID = value.String
			}
		case poscatalogoverride.FieldPriceIncludesTax:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field price_includes_tax", values[i])
			} else if value.Valid {
				_m.PriceIncludesTax = value.Bool
			}
		case poscatalogoverride.FieldIsAvailable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_available", values[i])
			} else if value.Valid {
				_m.IsAvailable = value.Bool
			}
		case poscatalogoverride.FieldIsFeatured:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_featured", values[i])
			} else if value.Valid {
				_m.IsFeatured = value.Bool
			}
		case poscatalogoverride.FieldDisplayOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field display_order", values[i])
			} else if value.Valid {
				_m.DisplayOrder = int(value.Int64)
			}
		case poscatalogoverride.FieldRequiresPrescription:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field requires_prescription", values[i])
			} else if value.Valid {
				_m.RequiresPrescription = value.Bool
			}
		case poscatalogoverride.FieldIsReturnable:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_returnable", values[i])
			} else if value.Valid {
				_m.IsReturnable = value.Bool
			}
		case poscatalogoverride.FieldRequiresAgeVerification:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field requires_age_verification", values[i])
			} else if value.Valid {
				_m.RequiresAgeVerification = value.Bool
			}
		case poscatalogoverride.FieldIsControlledSubstance:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_controlled_substance", values[i])
			} else if value.Valid {
				_m.IsControlledSubstance = value.Bool
			}
		case poscatalogoverride.FieldMinimumAge:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field minimum_age", values[i])
			} else if value.Valid {
				_m.MinimumAge = new(int)
				*_m.MinimumAge = int(value.Int64)
			}
		case poscatalogoverride.FieldDurationMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration_minutes", values[i])
			} else if value.Valid {
				_m.DurationMinutes = new(int)
				*_m.DurationMinutes = int(value.Int64)
			}
		case poscatalogoverride.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case poscatalogoverride.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case poscatalogoverride.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the POSCatalogOverride.
// This includes values selected through modifiers, order, etc.
func (_m *POSCatalogOverride) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this POSCatalogOverride.
// Note that you need to call POSCatalogOverride.Unwrap() before calling this method if this POSCatalogOverride
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *POSCatalogOverride) Update() *POSCatalogOverrideUpdateOne {
	return NewPOSCatalogOverrideClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the POSCatalogOverride entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *POSCatalogOverride) Unwrap() *POSCatalogOverride {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: POSCatalogOverride is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *POSCatalogOverride) String() string {
	var builder strings.Builder
	builder.WriteString("POSCatalogOverride(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	if v := _m.OutletID; v != nil {
		builder.WriteString("outlet_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("inventory_sku=")
	builder.WriteString(_m.InventorySku)
	builder.WriteString(", ")
	if v := _m.SellingPrice; v != nil {
		builder.WriteString("selling_price=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteString(", ")
	builder.WriteString("tax_status=")
	builder.WriteString(_m.TaxStatus)
	builder.WriteString(", ")
	builder.WriteString("tax_code_id=")
	builder.WriteString(_m.TaxCodeID)
	builder.WriteString(", ")
	builder.WriteString("price_includes_tax=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceIncludesTax))
	builder.WriteString(", ")
	builder.WriteString("is_available=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsAvailable))
	builder.WriteString(", ")
	builder.WriteString("is_featured=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsFeatured))
	builder.WriteString(", ")
	builder.WriteString("display_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.DisplayOrder))
	builder.WriteString(", ")
	builder.WriteString("requires_prescription=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequiresPrescription))
	builder.WriteString(", ")
	builder.WriteString("is_returnable=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsReturnable))
	builder.WriteString(", ")
	builder.WriteString("requires_age_verification=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequiresAgeVerification))
	builder.WriteString(", ")
	builder.WriteString("is_controlled_substance=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsControlledSubstance))
	builder.WriteString(", ")
	if v := _m.MinimumAge; v != nil {
		builder.WriteString("minimum_age=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DurationMinutes; v != nil {
		builder.WriteString("duration_minutes=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// POSCatalogOverrides is a parsable slice of POSCatalogOverride.
type POSCatalogOverrides []*POSCatalogOverride
