// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/pos-service/internal/ent/posreturnline"
	"github.com/bengobox/pos-service/internal/ent/predicate"
)

// POSReturnLineDelete is the builder for deleting a POSReturnLine entity.
type POSReturnLineDelete struct {
	config
	hooks    []Hook
	mutation *POSReturnLineMutation
}

// Where appends a list predicates to the POSReturnLineDelete builder.
func (_d *POSReturnLineDelete) Where(ps ...predicate.POSReturnLine) *POSReturnLineDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *POSReturnLineDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *POSReturnLineDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *POSReturnLineDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(posreturnline.Table, sqlgraph.NewFieldSpec(posreturnline.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// POSReturnLineDeleteOne is the builder for deleting a single POSReturnLine entity.
type POSReturnLineDeleteOne struct {
	_d *POSReturnLineDelete
}

// Where appends a list predicates to the POSReturnLineDelete builder.
func (_d *POSReturnLineDeleteOne) Where(ps ...predicate.POSReturnLine) *POSReturnLineDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *POSReturnLineDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{posreturnline.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *POSReturnLineDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
