// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/prescription"
	"github.com/google/uuid"
)

// Prescription is the model entity for the Prescription schema.
type Prescription struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// OutletID holds the value of the "outlet_id" field.
	OutletID uuid.UUID `json:"outlet_id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID *uuid.UUID `json:"order_id,omitempty"`
	// PrescriptionNumber holds the value of the "prescription_number" field.
	PrescriptionNumber string `json:"prescription_number,omitempty"`
	// PrescriberName holds the value of the "prescriber_name" field.
	PrescriberName string `json:"prescriber_name,omitempty"`
	// PrescriberLicense holds the value of the "prescriber_license" field.
	PrescriberLicense string `json:"prescriber_license,omitempty"`
	// PatientName holds the value of the "patient_name" field.
	PatientName string `json:"patient_name,omitempty"`
	// PatientDob holds the value of the "patient_dob" field.
	PatientDob string `json:"patient_dob,omitempty"`
	// PatientIDNumber holds the value of the "patient_id_number" field.
	PatientIDNumber string `json:"patient_id_number,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// DispensedAt holds the value of the "dispensed_at" field.
	DispensedAt *time.Time `json:"dispensed_at,omitempty"`
	// DispensedBy holds the value of the "dispensed_by" field.
	DispensedBy *uuid.UUID `json:"dispensed_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Prescription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case prescription.FieldOrderID, prescription.FieldDispensedBy:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case prescription.FieldPrescriptionNumber, prescription.FieldPrescriberName, prescription.FieldPrescriberLicense, prescription.FieldPatientName, prescription.FieldPatientDob, prescription.FieldPatientIDNumber, prescription.FieldStatus, prescription.FieldNotes:
			values[i] = new(sql.NullString)
		case prescription.FieldDispensedAt, prescription.FieldCreatedAt, prescription.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case prescription.FieldID, prescription.FieldTenantID, prescription.FieldOutletID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Prescription fields.
func (_m *Prescription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case prescription.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case prescription.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case prescription.FieldOutletID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field outlet_id", values[i])
			} else if value != nil {
				_m.OutletID = *value
			}
		case prescription.FieldOrderID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = new(uuid.UUID)
				*_m.OrderID = *value.S.(*uuid.UUID)
			}
		case prescription.FieldPrescriptionNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prescription_number", values[i])
			} else if value.Valid {
				_m.PrescriptionNumber = value.String
			}
		case prescription.FieldPrescriberName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prescriber_name", values[i])
			} else if value.Valid {
				_m.PrescriberName = value.String
			}
		case prescription.FieldPrescriberLicense:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field prescriber_license", values[i])
			} else if value.Valid {
				_m.PrescriberLicense = value.String
			}
		case prescription.FieldPatientName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field patient_name", values[i])
			} else if value.Valid {
				_m.PatientName = value.String
			}
		case prescription.FieldPatientDob:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field patient_dob", values[i])
			} else if value.Valid {
				_m.PatientDob = value.String
			}
		case prescription.FieldPatientIDNumber:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field patient_id_number", values[i])
			} else if value.Valid {
				_m.PatientIDNumber = value.String
			}
		case prescription.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case prescription.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case prescription.FieldDispensedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field dispensed_at", values[i])
			} else if value.Valid {
				_m.DispensedAt = new(time.Time)
				*_m.DispensedAt = value.Time
			}
		case prescription.FieldDispensedBy:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field dispensed_by", values[i])
			} else if value.Valid {
				_m.DispensedBy = new(uuid.UUID)
				*_m.DispensedBy = *value.S.(*uuid.UUID)
			}
		case prescription.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case prescription.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Prescription.
// This includes values selected through modifiers, order, etc.
func (_m *Prescription) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Prescription.
// Note that you need to call Prescription.Unwrap() before calling this method if this Prescription
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Prescription) Update() *PrescriptionUpdateOne {
	return NewPrescriptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Prescription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Prescription) Unwrap() *Prescription {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Prescription is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Prescription) String() string {
	var builder strings.Builder
	builder.WriteString("Prescription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("outlet_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutletID))
	builder.WriteString(", ")
	if v := _m.OrderID; v != nil {
		builder.WriteString("order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("prescription_number=")
	builder.WriteString(_m.PrescriptionNumber)
	builder.WriteString(", ")
	builder.WriteString("prescriber_name=")
	builder.WriteString(_m.PrescriberName)
	builder.WriteString(", ")
	builder.WriteString("prescriber_license=")
	builder.WriteString(_m.PrescriberLicense)
	builder.WriteString(", ")
	builder.WriteString("patient_name=")
	builder.WriteString(_m.PatientName)
	builder.WriteString(", ")
	builder.WriteString("patient_dob=")
	builder.WriteString(_m.PatientDob)
	builder.WriteString(", ")
	builder.WriteString("patient_id_number=")
	builder.WriteString(_m.PatientIDNumber)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	if v := _m.DispensedAt; v != nil {
		builder.WriteString("dispensed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DispensedBy; v != nil {
		builder.WriteString("dispensed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Prescriptions is a parsable slice of Prescription.
type Prescriptions []*Prescription
