// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/pos-service/internal/ent/room"
	"github.com/bengobox/pos-service/internal/ent/roomfolioitem"
	"github.com/bengobox/pos-service/internal/ent/roomguest"
	"github.com/google/uuid"
)

// RoomGuestCreate is the builder for creating a RoomGuest entity.
type RoomGuestCreate struct {
	config
	mutation *RoomGuestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *RoomGuestCreate) SetTenantID(v uuid.UUID) *RoomGuestCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetRoomID sets the "room_id" field.
func (_c *RoomGuestCreate) SetRoomID(v uuid.UUID) *RoomGuestCreate {
	_c.mutation.SetRoomID(v)
	return _c
}

// SetGuestName sets the "guest_name" field.
func (_c *RoomGuestCreate) SetGuestName(v string) *RoomGuestCreate {
	_c.mutation.SetGuestName(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *RoomGuestCreate) SetPhone(v string) *RoomGuestCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetIDNumber sets the "id_number" field.
func (_c *RoomGuestCreate) SetIDNumber(v string) *RoomGuestCreate {
	_c.mutation.SetIDNumber(v)
	return _c
}

// SetCheckInDate sets the "check_in_date" field.
func (_c *RoomGuestCreate) SetCheckInDate(v time.Time) *RoomGuestCreate {
	_c.mutation.SetCheckInDate(v)
	return _c
}

// SetNights sets the "nights" field.
func (_c *RoomGuestCreate) SetNights(v int) *RoomGuestCreate {
	_c.mutation.SetNights(v)
	return _c
}

// SetCheckOutDate sets the "check_out_date" field.
func (_c *RoomGuestCreate) SetCheckOutDate(v time.Time) *RoomGuestCreate {
	_c.mutation.SetCheckOutDate(v)
	return _c
}

// SetTotalRoomCharge sets the "total_room_charge" field.
func (_c *RoomGuestCreate) SetTotalRoomCharge(v float64) *RoomGuestCreate {
	_c.mutation.SetTotalRoomCharge(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *RoomGuestCreate) SetStatus(v roomguest.Status) *RoomGuestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *RoomGuestCreate) SetNillableStatus(v *roomguest.Status) *RoomGuestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCheckedInBy sets the "checked_in_by" field.
func (_c *RoomGuestCreate) SetCheckedInBy(v uuid.UUID) *RoomGuestCreate {
	_c.mutation.SetCheckedInBy(v)
	return _c
}

// SetCheckedOutBy sets the "checked_out_by" field.
func (_c *RoomGuestCreate) SetCheckedOutBy(v uuid.UUID) *RoomGuestCreate {
	_c.mutation.SetCheckedOutBy(v)
	return _c
}

// SetNillableCheckedOutBy sets the "checked_out_by" field if the given value is not nil.
func (_c *RoomGuestCreate) SetNillableCheckedOutBy(v *uuid.UUID) *RoomGuestCreate {
	if v != nil {
		_c.SetCheckedOutBy(*v)
	}
	return _c
}

// SetCheckedInAt sets the "checked_in_at" field.
func (_c *RoomGuestCreate) SetCheckedInAt(v time.Time) *RoomGuestCreate {
	_c.mutation.SetCheckedInAt(v)
	return _c
}

// SetNillableCheckedInAt sets the "checked_in_at" field if the given value is not nil.
func (_c *RoomGuestCreate) SetNillableCheckedInAt(v *time.Time) *RoomGuestCreate {
	if v != nil {
		_c.SetCheckedInAt(*v)
	}
	return _c
}

// SetCheckedOutAt sets the "checked_out_at" field.
func (_c *RoomGuestCreate) SetCheckedOutAt(v time.Time) *RoomGuestCreate {
	_c.mutation.SetCheckedOutAt(v)
	return _c
}

// SetNillableCheckedOutAt sets the "checked_out_at" field if the given value is not nil.
func (_c *RoomGuestCreate) SetNillableCheckedOutAt(v *time.Time) *RoomGuestCreate {
	if v != nil {
		_c.SetCheckedOutAt(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *RoomGuestCreate) SetMetadata(v map[string]interface{}) *RoomGuestCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RoomGuestCreate) SetCreatedAt(v time.Time) *RoomGuestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RoomGuestCreate) SetNillableCreatedAt(v *time.Time) *RoomGuestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RoomGuestCreate) SetUpdatedAt(v time.Time) *RoomGuestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RoomGuestCreate) SetNillableUpdatedAt(v *time.Time) *RoomGuestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RoomGuestCreate) SetID(v uuid.UUID) *RoomGuestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RoomGuestCreate) SetNillableID(v *uuid.UUID) *RoomGuestCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRoom sets the "room" edge to the Room entity.
func (_c *RoomGuestCreate) SetRoom(v *Room) *RoomGuestCreate {
	return _c.SetRoomID(v.ID)
}

// AddFolioItemIDs adds the "folio_items" edge to the RoomFolioItem entity by IDs.
func (_c *RoomGuestCreate) AddFolioItemIDs(ids ...uuid.UUID) *RoomGuestCreate {
	_c.mutation.AddFolioItemIDs(ids...)
	return _c
}

// AddFolioItems adds the "folio_items" edges to the RoomFolioItem entity.
func (_c *RoomGuestCreate) AddFolioItems(v ...*RoomFolioItem) *RoomGuestCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddFolioItemIDs(ids...)
}

// Mutation returns the RoomGuestMutation object of the builder.
func (_c *RoomGuestCreate) Mutation() *RoomGuestMutation {
	return _c.mutation
}

// Save creates the RoomGuest in the database.
func (_c *RoomGuestCreate) Save(ctx context.Context) (*RoomGuest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoomGuestCreate) SaveX(ctx context.Context) *RoomGuest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoomGuestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoomGuestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RoomGuestCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := roomguest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CheckedInAt(); !ok {
		v := roomguest.DefaultCheckedInAt()
		_c.mutation.SetCheckedInAt(v)
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		v := roomguest.DefaultMetadata
		_c.mutation.SetMetadata(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := roomguest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := roomguest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := roomguest.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoomGuestCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "RoomGuest.tenant_id"`)}
	}
	if _, ok := _c.mutation.RoomID(); !ok {
		return &ValidationError{Name: "room_id", err: errors.New(`ent: missing required field "RoomGuest.room_id"`)}
	}
	if _, ok := _c.mutation.GuestName(); !ok {
		return &ValidationError{Name: "guest_name", err: errors.New(`ent: missing required field "RoomGuest.guest_name"`)}
	}
	if v, ok := _c.mutation.GuestName(); ok {
		if err := roomguest.GuestNameValidator(v); err != nil {
			return &ValidationError{Name: "guest_name", err: fmt.Errorf(`ent: validator failed for field "RoomGuest.guest_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "RoomGuest.phone"`)}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := roomguest.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "RoomGuest.phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IDNumber(); !ok {
		return &ValidationError{Name: "id_number", err: errors.New(`ent: missing required field "RoomGuest.id_number"`)}
	}
	if v, ok := _c.mutation.IDNumber(); ok {
		if err := roomguest.IDNumberValidator(v); err != nil {
			return &ValidationError{Name: "id_number", err: fmt.Errorf(`ent: validator failed for field "RoomGuest.id_number": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CheckInDate(); !ok {
		return &ValidationError{Name: "check_in_date", err: errors.New(`ent: missing required field "RoomGuest.check_in_date"`)}
	}
	if _, ok := _c.mutation.Nights(); !ok {
		return &ValidationError{Name: "nights", err: errors.New(`ent: missing required field "RoomGuest.nights"`)}
	}
	if v, ok := _c.mutation.Nights(); ok {
		if err := roomguest.NightsValidator(v); err != nil {
			return &ValidationError{Name: "nights", err: fmt.Errorf(`ent: validator failed for field "RoomGuest.nights": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CheckOutDate(); !ok {
		return &ValidationError{Name: "check_out_date", err: errors.New(`ent: missing required field "RoomGuest.check_out_date"`)}
	}
	if _, ok := _c.mutation.TotalRoomCharge(); !ok {
		return &ValidationError{Name: "total_room_charge", err: errors.New(`ent: missing required field "RoomGuest.total_room_charge"`)}
	}
	if v, ok := _c.mutation.TotalRoomCharge(); ok {
		if err := roomguest.TotalRoomChargeValidator(v); err != nil {
			return &ValidationError{Name: "total_room_charge", err: fmt.Errorf(`ent: validator failed for field "RoomGuest.total_room_charge": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "RoomGuest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := roomguest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "RoomGuest.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CheckedInBy(); !ok {
		return &ValidationError{Name: "checked_in_by", err: errors.New(`ent: missing required field "RoomGuest.checked_in_by"`)}
	}
	if _, ok := _c.mutation.CheckedInAt(); !ok {
		return &ValidationError{Name: "checked_in_at", err: errors.New(`ent: missing required field "RoomGuest.checked_in_at"`)}
	}
	if _, ok := _c.mutation.Metadata(); !ok {
		return &ValidationError{Name: "metadata", err: errors.New(`ent: missing required field "RoomGuest.metadata"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RoomGuest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RoomGuest.updated_at"`)}
	}
	if len(_c.mutation.RoomIDs()) == 0 {
		return &ValidationError{Name: "room", err: errors.New(`ent: missing required edge "RoomGuest.room"`)}
	}
	return nil
}

func (_c *RoomGuestCreate) sqlSave(ctx context.Context) (*RoomGuest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoomGuestCreate) createSpec() (*RoomGuest, *sqlgraph.CreateSpec) {
	var (
		_node = &RoomGuest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(roomguest.Table, sqlgraph.NewFieldSpec(roomguest.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(roomguest.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.GuestName(); ok {
		_spec.SetField(roomguest.FieldGuestName, field.TypeString, value)
		_node.GuestName = value
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(roomguest.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.IDNumber(); ok {
		_spec.SetField(roomguest.FieldIDNumber, field.TypeString, value)
		_node.IDNumber = value
	}
	if value, ok := _c.mutation.CheckInDate(); ok {
		_spec.SetField(roomguest.FieldCheckInDate, field.TypeTime, value)
		_node.CheckInDate = value
	}
	if value, ok := _c.mutation.Nights(); ok {
		_spec.SetField(roomguest.FieldNights, field.TypeInt, value)
		_node.Nights = value
	}
	if value, ok := _c.mutation.CheckOutDate(); ok {
		_spec.SetField(roomguest.FieldCheckOutDate, field.TypeTime, value)
		_node.CheckOutDate = value
	}
	if value, ok := _c.mutation.TotalRoomCharge(); ok {
		_spec.SetField(roomguest.FieldTotalRoomCharge, field.TypeFloat64, value)
		_node.TotalRoomCharge = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(roomguest.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CheckedInBy(); ok {
		_spec.SetField(roomguest.FieldCheckedInBy, field.TypeUUID, value)
		_node.CheckedInBy = value
	}
	if value, ok := _c.mutation.CheckedOutBy(); ok {
		_spec.SetField(roomguest.FieldCheckedOutBy, field.TypeUUID, value)
		_node.CheckedOutBy = &value
	}
	if value, ok := _c.mutation.CheckedInAt(); ok {
		_spec.SetField(roomguest.FieldCheckedInAt, field.TypeTime, value)
		_node.CheckedInAt = value
	}
	if value, ok := _c.mutation.CheckedOutAt(); ok {
		_spec.SetField(roomguest.FieldCheckedOutAt, field.TypeTime, value)
		_node.CheckedOutAt = &value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(roomguest.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(roomguest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(roomguest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roomguest.RoomTable,
			Columns: []string{roomguest.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoomID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.FolioItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomguest.FolioItemsTable,
			Columns: []string{roomguest.FolioItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roomfolioitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RoomGuest.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RoomGuestUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *RoomGuestCreate) OnConflict(opts ...sql.ConflictOption) *RoomGuestUpsertOne {
	_c.conflict = opts
	return &RoomGuestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RoomGuest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RoomGuestCreate) OnConflictColumns(columns ...string) *RoomGuestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RoomGuestUpsertOne{
		create: _c,
	}
}

type (
	// RoomGuestUpsertOne is the builder for "upsert"-ing
	//  one RoomGuest node.
	RoomGuestUpsertOne struct {
		create *RoomGuestCreate
	}

	// RoomGuestUpsert is the "OnConflict" setter.
	RoomGuestUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *RoomGuestUpsert) SetTenantID(v uuid.UUID) *RoomGuestUpsert {
	u.Set(roomguest.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateTenantID() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldTenantID)
	return u
}

// SetRoomID sets the "room_id" field.
func (u *RoomGuestUpsert) SetRoomID(v uuid.UUID) *RoomGuestUpsert {
	u.Set(roomguest.FieldRoomID, v)
	return u
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateRoomID() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldRoomID)
	return u
}

// SetGuestName sets the "guest_name" field.
func (u *RoomGuestUpsert) SetGuestName(v string) *RoomGuestUpsert {
	u.Set(roomguest.FieldGuestName, v)
	return u
}

// UpdateGuestName sets the "guest_name" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateGuestName() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldGuestName)
	return u
}

// SetPhone sets the "phone" field.
func (u *RoomGuestUpsert) SetPhone(v string) *RoomGuestUpsert {
	u.Set(roomguest.FieldPhone, v)
	return u
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdatePhone() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldPhone)
	return u
}

// SetIDNumber sets the "id_number" field.
func (u *RoomGuestUpsert) SetIDNumber(v string) *RoomGuestUpsert {
	u.Set(roomguest.FieldIDNumber, v)
	return u
}

// UpdateIDNumber sets the "id_number" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateIDNumber() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldIDNumber)
	return u
}

// SetCheckInDate sets the "check_in_date" field.
func (u *RoomGuestUpsert) SetCheckInDate(v time.Time) *RoomGuestUpsert {
	u.Set(roomguest.FieldCheckInDate, v)
	return u
}

// UpdateCheckInDate sets the "check_in_date" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateCheckInDate() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldCheckInDate)
	return u
}

// SetNights sets the "nights" field.
func (u *RoomGuestUpsert) SetNights(v int) *RoomGuestUpsert {
	u.Set(roomguest.FieldNights, v)
	return u
}

// UpdateNights sets the "nights" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateNights() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldNights)
	return u
}

// AddNights adds v to the "nights" field.
func (u *RoomGuestUpsert) AddNights(v int) *RoomGuestUpsert {
	u.Add(roomguest.FieldNights, v)
	return u
}

// SetCheckOutDate sets the "check_out_date" field.
func (u *RoomGuestUpsert) SetCheckOutDate(v time.Time) *RoomGuestUpsert {
	u.Set(roomguest.FieldCheckOutDate, v)
	return u
}

// UpdateCheckOutDate sets the "check_out_date" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateCheckOutDate() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldCheckOutDate)
	return u
}

// SetTotalRoomCharge sets the "total_room_charge" field.
func (u *RoomGuestUpsert) SetTotalRoomCharge(v float64) *RoomGuestUpsert {
	u.Set(roomguest.FieldTotalRoomCharge, v)
	return u
}

// UpdateTotalRoomCharge sets the "total_room_charge" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateTotalRoomCharge() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldTotalRoomCharge)
	return u
}

// AddTotalRoomCharge adds v to the "total_room_charge" field.
func (u *RoomGuestUpsert) AddTotalRoomCharge(v float64) *RoomGuestUpsert {
	u.Add(roomguest.FieldTotalRoomCharge, v)
	return u
}

// SetStatus sets the "status" field.
func (u *RoomGuestUpsert) SetStatus(v roomguest.Status) *RoomGuestUpsert {
	u.Set(roomguest.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateStatus() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldStatus)
	return u
}

// SetCheckedInBy sets the "checked_in_by" field.
func (u *RoomGuestUpsert) SetCheckedInBy(v uuid.UUID) *RoomGuestUpsert {
	u.Set(roomguest.FieldCheckedInBy, v)
	return u
}

// UpdateCheckedInBy sets the "checked_in_by" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateCheckedInBy() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldCheckedInBy)
	return u
}

// SetCheckedOutBy sets the "checked_out_by" field.
func (u *RoomGuestUpsert) SetCheckedOutBy(v uuid.UUID) *RoomGuestUpsert {
	u.Set(roomguest.FieldCheckedOutBy, v)
	return u
}

// UpdateCheckedOutBy sets the "checked_out_by" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateCheckedOutBy() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldCheckedOutBy)
	return u
}

// ClearCheckedOutBy clears the value of the "checked_out_by" field.
func (u *RoomGuestUpsert) ClearCheckedOutBy() *RoomGuestUpsert {
	u.SetNull(roomguest.FieldCheckedOutBy)
	return u
}

// SetCheckedInAt sets the "checked_in_at" field.
func (u *RoomGuestUpsert) SetCheckedInAt(v time.Time) *RoomGuestUpsert {
	u.Set(roomguest.FieldCheckedInAt, v)
	return u
}

// UpdateCheckedInAt sets the "checked_in_at" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateCheckedInAt() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldCheckedInAt)
	return u
}

// SetCheckedOutAt sets the "checked_out_at" field.
func (u *RoomGuestUpsert) SetCheckedOutAt(v time.Time) *RoomGuestUpsert {
	u.Set(roomguest.FieldCheckedOutAt, v)
	return u
}

// UpdateCheckedOutAt sets the "checked_out_at" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateCheckedOutAt() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldCheckedOutAt)
	return u
}

// ClearCheckedOutAt clears the value of the "checked_out_at" field.
func (u *RoomGuestUpsert) ClearCheckedOutAt() *RoomGuestUpsert {
	u.SetNull(roomguest.FieldCheckedOutAt)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *RoomGuestUpsert) SetMetadata(v map[string]interface{}) *RoomGuestUpsert {
	u.Set(roomguest.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateMetadata() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldMetadata)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RoomGuestUpsert) SetUpdatedAt(v time.Time) *RoomGuestUpsert {
	u.Set(roomguest.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RoomGuestUpsert) UpdateUpdatedAt() *RoomGuestUpsert {
	u.SetExcluded(roomguest.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RoomGuest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(roomguest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RoomGuestUpsertOne) UpdateNewValues() *RoomGuestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(roomguest.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(roomguest.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RoomGuest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RoomGuestUpsertOne) Ignore() *RoomGuestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RoomGuestUpsertOne) DoNothing() *RoomGuestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RoomGuestCreate.OnConflict
// documentation for more info.
func (u *RoomGuestUpsertOne) Update(set func(*RoomGuestUpsert)) *RoomGuestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RoomGuestUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *RoomGuestUpsertOne) SetTenantID(v uuid.UUID) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateTenantID() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateTenantID()
	})
}

// SetRoomID sets the "room_id" field.
func (u *RoomGuestUpsertOne) SetRoomID(v uuid.UUID) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateRoomID() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateRoomID()
	})
}

// SetGuestName sets the "guest_name" field.
func (u *RoomGuestUpsertOne) SetGuestName(v string) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetGuestName(v)
	})
}

// UpdateGuestName sets the "guest_name" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateGuestName() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateGuestName()
	})
}

// SetPhone sets the "phone" field.
func (u *RoomGuestUpsertOne) SetPhone(v string) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdatePhone() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdatePhone()
	})
}

// SetIDNumber sets the "id_number" field.
func (u *RoomGuestUpsertOne) SetIDNumber(v string) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetIDNumber(v)
	})
}

// UpdateIDNumber sets the "id_number" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateIDNumber() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateIDNumber()
	})
}

// SetCheckInDate sets the "check_in_date" field.
func (u *RoomGuestUpsertOne) SetCheckInDate(v time.Time) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetCheckInDate(v)
	})
}

// UpdateCheckInDate sets the "check_in_date" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateCheckInDate() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateCheckInDate()
	})
}

// SetNights sets the "nights" field.
func (u *RoomGuestUpsertOne) SetNights(v int) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetNights(v)
	})
}

// AddNights adds v to the "nights" field.
func (u *RoomGuestUpsertOne) AddNights(v int) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.AddNights(v)
	})
}

// UpdateNights sets the "nights" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateNights() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateNights()
	})
}

// SetCheckOutDate sets the "check_out_date" field.
func (u *RoomGuestUpsertOne) SetCheckOutDate(v time.Time) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetCheckOutDate(v)
	})
}

// UpdateCheckOutDate sets the "check_out_date" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateCheckOutDate() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateCheckOutDate()
	})
}

// SetTotalRoomCharge sets the "total_room_charge" field.
func (u *RoomGuestUpsertOne) SetTotalRoomCharge(v float64) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetTotalRoomCharge(v)
	})
}

// AddTotalRoomCharge adds v to the "total_room_charge" field.
func (u *RoomGuestUpsertOne) AddTotalRoomCharge(v float64) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.AddTotalRoomCharge(v)
	})
}

// UpdateTotalRoomCharge sets the "total_room_charge" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateTotalRoomCharge() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateTotalRoomCharge()
	})
}

// SetStatus sets the "status" field.
func (u *RoomGuestUpsertOne) SetStatus(v roomguest.Status) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateStatus() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateStatus()
	})
}

// SetCheckedInBy sets the "checked_in_by" field.
func (u *RoomGuestUpsertOne) SetCheckedInBy(v uuid.UUID) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetCheckedInBy(v)
	})
}

// UpdateCheckedInBy sets the "checked_in_by" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateCheckedInBy() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateCheckedInBy()
	})
}

// SetCheckedOutBy sets the "checked_out_by" field.
func (u *RoomGuestUpsertOne) SetCheckedOutBy(v uuid.UUID) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetCheckedOutBy(v)
	})
}

// UpdateCheckedOutBy sets the "checked_out_by" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateCheckedOutBy() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateCheckedOutBy()
	})
}

// ClearCheckedOutBy clears the value of the "checked_out_by" field.
func (u *RoomGuestUpsertOne) ClearCheckedOutBy() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.ClearCheckedOutBy()
	})
}

// SetCheckedInAt sets the "checked_in_at" field.
func (u *RoomGuestUpsertOne) SetCheckedInAt(v time.Time) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetCheckedInAt(v)
	})
}

// UpdateCheckedInAt sets the "checked_in_at" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateCheckedInAt() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateCheckedInAt()
	})
}

// SetCheckedOutAt sets the "checked_out_at" field.
func (u *RoomGuestUpsertOne) SetCheckedOutAt(v time.Time) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetCheckedOutAt(v)
	})
}

// UpdateCheckedOutAt sets the "checked_out_at" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateCheckedOutAt() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateCheckedOutAt()
	})
}

// ClearCheckedOutAt clears the value of the "checked_out_at" field.
func (u *RoomGuestUpsertOne) ClearCheckedOutAt() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.ClearCheckedOutAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *RoomGuestUpsertOne) SetMetadata(v map[string]interface{}) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateMetadata() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RoomGuestUpsertOne) SetUpdatedAt(v time.Time) *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RoomGuestUpsertOne) UpdateUpdatedAt() *RoomGuestUpsertOne {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RoomGuestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RoomGuestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RoomGuestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RoomGuestUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RoomGuestUpsertOne.ID is not supported by MySQL driver. Use RoomGuestUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RoomGuestUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RoomGuestCreateBulk is the builder for creating many RoomGuest entities in bulk.
type RoomGuestCreateBulk struct {
	config
	err      error
	builders []*RoomGuestCreate
	conflict []sql.ConflictOption
}

// Save creates the RoomGuest entities in the database.
func (_c *RoomGuestCreateBulk) Save(ctx context.Context) ([]*RoomGuest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RoomGuest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoomGuestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoomGuestCreateBulk) SaveX(ctx context.Context) []*RoomGuest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoomGuestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoomGuestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RoomGuest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RoomGuestUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *RoomGuestCreateBulk) OnConflict(opts ...sql.ConflictOption) *RoomGuestUpsertBulk {
	_c.conflict = opts
	return &RoomGuestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RoomGuest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RoomGuestCreateBulk) OnConflictColumns(columns ...string) *RoomGuestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RoomGuestUpsertBulk{
		create: _c,
	}
}

// RoomGuestUpsertBulk is the builder for "upsert"-ing
// a bulk of RoomGuest nodes.
type RoomGuestUpsertBulk struct {
	create *RoomGuestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RoomGuest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(roomguest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RoomGuestUpsertBulk) UpdateNewValues() *RoomGuestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(roomguest.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(roomguest.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RoomGuest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RoomGuestUpsertBulk) Ignore() *RoomGuestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RoomGuestUpsertBulk) DoNothing() *RoomGuestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RoomGuestCreateBulk.OnConflict
// documentation for more info.
func (u *RoomGuestUpsertBulk) Update(set func(*RoomGuestUpsert)) *RoomGuestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RoomGuestUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *RoomGuestUpsertBulk) SetTenantID(v uuid.UUID) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateTenantID() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateTenantID()
	})
}

// SetRoomID sets the "room_id" field.
func (u *RoomGuestUpsertBulk) SetRoomID(v uuid.UUID) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateRoomID() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateRoomID()
	})
}

// SetGuestName sets the "guest_name" field.
func (u *RoomGuestUpsertBulk) SetGuestName(v string) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetGuestName(v)
	})
}

// UpdateGuestName sets the "guest_name" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateGuestName() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateGuestName()
	})
}

// SetPhone sets the "phone" field.
func (u *RoomGuestUpsertBulk) SetPhone(v string) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetPhone(v)
	})
}

// UpdatePhone sets the "phone" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdatePhone() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdatePhone()
	})
}

// SetIDNumber sets the "id_number" field.
func (u *RoomGuestUpsertBulk) SetIDNumber(v string) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetIDNumber(v)
	})
}

// UpdateIDNumber sets the "id_number" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateIDNumber() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateIDNumber()
	})
}

// SetCheckInDate sets the "check_in_date" field.
func (u *RoomGuestUpsertBulk) SetCheckInDate(v time.Time) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetCheckInDate(v)
	})
}

// UpdateCheckInDate sets the "check_in_date" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateCheckInDate() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateCheckInDate()
	})
}

// SetNights sets the "nights" field.
func (u *RoomGuestUpsertBulk) SetNights(v int) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetNights(v)
	})
}

// AddNights adds v to the "nights" field.
func (u *RoomGuestUpsertBulk) AddNights(v int) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.AddNights(v)
	})
}

// UpdateNights sets the "nights" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateNights() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateNights()
	})
}

// SetCheckOutDate sets the "check_out_date" field.
func (u *RoomGuestUpsertBulk) SetCheckOutDate(v time.Time) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetCheckOutDate(v)
	})
}

// UpdateCheckOutDate sets the "check_out_date" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateCheckOutDate() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateCheckOutDate()
	})
}

// SetTotalRoomCharge sets the "total_room_charge" field.
func (u *RoomGuestUpsertBulk) SetTotalRoomCharge(v float64) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetTotalRoomCharge(v)
	})
}

// AddTotalRoomCharge adds v to the "total_room_charge" field.
func (u *RoomGuestUpsertBulk) AddTotalRoomCharge(v float64) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.AddTotalRoomCharge(v)
	})
}

// UpdateTotalRoomCharge sets the "total_room_charge" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateTotalRoomCharge() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateTotalRoomCharge()
	})
}

// SetStatus sets the "status" field.
func (u *RoomGuestUpsertBulk) SetStatus(v roomguest.Status) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateStatus() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateStatus()
	})
}

// SetCheckedInBy sets the "checked_in_by" field.
func (u *RoomGuestUpsertBulk) SetCheckedInBy(v uuid.UUID) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetCheckedInBy(v)
	})
}

// UpdateCheckedInBy sets the "checked_in_by" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateCheckedInBy() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateCheckedInBy()
	})
}

// SetCheckedOutBy sets the "checked_out_by" field.
func (u *RoomGuestUpsertBulk) SetCheckedOutBy(v uuid.UUID) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetCheckedOutBy(v)
	})
}

// UpdateCheckedOutBy sets the "checked_out_by" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateCheckedOutBy() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateCheckedOutBy()
	})
}

// ClearCheckedOutBy clears the value of the "checked_out_by" field.
func (u *RoomGuestUpsertBulk) ClearCheckedOutBy() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.ClearCheckedOutBy()
	})
}

// SetCheckedInAt sets the "checked_in_at" field.
func (u *RoomGuestUpsertBulk) SetCheckedInAt(v time.Time) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetCheckedInAt(v)
	})
}

// UpdateCheckedInAt sets the "checked_in_at" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateCheckedInAt() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateCheckedInAt()
	})
}

// SetCheckedOutAt sets the "checked_out_at" field.
func (u *RoomGuestUpsertBulk) SetCheckedOutAt(v time.Time) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetCheckedOutAt(v)
	})
}

// UpdateCheckedOutAt sets the "checked_out_at" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateCheckedOutAt() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateCheckedOutAt()
	})
}

// ClearCheckedOutAt clears the value of the "checked_out_at" field.
func (u *RoomGuestUpsertBulk) ClearCheckedOutAt() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.ClearCheckedOutAt()
	})
}

// SetMetadata sets the "metadata" field.
func (u *RoomGuestUpsertBulk) SetMetadata(v map[string]interface{}) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateMetadata() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateMetadata()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RoomGuestUpsertBulk) SetUpdatedAt(v time.Time) *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RoomGuestUpsertBulk) UpdateUpdatedAt() *RoomGuestUpsertBulk {
	return u.Update(func(s *RoomGuestUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RoomGuestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RoomGuestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RoomGuestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RoomGuestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
