// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/bengobox/pos-service/internal/ent/room"
	"github.com/bengobox/pos-service/internal/ent/roomamenity"
	"github.com/bengobox/pos-service/internal/ent/roomamenityassignment"
	"github.com/google/uuid"
)

// RoomAmenityAssignmentCreate is the builder for creating a RoomAmenityAssignment entity.
type RoomAmenityAssignmentCreate struct {
	config
	mutation *RoomAmenityAssignmentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (_c *RoomAmenityAssignmentCreate) SetTenantID(v uuid.UUID) *RoomAmenityAssignmentCreate {
	_c.mutation.SetTenantID(v)
	return _c
}

// SetRoomID sets the "room_id" field.
func (_c *RoomAmenityAssignmentCreate) SetRoomID(v uuid.UUID) *RoomAmenityAssignmentCreate {
	_c.mutation.SetRoomID(v)
	return _c
}

// SetAmenityID sets the "amenity_id" field.
func (_c *RoomAmenityAssignmentCreate) SetAmenityID(v uuid.UUID) *RoomAmenityAssignmentCreate {
	_c.mutation.SetAmenityID(v)
	return _c
}

// SetIsIncluded sets the "is_included" field.
func (_c *RoomAmenityAssignmentCreate) SetIsIncluded(v bool) *RoomAmenityAssignmentCreate {
	_c.mutation.SetIsIncluded(v)
	return _c
}

// SetNillableIsIncluded sets the "is_included" field if the given value is not nil.
func (_c *RoomAmenityAssignmentCreate) SetNillableIsIncluded(v *bool) *RoomAmenityAssignmentCreate {
	if v != nil {
		_c.SetIsIncluded(*v)
	}
	return _c
}

// SetNotes sets the "notes" field.
func (_c *RoomAmenityAssignmentCreate) SetNotes(v string) *RoomAmenityAssignmentCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *RoomAmenityAssignmentCreate) SetNillableNotes(v *string) *RoomAmenityAssignmentCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RoomAmenityAssignmentCreate) SetCreatedAt(v time.Time) *RoomAmenityAssignmentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RoomAmenityAssignmentCreate) SetNillableCreatedAt(v *time.Time) *RoomAmenityAssignmentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RoomAmenityAssignmentCreate) SetID(v uuid.UUID) *RoomAmenityAssignmentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *RoomAmenityAssignmentCreate) SetNillableID(v *uuid.UUID) *RoomAmenityAssignmentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetRoom sets the "room" edge to the Room entity.
func (_c *RoomAmenityAssignmentCreate) SetRoom(v *Room) *RoomAmenityAssignmentCreate {
	return _c.SetRoomID(v.ID)
}

// SetAmenity sets the "amenity" edge to the RoomAmenity entity.
func (_c *RoomAmenityAssignmentCreate) SetAmenity(v *RoomAmenity) *RoomAmenityAssignmentCreate {
	return _c.SetAmenityID(v.ID)
}

// Mutation returns the RoomAmenityAssignmentMutation object of the builder.
func (_c *RoomAmenityAssignmentCreate) Mutation() *RoomAmenityAssignmentMutation {
	return _c.mutation
}

// Save creates the RoomAmenityAssignment in the database.
func (_c *RoomAmenityAssignmentCreate) Save(ctx context.Context) (*RoomAmenityAssignment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RoomAmenityAssignmentCreate) SaveX(ctx context.Context) *RoomAmenityAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoomAmenityAssignmentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoomAmenityAssignmentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RoomAmenityAssignmentCreate) defaults() {
	if _, ok := _c.mutation.IsIncluded(); !ok {
		v := roomamenityassignment.DefaultIsIncluded
		_c.mutation.SetIsIncluded(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := roomamenityassignment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := roomamenityassignment.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RoomAmenityAssignmentCreate) check() error {
	if _, ok := _c.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "RoomAmenityAssignment.tenant_id"`)}
	}
	if _, ok := _c.mutation.RoomID(); !ok {
		return &ValidationError{Name: "room_id", err: errors.New(`ent: missing required field "RoomAmenityAssignment.room_id"`)}
	}
	if _, ok := _c.mutation.AmenityID(); !ok {
		return &ValidationError{Name: "amenity_id", err: errors.New(`ent: missing required field "RoomAmenityAssignment.amenity_id"`)}
	}
	if _, ok := _c.mutation.IsIncluded(); !ok {
		return &ValidationError{Name: "is_included", err: errors.New(`ent: missing required field "RoomAmenityAssignment.is_included"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RoomAmenityAssignment.created_at"`)}
	}
	if len(_c.mutation.RoomIDs()) == 0 {
		return &ValidationError{Name: "room", err: errors.New(`ent: missing required edge "RoomAmenityAssignment.room"`)}
	}
	if len(_c.mutation.AmenityIDs()) == 0 {
		return &ValidationError{Name: "amenity", err: errors.New(`ent: missing required edge "RoomAmenityAssignment.amenity"`)}
	}
	return nil
}

func (_c *RoomAmenityAssignmentCreate) sqlSave(ctx context.Context) (*RoomAmenityAssignment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RoomAmenityAssignmentCreate) createSpec() (*RoomAmenityAssignment, *sqlgraph.CreateSpec) {
	var (
		_node = &RoomAmenityAssignment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(roomamenityassignment.Table, sqlgraph.NewFieldSpec(roomamenityassignment.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TenantID(); ok {
		_spec.SetField(roomamenityassignment.FieldTenantID, field.TypeUUID, value)
		_node.TenantID = value
	}
	if value, ok := _c.mutation.IsIncluded(); ok {
		_spec.SetField(roomamenityassignment.FieldIsIncluded, field.TypeBool, value)
		_node.IsIncluded = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(roomamenityassignment.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(roomamenityassignment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.RoomIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roomamenityassignment.RoomTable,
			Columns: []string{roomamenityassignment.RoomColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(room.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoomID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AmenityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roomamenityassignment.AmenityTable,
			Columns: []string{roomamenityassignment.AmenityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roomamenity.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AmenityID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RoomAmenityAssignment.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RoomAmenityAssignmentUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *RoomAmenityAssignmentCreate) OnConflict(opts ...sql.ConflictOption) *RoomAmenityAssignmentUpsertOne {
	_c.conflict = opts
	return &RoomAmenityAssignmentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RoomAmenityAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RoomAmenityAssignmentCreate) OnConflictColumns(columns ...string) *RoomAmenityAssignmentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RoomAmenityAssignmentUpsertOne{
		create: _c,
	}
}

type (
	// RoomAmenityAssignmentUpsertOne is the builder for "upsert"-ing
	//  one RoomAmenityAssignment node.
	RoomAmenityAssignmentUpsertOne struct {
		create *RoomAmenityAssignmentCreate
	}

	// RoomAmenityAssignmentUpsert is the "OnConflict" setter.
	RoomAmenityAssignmentUpsert struct {
		*sql.UpdateSet
	}
)

// SetTenantID sets the "tenant_id" field.
func (u *RoomAmenityAssignmentUpsert) SetTenantID(v uuid.UUID) *RoomAmenityAssignmentUpsert {
	u.Set(roomamenityassignment.FieldTenantID, v)
	return u
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsert) UpdateTenantID() *RoomAmenityAssignmentUpsert {
	u.SetExcluded(roomamenityassignment.FieldTenantID)
	return u
}

// SetRoomID sets the "room_id" field.
func (u *RoomAmenityAssignmentUpsert) SetRoomID(v uuid.UUID) *RoomAmenityAssignmentUpsert {
	u.Set(roomamenityassignment.FieldRoomID, v)
	return u
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsert) UpdateRoomID() *RoomAmenityAssignmentUpsert {
	u.SetExcluded(roomamenityassignment.FieldRoomID)
	return u
}

// SetAmenityID sets the "amenity_id" field.
func (u *RoomAmenityAssignmentUpsert) SetAmenityID(v uuid.UUID) *RoomAmenityAssignmentUpsert {
	u.Set(roomamenityassignment.FieldAmenityID, v)
	return u
}

// UpdateAmenityID sets the "amenity_id" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsert) UpdateAmenityID() *RoomAmenityAssignmentUpsert {
	u.SetExcluded(roomamenityassignment.FieldAmenityID)
	return u
}

// SetIsIncluded sets the "is_included" field.
func (u *RoomAmenityAssignmentUpsert) SetIsIncluded(v bool) *RoomAmenityAssignmentUpsert {
	u.Set(roomamenityassignment.FieldIsIncluded, v)
	return u
}

// UpdateIsIncluded sets the "is_included" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsert) UpdateIsIncluded() *RoomAmenityAssignmentUpsert {
	u.SetExcluded(roomamenityassignment.FieldIsIncluded)
	return u
}

// SetNotes sets the "notes" field.
func (u *RoomAmenityAssignmentUpsert) SetNotes(v string) *RoomAmenityAssignmentUpsert {
	u.Set(roomamenityassignment.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsert) UpdateNotes() *RoomAmenityAssignmentUpsert {
	u.SetExcluded(roomamenityassignment.FieldNotes)
	return u
}

// ClearNotes clears the value of the "notes" field.
func (u *RoomAmenityAssignmentUpsert) ClearNotes() *RoomAmenityAssignmentUpsert {
	u.SetNull(roomamenityassignment.FieldNotes)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RoomAmenityAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(roomamenityassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RoomAmenityAssignmentUpsertOne) UpdateNewValues() *RoomAmenityAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(roomamenityassignment.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(roomamenityassignment.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RoomAmenityAssignment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RoomAmenityAssignmentUpsertOne) Ignore() *RoomAmenityAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RoomAmenityAssignmentUpsertOne) DoNothing() *RoomAmenityAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RoomAmenityAssignmentCreate.OnConflict
// documentation for more info.
func (u *RoomAmenityAssignmentUpsertOne) Update(set func(*RoomAmenityAssignmentUpsert)) *RoomAmenityAssignmentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RoomAmenityAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *RoomAmenityAssignmentUpsertOne) SetTenantID(v uuid.UUID) *RoomAmenityAssignmentUpsertOne {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsertOne) UpdateTenantID() *RoomAmenityAssignmentUpsertOne {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.UpdateTenantID()
	})
}

// SetRoomID sets the "room_id" field.
func (u *RoomAmenityAssignmentUpsertOne) SetRoomID(v uuid.UUID) *RoomAmenityAssignmentUpsertOne {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsertOne) UpdateRoomID() *RoomAmenityAssignmentUpsertOne {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.UpdateRoomID()
	})
}

// SetAmenityID sets the "amenity_id" field.
func (u *RoomAmenityAssignmentUpsertOne) SetAmenityID(v uuid.UUID) *RoomAmenityAssignmentUpsertOne {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.SetAmenityID(v)
	})
}

// UpdateAmenityID sets the "amenity_id" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsertOne) UpdateAmenityID() *RoomAmenityAssignmentUpsertOne {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.UpdateAmenityID()
	})
}

// SetIsIncluded sets the "is_included" field.
func (u *RoomAmenityAssignmentUpsertOne) SetIsIncluded(v bool) *RoomAmenityAssignmentUpsertOne {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.SetIsIncluded(v)
	})
}

// UpdateIsIncluded sets the "is_included" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsertOne) UpdateIsIncluded() *RoomAmenityAssignmentUpsertOne {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.UpdateIsIncluded()
	})
}

// SetNotes sets the "notes" field.
func (u *RoomAmenityAssignmentUpsertOne) SetNotes(v string) *RoomAmenityAssignmentUpsertOne {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsertOne) UpdateNotes() *RoomAmenityAssignmentUpsertOne {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *RoomAmenityAssignmentUpsertOne) ClearNotes() *RoomAmenityAssignmentUpsertOne {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *RoomAmenityAssignmentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RoomAmenityAssignmentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RoomAmenityAssignmentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RoomAmenityAssignmentUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: RoomAmenityAssignmentUpsertOne.ID is not supported by MySQL driver. Use RoomAmenityAssignmentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RoomAmenityAssignmentUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RoomAmenityAssignmentCreateBulk is the builder for creating many RoomAmenityAssignment entities in bulk.
type RoomAmenityAssignmentCreateBulk struct {
	config
	err      error
	builders []*RoomAmenityAssignmentCreate
	conflict []sql.ConflictOption
}

// Save creates the RoomAmenityAssignment entities in the database.
func (_c *RoomAmenityAssignmentCreateBulk) Save(ctx context.Context) ([]*RoomAmenityAssignment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RoomAmenityAssignment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RoomAmenityAssignmentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RoomAmenityAssignmentCreateBulk) SaveX(ctx context.Context) []*RoomAmenityAssignment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RoomAmenityAssignmentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RoomAmenityAssignmentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RoomAmenityAssignment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RoomAmenityAssignmentUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (_c *RoomAmenityAssignmentCreateBulk) OnConflict(opts ...sql.ConflictOption) *RoomAmenityAssignmentUpsertBulk {
	_c.conflict = opts
	return &RoomAmenityAssignmentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RoomAmenityAssignment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RoomAmenityAssignmentCreateBulk) OnConflictColumns(columns ...string) *RoomAmenityAssignmentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RoomAmenityAssignmentUpsertBulk{
		create: _c,
	}
}

// RoomAmenityAssignmentUpsertBulk is the builder for "upsert"-ing
// a bulk of RoomAmenityAssignment nodes.
type RoomAmenityAssignmentUpsertBulk struct {
	create *RoomAmenityAssignmentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RoomAmenityAssignment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(roomamenityassignment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RoomAmenityAssignmentUpsertBulk) UpdateNewValues() *RoomAmenityAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(roomamenityassignment.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(roomamenityassignment.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RoomAmenityAssignment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RoomAmenityAssignmentUpsertBulk) Ignore() *RoomAmenityAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RoomAmenityAssignmentUpsertBulk) DoNothing() *RoomAmenityAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RoomAmenityAssignmentCreateBulk.OnConflict
// documentation for more info.
func (u *RoomAmenityAssignmentUpsertBulk) Update(set func(*RoomAmenityAssignmentUpsert)) *RoomAmenityAssignmentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RoomAmenityAssignmentUpsert{UpdateSet: update})
	}))
	return u
}

// SetTenantID sets the "tenant_id" field.
func (u *RoomAmenityAssignmentUpsertBulk) SetTenantID(v uuid.UUID) *RoomAmenityAssignmentUpsertBulk {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.SetTenantID(v)
	})
}

// UpdateTenantID sets the "tenant_id" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsertBulk) UpdateTenantID() *RoomAmenityAssignmentUpsertBulk {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.UpdateTenantID()
	})
}

// SetRoomID sets the "room_id" field.
func (u *RoomAmenityAssignmentUpsertBulk) SetRoomID(v uuid.UUID) *RoomAmenityAssignmentUpsertBulk {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.SetRoomID(v)
	})
}

// UpdateRoomID sets the "room_id" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsertBulk) UpdateRoomID() *RoomAmenityAssignmentUpsertBulk {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.UpdateRoomID()
	})
}

// SetAmenityID sets the "amenity_id" field.
func (u *RoomAmenityAssignmentUpsertBulk) SetAmenityID(v uuid.UUID) *RoomAmenityAssignmentUpsertBulk {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.SetAmenityID(v)
	})
}

// UpdateAmenityID sets the "amenity_id" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsertBulk) UpdateAmenityID() *RoomAmenityAssignmentUpsertBulk {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.UpdateAmenityID()
	})
}

// SetIsIncluded sets the "is_included" field.
func (u *RoomAmenityAssignmentUpsertBulk) SetIsIncluded(v bool) *RoomAmenityAssignmentUpsertBulk {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.SetIsIncluded(v)
	})
}

// UpdateIsIncluded sets the "is_included" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsertBulk) UpdateIsIncluded() *RoomAmenityAssignmentUpsertBulk {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.UpdateIsIncluded()
	})
}

// SetNotes sets the "notes" field.
func (u *RoomAmenityAssignmentUpsertBulk) SetNotes(v string) *RoomAmenityAssignmentUpsertBulk {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *RoomAmenityAssignmentUpsertBulk) UpdateNotes() *RoomAmenityAssignmentUpsertBulk {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.UpdateNotes()
	})
}

// ClearNotes clears the value of the "notes" field.
func (u *RoomAmenityAssignmentUpsertBulk) ClearNotes() *RoomAmenityAssignmentUpsertBulk {
	return u.Update(func(s *RoomAmenityAssignmentUpsert) {
		s.ClearNotes()
	})
}

// Exec executes the query.
func (u *RoomAmenityAssignmentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RoomAmenityAssignmentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RoomAmenityAssignmentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RoomAmenityAssignmentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
