// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/shiftrotationslot"
	"github.com/google/uuid"
)

// ShiftRotationSlot is the model entity for the ShiftRotationSlot schema.
type ShiftRotationSlot struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// RotationID holds the value of the "rotation_id" field.
	RotationID uuid.UUID `json:"rotation_id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// StaffMemberID holds the value of the "staff_member_id" field.
	StaffMemberID uuid.UUID `json:"staff_member_id,omitempty"`
	// 1-based position in the cycle (1 = first day of cycle, cycle_days = last day)
	CycleDay int `json:"cycle_day,omitempty"`
	// HH:MM
	StartTime string `json:"start_time,omitempty"`
	// HH:MM
	EndTime string `json:"end_time,omitempty"`
	// Staff is off on this cycle day regardless of start/end times
	IsOffDay bool `json:"is_off_day,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ShiftRotationSlot) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case shiftrotationslot.FieldIsOffDay:
			values[i] = new(sql.NullBool)
		case shiftrotationslot.FieldCycleDay:
			values[i] = new(sql.NullInt64)
		case shiftrotationslot.FieldStartTime, shiftrotationslot.FieldEndTime:
			values[i] = new(sql.NullString)
		case shiftrotationslot.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case shiftrotationslot.FieldID, shiftrotationslot.FieldRotationID, shiftrotationslot.FieldTenantID, shiftrotationslot.FieldStaffMemberID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ShiftRotationSlot fields.
func (_m *ShiftRotationSlot) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case shiftrotationslot.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case shiftrotationslot.FieldRotationID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field rotation_id", values[i])
			} else if value != nil {
				_m.RotationID = *value
			}
		case shiftrotationslot.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case shiftrotationslot.FieldStaffMemberID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field staff_member_id", values[i])
			} else if value != nil {
				_m.StaffMemberID = *value
			}
		case shiftrotationslot.FieldCycleDay:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cycle_day", values[i])
			} else if value.Valid {
				_m.CycleDay = int(value.Int64)
			}
		case shiftrotationslot.FieldStartTime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field start_time", values[i])
			} else if value.Valid {
				_m.StartTime = value.String
			}
		case shiftrotationslot.FieldEndTime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field end_time", values[i])
			} else if value.Valid {
				_m.EndTime = value.String
			}
		case shiftrotationslot.FieldIsOffDay:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_off_day", values[i])
			} else if value.Valid {
				_m.IsOffDay = value.Bool
			}
		case shiftrotationslot.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ShiftRotationSlot.
// This includes values selected through modifiers, order, etc.
func (_m *ShiftRotationSlot) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ShiftRotationSlot.
// Note that you need to call ShiftRotationSlot.Unwrap() before calling this method if this ShiftRotationSlot
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ShiftRotationSlot) Update() *ShiftRotationSlotUpdateOne {
	return NewShiftRotationSlotClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ShiftRotationSlot entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ShiftRotationSlot) Unwrap() *ShiftRotationSlot {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ShiftRotationSlot is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ShiftRotationSlot) String() string {
	var builder strings.Builder
	builder.WriteString("ShiftRotationSlot(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("rotation_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.RotationID))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("staff_member_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StaffMemberID))
	builder.WriteString(", ")
	builder.WriteString("cycle_day=")
	builder.WriteString(fmt.Sprintf("%v", _m.CycleDay))
	builder.WriteString(", ")
	builder.WriteString("start_time=")
	builder.WriteString(_m.StartTime)
	builder.WriteString(", ")
	builder.WriteString("end_time=")
	builder.WriteString(_m.EndTime)
	builder.WriteString(", ")
	builder.WriteString("is_off_day=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsOffDay))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ShiftRotationSlots is a parsable slice of ShiftRotationSlot.
type ShiftRotationSlots []*ShiftRotationSlot
