// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/staffpurchaselink"
	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// StaffPurchaseLink is the model entity for the StaffPurchaseLink schema.
type StaffPurchaseLink struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// OutletID holds the value of the "outlet_id" field.
	OutletID *uuid.UUID `json:"outlet_id,omitempty"`
	// FK to StaffMember
	StaffMemberID uuid.UUID `json:"staff_member_id,omitempty"`
	// Auth-service user id (the sync key to erp)
	UserID uuid.UUID `json:"user_id,omitempty"`
	// Origin holds the value of the "origin" field.
	Origin staffpurchaselink.Origin `json:"origin,omitempty"`
	// LayawayPlanID holds the value of the "layaway_plan_id" field.
	LayawayPlanID *uuid.UUID `json:"layaway_plan_id,omitempty"`
	// PosOrderID holds the value of the "pos_order_id" field.
	PosOrderID *uuid.UUID `json:"pos_order_id,omitempty"`
	// pos:<origin>:<id> — idempotency key (unique per tenant)
	SourceKey string `json:"source_key,omitempty"`
	// erp StaffPurchaseDeduction id once synced
	ErpPurchaseID *uuid.UUID `json:"erp_purchase_id,omitempty"`
	// Principal holds the value of the "principal" field.
	Principal decimal.Decimal `json:"principal,omitempty"`
	// Recovered so far via payroll
	AmountSettled decimal.Decimal `json:"amount_settled,omitempty"`
	// Outstanding holds the value of the "outstanding" field.
	Outstanding decimal.Decimal `json:"outstanding,omitempty"`
	// SyncStatus holds the value of the "sync_status" field.
	SyncStatus staffpurchaselink.SyncStatus `json:"sync_status,omitempty"`
	// Status holds the value of the "status" field.
	Status staffpurchaselink.Status `json:"status,omitempty"`
	// SyncError holds the value of the "sync_error" field.
	SyncError string `json:"sync_error,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StaffPurchaseLink) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case staffpurchaselink.FieldOutletID, staffpurchaselink.FieldLayawayPlanID, staffpurchaselink.FieldPosOrderID, staffpurchaselink.FieldErpPurchaseID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case staffpurchaselink.FieldPrincipal, staffpurchaselink.FieldAmountSettled, staffpurchaselink.FieldOutstanding:
			values[i] = new(decimal.Decimal)
		case staffpurchaselink.FieldOrigin, staffpurchaselink.FieldSourceKey, staffpurchaselink.FieldSyncStatus, staffpurchaselink.FieldStatus, staffpurchaselink.FieldSyncError:
			values[i] = new(sql.NullString)
		case staffpurchaselink.FieldCreatedAt, staffpurchaselink.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case staffpurchaselink.FieldID, staffpurchaselink.FieldTenantID, staffpurchaselink.FieldStaffMemberID, staffpurchaselink.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StaffPurchaseLink fields.
func (_m *StaffPurchaseLink) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case staffpurchaselink.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case staffpurchaselink.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case staffpurchaselink.FieldOutletID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field outlet_id", values[i])
			} else if value.Valid {
				_m.OutletID = new(uuid.UUID)
				*_m.OutletID = *value.S.(*uuid.UUID)
			}
		case staffpurchaselink.FieldStaffMemberID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field staff_member_id", values[i])
			} else if value != nil {
				_m.StaffMemberID = *value
			}
		case staffpurchaselink.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case staffpurchaselink.FieldOrigin:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field origin", values[i])
			} else if value.Valid {
				_m.Origin = staffpurchaselink.Origin(value.String)
			}
		case staffpurchaselink.FieldLayawayPlanID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field layaway_plan_id", values[i])
			} else if value.Valid {
				_m.LayawayPlanID = new(uuid.UUID)
				*_m.LayawayPlanID = *value.S.(*uuid.UUID)
			}
		case staffpurchaselink.FieldPosOrderID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field pos_order_id", values[i])
			} else if value.Valid {
				_m.PosOrderID = new(uuid.UUID)
				*_m.PosOrderID = *value.S.(*uuid.UUID)
			}
		case staffpurchaselink.FieldSourceKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_key", values[i])
			} else if value.Valid {
				_m.SourceKey = value.String
			}
		case staffpurchaselink.FieldErpPurchaseID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field erp_purchase_id", values[i])
			} else if value.Valid {
				_m.ErpPurchaseID = new(uuid.UUID)
				*_m.ErpPurchaseID = *value.S.(*uuid.UUID)
			}
		case staffpurchaselink.FieldPrincipal:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field principal", values[i])
			} else if value != nil {
				_m.Principal = *value
			}
		case staffpurchaselink.FieldAmountSettled:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field amount_settled", values[i])
			} else if value != nil {
				_m.AmountSettled = *value
			}
		case staffpurchaselink.FieldOutstanding:
			if value, ok := values[i].(*decimal.Decimal); !ok {
				return fmt.Errorf("unexpected type %T for field outstanding", values[i])
			} else if value != nil {
				_m.Outstanding = *value
			}
		case staffpurchaselink.FieldSyncStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sync_status", values[i])
			} else if value.Valid {
				_m.SyncStatus = staffpurchaselink.SyncStatus(value.String)
			}
		case staffpurchaselink.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = staffpurchaselink.Status(value.String)
			}
		case staffpurchaselink.FieldSyncError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sync_error", values[i])
			} else if value.Valid {
				_m.SyncError = value.String
			}
		case staffpurchaselink.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case staffpurchaselink.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StaffPurchaseLink.
// This includes values selected through modifiers, order, etc.
func (_m *StaffPurchaseLink) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this StaffPurchaseLink.
// Note that you need to call StaffPurchaseLink.Unwrap() before calling this method if this StaffPurchaseLink
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StaffPurchaseLink) Update() *StaffPurchaseLinkUpdateOne {
	return NewStaffPurchaseLinkClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StaffPurchaseLink entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StaffPurchaseLink) Unwrap() *StaffPurchaseLink {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StaffPurchaseLink is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StaffPurchaseLink) String() string {
	var builder strings.Builder
	builder.WriteString("StaffPurchaseLink(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	if v := _m.OutletID; v != nil {
		builder.WriteString("outlet_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("staff_member_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StaffMemberID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("origin=")
	builder.WriteString(fmt.Sprintf("%v", _m.Origin))
	builder.WriteString(", ")
	if v := _m.LayawayPlanID; v != nil {
		builder.WriteString("layaway_plan_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PosOrderID; v != nil {
		builder.WriteString("pos_order_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("source_key=")
	builder.WriteString(_m.SourceKey)
	builder.WriteString(", ")
	if v := _m.ErpPurchaseID; v != nil {
		builder.WriteString("erp_purchase_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("principal=")
	builder.WriteString(fmt.Sprintf("%v", _m.Principal))
	builder.WriteString(", ")
	builder.WriteString("amount_settled=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountSettled))
	builder.WriteString(", ")
	builder.WriteString("outstanding=")
	builder.WriteString(fmt.Sprintf("%v", _m.Outstanding))
	builder.WriteString(", ")
	builder.WriteString("sync_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.SyncStatus))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("sync_error=")
	builder.WriteString(_m.SyncError)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// StaffPurchaseLinks is a parsable slice of StaffPurchaseLink.
type StaffPurchaseLinks []*StaffPurchaseLink
