// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/outlet"
	"github.com/bengobox/pos-service/internal/ent/staffmember"
	"github.com/bengobox/pos-service/internal/ent/staffoutlet"
	"github.com/google/uuid"
)

// StaffOutlet is the model entity for the StaffOutlet schema.
type StaffOutlet struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// StaffMemberID holds the value of the "staff_member_id" field.
	StaffMemberID uuid.UUID `json:"staff_member_id,omitempty"`
	// OutletID holds the value of the "outlet_id" field.
	OutletID uuid.UUID `json:"outlet_id,omitempty"`
	// True for the staff member's primary outlet
	IsHomeOutlet bool `json:"is_home_outlet,omitempty"`
	// AssignedAt holds the value of the "assigned_at" field.
	AssignedAt time.Time `json:"assigned_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the StaffOutletQuery when eager-loading is set.
	Edges        StaffOutletEdges `json:"edges"`
	selectValues sql.SelectValues
}

// StaffOutletEdges holds the relations/edges for other nodes in the graph.
type StaffOutletEdges struct {
	// StaffMember holds the value of the staff_member edge.
	StaffMember *StaffMember `json:"staff_member,omitempty"`
	// Outlet holds the value of the outlet edge.
	Outlet *Outlet `json:"outlet,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// StaffMemberOrErr returns the StaffMember value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StaffOutletEdges) StaffMemberOrErr() (*StaffMember, error) {
	if e.StaffMember != nil {
		return e.StaffMember, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: staffmember.Label}
	}
	return nil, &NotLoadedError{edge: "staff_member"}
}

// OutletOrErr returns the Outlet value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e StaffOutletEdges) OutletOrErr() (*Outlet, error) {
	if e.Outlet != nil {
		return e.Outlet, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: outlet.Label}
	}
	return nil, &NotLoadedError{edge: "outlet"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StaffOutlet) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case staffoutlet.FieldIsHomeOutlet:
			values[i] = new(sql.NullBool)
		case staffoutlet.FieldAssignedAt:
			values[i] = new(sql.NullTime)
		case staffoutlet.FieldID, staffoutlet.FieldTenantID, staffoutlet.FieldStaffMemberID, staffoutlet.FieldOutletID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StaffOutlet fields.
func (_m *StaffOutlet) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case staffoutlet.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case staffoutlet.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				_m.TenantID = *value
			}
		case staffoutlet.FieldStaffMemberID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field staff_member_id", values[i])
			} else if value != nil {
				_m.StaffMemberID = *value
			}
		case staffoutlet.FieldOutletID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field outlet_id", values[i])
			} else if value != nil {
				_m.OutletID = *value
			}
		case staffoutlet.FieldIsHomeOutlet:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_home_outlet", values[i])
			} else if value.Valid {
				_m.IsHomeOutlet = value.Bool
			}
		case staffoutlet.FieldAssignedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field assigned_at", values[i])
			} else if value.Valid {
				_m.AssignedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StaffOutlet.
// This includes values selected through modifiers, order, etc.
func (_m *StaffOutlet) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryStaffMember queries the "staff_member" edge of the StaffOutlet entity.
func (_m *StaffOutlet) QueryStaffMember() *StaffMemberQuery {
	return NewStaffOutletClient(_m.config).QueryStaffMember(_m)
}

// QueryOutlet queries the "outlet" edge of the StaffOutlet entity.
func (_m *StaffOutlet) QueryOutlet() *OutletQuery {
	return NewStaffOutletClient(_m.config).QueryOutlet(_m)
}

// Update returns a builder for updating this StaffOutlet.
// Note that you need to call StaffOutlet.Unwrap() before calling this method if this StaffOutlet
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StaffOutlet) Update() *StaffOutletUpdateOne {
	return NewStaffOutletClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StaffOutlet entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StaffOutlet) Unwrap() *StaffOutlet {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StaffOutlet is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StaffOutlet) String() string {
	var builder strings.Builder
	builder.WriteString("StaffOutlet(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.TenantID))
	builder.WriteString(", ")
	builder.WriteString("staff_member_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StaffMemberID))
	builder.WriteString(", ")
	builder.WriteString("outlet_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OutletID))
	builder.WriteString(", ")
	builder.WriteString("is_home_outlet=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsHomeOutlet))
	builder.WriteString(", ")
	builder.WriteString("assigned_at=")
	builder.WriteString(_m.AssignedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// StaffOutlets is a parsable slice of StaffOutlet.
type StaffOutlets []*StaffOutlet
