// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Appointment is the predicate function for appointment builders.
type Appointment func(*sql.Selector)

// BarTab is the predicate function for bartab builders.
type BarTab func(*sql.Selector)

// BarTabEvent is the predicate function for bartabevent builders.
type BarTabEvent func(*sql.Selector)

// CashDrawer is the predicate function for cashdrawer builders.
type CashDrawer func(*sql.Selector)

// CashDrawerEvent is the predicate function for cashdrawerevent builders.
type CashDrawerEvent func(*sql.Selector)

// CatalogItem is the predicate function for catalogitem builders.
type CatalogItem func(*sql.Selector)

// ChannelIntegration is the predicate function for channelintegration builders.
type ChannelIntegration func(*sql.Selector)

// ChannelSyncJob is the predicate function for channelsyncjob builders.
type ChannelSyncJob func(*sql.Selector)

// CommissionRecord is the predicate function for commissionrecord builders.
type CommissionRecord func(*sql.Selector)

// FeatureOverride is the predicate function for featureoverride builders.
type FeatureOverride func(*sql.Selector)

// GiftCard is the predicate function for giftcard builders.
type GiftCard func(*sql.Selector)

// GiftCardTransaction is the predicate function for giftcardtransaction builders.
type GiftCardTransaction func(*sql.Selector)

// IntegrationSetting is the predicate function for integrationsetting builders.
type IntegrationSetting func(*sql.Selector)

// InventorySnapshot is the predicate function for inventorysnapshot builders.
type InventorySnapshot func(*sql.Selector)

// KDSStation is the predicate function for kdsstation builders.
type KDSStation func(*sql.Selector)

// KDSTicket is the predicate function for kdsticket builders.
type KDSTicket func(*sql.Selector)

// LicenseUsageSnapshot is the predicate function for licenseusagesnapshot builders.
type LicenseUsageSnapshot func(*sql.Selector)

// Modifier is the predicate function for modifier builders.
type Modifier func(*sql.Selector)

// ModifierGroup is the predicate function for modifiergroup builders.
type ModifierGroup func(*sql.Selector)

// OrderLink is the predicate function for orderlink builders.
type OrderLink func(*sql.Selector)

// OutboxEvent is the predicate function for outboxevent builders.
type OutboxEvent func(*sql.Selector)

// Outlet is the predicate function for outlet builders.
type Outlet func(*sql.Selector)

// OutletSetting is the predicate function for outletsetting builders.
type OutletSetting func(*sql.Selector)

// POSDevice is the predicate function for posdevice builders.
type POSDevice func(*sql.Selector)

// POSDeviceSession is the predicate function for posdevicesession builders.
type POSDeviceSession func(*sql.Selector)

// POSLineModifier is the predicate function for poslinemodifier builders.
type POSLineModifier func(*sql.Selector)

// POSOrder is the predicate function for posorder builders.
type POSOrder func(*sql.Selector)

// POSOrderEvent is the predicate function for posorderevent builders.
type POSOrderEvent func(*sql.Selector)

// POSOrderLine is the predicate function for posorderline builders.
type POSOrderLine func(*sql.Selector)

// POSPayment is the predicate function for pospayment builders.
type POSPayment func(*sql.Selector)

// POSPermission is the predicate function for pospermission builders.
type POSPermission func(*sql.Selector)

// POSRefund is the predicate function for posrefund builders.
type POSRefund func(*sql.Selector)

// POSRole is the predicate function for posrole builders.
type POSRole func(*sql.Selector)

// POSRolePermission is the predicate function for posrolepermission builders.
type POSRolePermission func(*sql.Selector)

// POSRoleV2 is the predicate function for posrolev2 builders.
type POSRoleV2 func(*sql.Selector)

// POSUserRoleAssignment is the predicate function for posuserroleassignment builders.
type POSUserRoleAssignment func(*sql.Selector)

// PriceBook is the predicate function for pricebook builders.
type PriceBook func(*sql.Selector)

// PriceBookItem is the predicate function for pricebookitem builders.
type PriceBookItem func(*sql.Selector)

// Promotion is the predicate function for promotion builders.
type Promotion func(*sql.Selector)

// PromotionApplication is the predicate function for promotionapplication builders.
type PromotionApplication func(*sql.Selector)

// PromotionRule is the predicate function for promotionrule builders.
type PromotionRule func(*sql.Selector)

// RateLimitConfig is the predicate function for ratelimitconfig builders.
type RateLimitConfig func(*sql.Selector)

// Section is the predicate function for section builders.
type Section func(*sql.Selector)

// SerialNumberLog is the predicate function for serialnumberlog builders.
type SerialNumberLog func(*sql.Selector)

// ServiceConfig is the predicate function for serviceconfig builders.
type ServiceConfig func(*sql.Selector)

// StaffMember is the predicate function for staffmember builders.
type StaffMember func(*sql.Selector)

// StockAlertSubscription is the predicate function for stockalertsubscription builders.
type StockAlertSubscription func(*sql.Selector)

// StockConsumptionEvent is the predicate function for stockconsumptionevent builders.
type StockConsumptionEvent func(*sql.Selector)

// SyncFailure is the predicate function for syncfailure builders.
type SyncFailure func(*sql.Selector)

// Table is the predicate function for table builders.
type Table func(*sql.Selector)

// TableAssignment is the predicate function for tableassignment builders.
type TableAssignment func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// TenantSyncEvent is the predicate function for tenantsyncevent builders.
type TenantSyncEvent func(*sql.Selector)

// Tender is the predicate function for tender builders.
type Tender func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserPOSRole is the predicate function for userposrole builders.
type UserPOSRole func(*sql.Selector)

// WebhookSubscription is the predicate function for webhooksubscription builders.
type WebhookSubscription func(*sql.Selector)
