// Code generated by ent, DO NOT EDIT.

package staffpayrollline

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/pos-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldLTE(FieldID, id))
}

// PayrollID applies equality check predicate on the "payroll_id" field. It's identical to PayrollIDEQ.
func PayrollID(v uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldEQ(FieldPayrollID, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldEQ(FieldDescription, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v float64) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldEQ(FieldAmount, v))
}

// AdvanceID applies equality check predicate on the "advance_id" field. It's identical to AdvanceIDEQ.
func AdvanceID(v uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldEQ(FieldAdvanceID, v))
}

// PayrollIDEQ applies the EQ predicate on the "payroll_id" field.
func PayrollIDEQ(v uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldEQ(FieldPayrollID, v))
}

// PayrollIDNEQ applies the NEQ predicate on the "payroll_id" field.
func PayrollIDNEQ(v uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldNEQ(FieldPayrollID, v))
}

// PayrollIDIn applies the In predicate on the "payroll_id" field.
func PayrollIDIn(vs ...uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldIn(FieldPayrollID, vs...))
}

// PayrollIDNotIn applies the NotIn predicate on the "payroll_id" field.
func PayrollIDNotIn(vs ...uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldNotIn(FieldPayrollID, vs...))
}

// LineTypeEQ applies the EQ predicate on the "line_type" field.
func LineTypeEQ(v LineType) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldEQ(FieldLineType, v))
}

// LineTypeNEQ applies the NEQ predicate on the "line_type" field.
func LineTypeNEQ(v LineType) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldNEQ(FieldLineType, v))
}

// LineTypeIn applies the In predicate on the "line_type" field.
func LineTypeIn(vs ...LineType) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldIn(FieldLineType, vs...))
}

// LineTypeNotIn applies the NotIn predicate on the "line_type" field.
func LineTypeNotIn(vs ...LineType) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldNotIn(FieldLineType, vs...))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldContainsFold(FieldDescription, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v float64) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v float64) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...float64) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...float64) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v float64) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v float64) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v float64) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v float64) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldLTE(FieldAmount, v))
}

// AdvanceIDEQ applies the EQ predicate on the "advance_id" field.
func AdvanceIDEQ(v uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldEQ(FieldAdvanceID, v))
}

// AdvanceIDNEQ applies the NEQ predicate on the "advance_id" field.
func AdvanceIDNEQ(v uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldNEQ(FieldAdvanceID, v))
}

// AdvanceIDIn applies the In predicate on the "advance_id" field.
func AdvanceIDIn(vs ...uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldIn(FieldAdvanceID, vs...))
}

// AdvanceIDNotIn applies the NotIn predicate on the "advance_id" field.
func AdvanceIDNotIn(vs ...uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldNotIn(FieldAdvanceID, vs...))
}

// AdvanceIDGT applies the GT predicate on the "advance_id" field.
func AdvanceIDGT(v uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldGT(FieldAdvanceID, v))
}

// AdvanceIDGTE applies the GTE predicate on the "advance_id" field.
func AdvanceIDGTE(v uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldGTE(FieldAdvanceID, v))
}

// AdvanceIDLT applies the LT predicate on the "advance_id" field.
func AdvanceIDLT(v uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldLT(FieldAdvanceID, v))
}

// AdvanceIDLTE applies the LTE predicate on the "advance_id" field.
func AdvanceIDLTE(v uuid.UUID) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldLTE(FieldAdvanceID, v))
}

// AdvanceIDIsNil applies the IsNil predicate on the "advance_id" field.
func AdvanceIDIsNil() predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldIsNull(FieldAdvanceID))
}

// AdvanceIDNotNil applies the NotNil predicate on the "advance_id" field.
func AdvanceIDNotNil() predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.FieldNotNull(FieldAdvanceID))
}

// HasPayroll applies the HasEdge predicate on the "payroll" edge.
func HasPayroll() predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PayrollTable, PayrollColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPayrollWith applies the HasEdge predicate on the "payroll" edge with a given conditions (other predicates).
func HasPayrollWith(preds ...predicate.StaffPayroll) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(func(s *sql.Selector) {
		step := newPayrollStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StaffPayrollLine) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StaffPayrollLine) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StaffPayrollLine) predicate.StaffPayrollLine {
	return predicate.StaffPayrollLine(sql.NotPredicates(p))
}
