// Code generated by ent, DO NOT EDIT.

package controlledsubstancelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the controlledsubstancelog type in the database.
	Label = "controlled_substance_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldOutletID holds the string denoting the outlet_id field in the database.
	FieldOutletID = "outlet_id"
	// FieldPrescriptionID holds the string denoting the prescription_id field in the database.
	FieldPrescriptionID = "prescription_id"
	// FieldCatalogItemID holds the string denoting the catalog_item_id field in the database.
	FieldCatalogItemID = "catalog_item_id"
	// FieldItemSku holds the string denoting the item_sku field in the database.
	FieldItemSku = "item_sku"
	// FieldItemName holds the string denoting the item_name field in the database.
	FieldItemName = "item_name"
	// FieldQuantityDispensed holds the string denoting the quantity_dispensed field in the database.
	FieldQuantityDispensed = "quantity_dispensed"
	// FieldDispensedBy holds the string denoting the dispensed_by field in the database.
	FieldDispensedBy = "dispensed_by"
	// FieldPatientName holds the string denoting the patient_name field in the database.
	FieldPatientName = "patient_name"
	// FieldPatientIDNumber holds the string denoting the patient_id_number field in the database.
	FieldPatientIDNumber = "patient_id_number"
	// FieldWitnessStaffID holds the string denoting the witness_staff_id field in the database.
	FieldWitnessStaffID = "witness_staff_id"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldLotNumber holds the string denoting the lot_number field in the database.
	FieldLotNumber = "lot_number"
	// FieldLotExpiryDate holds the string denoting the lot_expiry_date field in the database.
	FieldLotExpiryDate = "lot_expiry_date"
	// FieldDispensedAt holds the string denoting the dispensed_at field in the database.
	FieldDispensedAt = "dispensed_at"
	// Table holds the table name of the controlledsubstancelog in the database.
	Table = "controlled_substance_logs"
)

// Columns holds all SQL columns for controlledsubstancelog fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldOutletID,
	FieldPrescriptionID,
	FieldCatalogItemID,
	FieldItemSku,
	FieldItemName,
	FieldQuantityDispensed,
	FieldDispensedBy,
	FieldPatientName,
	FieldPatientIDNumber,
	FieldWitnessStaffID,
	FieldNotes,
	FieldLotNumber,
	FieldLotExpiryDate,
	FieldDispensedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ItemSkuValidator is a validator for the "item_sku" field. It is called by the builders before save.
	ItemSkuValidator func(string) error
	// ItemNameValidator is a validator for the "item_name" field. It is called by the builders before save.
	ItemNameValidator func(string) error
	// PatientNameValidator is a validator for the "patient_name" field. It is called by the builders before save.
	PatientNameValidator func(string) error
	// DefaultDispensedAt holds the default value on creation for the "dispensed_at" field.
	DefaultDispensedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the ControlledSubstanceLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByOutletID orders the results by the outlet_id field.
func ByOutletID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutletID, opts...).ToFunc()
}

// ByPrescriptionID orders the results by the prescription_id field.
func ByPrescriptionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrescriptionID, opts...).ToFunc()
}

// ByCatalogItemID orders the results by the catalog_item_id field.
func ByCatalogItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCatalogItemID, opts...).ToFunc()
}

// ByItemSku orders the results by the item_sku field.
func ByItemSku(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemSku, opts...).ToFunc()
}

// ByItemName orders the results by the item_name field.
func ByItemName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemName, opts...).ToFunc()
}

// ByQuantityDispensed orders the results by the quantity_dispensed field.
func ByQuantityDispensed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuantityDispensed, opts...).ToFunc()
}

// ByDispensedBy orders the results by the dispensed_by field.
func ByDispensedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDispensedBy, opts...).ToFunc()
}

// ByPatientName orders the results by the patient_name field.
func ByPatientName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPatientName, opts...).ToFunc()
}

// ByPatientIDNumber orders the results by the patient_id_number field.
func ByPatientIDNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPatientIDNumber, opts...).ToFunc()
}

// ByWitnessStaffID orders the results by the witness_staff_id field.
func ByWitnessStaffID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWitnessStaffID, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByLotNumber orders the results by the lot_number field.
func ByLotNumber(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLotNumber, opts...).ToFunc()
}

// ByLotExpiryDate orders the results by the lot_expiry_date field.
func ByLotExpiryDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLotExpiryDate, opts...).ToFunc()
}

// ByDispensedAt orders the results by the dispensed_at field.
func ByDispensedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDispensedAt, opts...).ToFunc()
}
