// Code generated by ent, DO NOT EDIT.

package controlledsubstancelog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldTenantID, v))
}

// OutletID applies equality check predicate on the "outlet_id" field. It's identical to OutletIDEQ.
func OutletID(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldOutletID, v))
}

// PrescriptionID applies equality check predicate on the "prescription_id" field. It's identical to PrescriptionIDEQ.
func PrescriptionID(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldPrescriptionID, v))
}

// CatalogItemID applies equality check predicate on the "catalog_item_id" field. It's identical to CatalogItemIDEQ.
func CatalogItemID(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldCatalogItemID, v))
}

// ItemSku applies equality check predicate on the "item_sku" field. It's identical to ItemSkuEQ.
func ItemSku(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldItemSku, v))
}

// ItemName applies equality check predicate on the "item_name" field. It's identical to ItemNameEQ.
func ItemName(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldItemName, v))
}

// QuantityDispensed applies equality check predicate on the "quantity_dispensed" field. It's identical to QuantityDispensedEQ.
func QuantityDispensed(v float64) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldQuantityDispensed, v))
}

// DispensedBy applies equality check predicate on the "dispensed_by" field. It's identical to DispensedByEQ.
func DispensedBy(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldDispensedBy, v))
}

// PatientName applies equality check predicate on the "patient_name" field. It's identical to PatientNameEQ.
func PatientName(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldPatientName, v))
}

// PatientIDNumber applies equality check predicate on the "patient_id_number" field. It's identical to PatientIDNumberEQ.
func PatientIDNumber(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldPatientIDNumber, v))
}

// WitnessStaffID applies equality check predicate on the "witness_staff_id" field. It's identical to WitnessStaffIDEQ.
func WitnessStaffID(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldWitnessStaffID, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldNotes, v))
}

// LotNumber applies equality check predicate on the "lot_number" field. It's identical to LotNumberEQ.
func LotNumber(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldLotNumber, v))
}

// LotExpiryDate applies equality check predicate on the "lot_expiry_date" field. It's identical to LotExpiryDateEQ.
func LotExpiryDate(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldLotExpiryDate, v))
}

// DispensedAt applies equality check predicate on the "dispensed_at" field. It's identical to DispensedAtEQ.
func DispensedAt(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldDispensedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldTenantID, v))
}

// OutletIDEQ applies the EQ predicate on the "outlet_id" field.
func OutletIDEQ(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldOutletID, v))
}

// OutletIDNEQ applies the NEQ predicate on the "outlet_id" field.
func OutletIDNEQ(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldOutletID, v))
}

// OutletIDIn applies the In predicate on the "outlet_id" field.
func OutletIDIn(vs ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldOutletID, vs...))
}

// OutletIDNotIn applies the NotIn predicate on the "outlet_id" field.
func OutletIDNotIn(vs ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldOutletID, vs...))
}

// OutletIDGT applies the GT predicate on the "outlet_id" field.
func OutletIDGT(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldOutletID, v))
}

// OutletIDGTE applies the GTE predicate on the "outlet_id" field.
func OutletIDGTE(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldOutletID, v))
}

// OutletIDLT applies the LT predicate on the "outlet_id" field.
func OutletIDLT(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldOutletID, v))
}

// OutletIDLTE applies the LTE predicate on the "outlet_id" field.
func OutletIDLTE(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldOutletID, v))
}

// PrescriptionIDEQ applies the EQ predicate on the "prescription_id" field.
func PrescriptionIDEQ(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldPrescriptionID, v))
}

// PrescriptionIDNEQ applies the NEQ predicate on the "prescription_id" field.
func PrescriptionIDNEQ(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldPrescriptionID, v))
}

// PrescriptionIDIn applies the In predicate on the "prescription_id" field.
func PrescriptionIDIn(vs ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldPrescriptionID, vs...))
}

// PrescriptionIDNotIn applies the NotIn predicate on the "prescription_id" field.
func PrescriptionIDNotIn(vs ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldPrescriptionID, vs...))
}

// PrescriptionIDGT applies the GT predicate on the "prescription_id" field.
func PrescriptionIDGT(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldPrescriptionID, v))
}

// PrescriptionIDGTE applies the GTE predicate on the "prescription_id" field.
func PrescriptionIDGTE(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldPrescriptionID, v))
}

// PrescriptionIDLT applies the LT predicate on the "prescription_id" field.
func PrescriptionIDLT(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldPrescriptionID, v))
}

// PrescriptionIDLTE applies the LTE predicate on the "prescription_id" field.
func PrescriptionIDLTE(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldPrescriptionID, v))
}

// PrescriptionIDIsNil applies the IsNil predicate on the "prescription_id" field.
func PrescriptionIDIsNil() predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIsNull(FieldPrescriptionID))
}

// PrescriptionIDNotNil applies the NotNil predicate on the "prescription_id" field.
func PrescriptionIDNotNil() predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotNull(FieldPrescriptionID))
}

// CatalogItemIDEQ applies the EQ predicate on the "catalog_item_id" field.
func CatalogItemIDEQ(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldCatalogItemID, v))
}

// CatalogItemIDNEQ applies the NEQ predicate on the "catalog_item_id" field.
func CatalogItemIDNEQ(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldCatalogItemID, v))
}

// CatalogItemIDIn applies the In predicate on the "catalog_item_id" field.
func CatalogItemIDIn(vs ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldCatalogItemID, vs...))
}

// CatalogItemIDNotIn applies the NotIn predicate on the "catalog_item_id" field.
func CatalogItemIDNotIn(vs ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldCatalogItemID, vs...))
}

// CatalogItemIDGT applies the GT predicate on the "catalog_item_id" field.
func CatalogItemIDGT(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldCatalogItemID, v))
}

// CatalogItemIDGTE applies the GTE predicate on the "catalog_item_id" field.
func CatalogItemIDGTE(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldCatalogItemID, v))
}

// CatalogItemIDLT applies the LT predicate on the "catalog_item_id" field.
func CatalogItemIDLT(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldCatalogItemID, v))
}

// CatalogItemIDLTE applies the LTE predicate on the "catalog_item_id" field.
func CatalogItemIDLTE(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldCatalogItemID, v))
}

// ItemSkuEQ applies the EQ predicate on the "item_sku" field.
func ItemSkuEQ(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldItemSku, v))
}

// ItemSkuNEQ applies the NEQ predicate on the "item_sku" field.
func ItemSkuNEQ(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldItemSku, v))
}

// ItemSkuIn applies the In predicate on the "item_sku" field.
func ItemSkuIn(vs ...string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldItemSku, vs...))
}

// ItemSkuNotIn applies the NotIn predicate on the "item_sku" field.
func ItemSkuNotIn(vs ...string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldItemSku, vs...))
}

// ItemSkuGT applies the GT predicate on the "item_sku" field.
func ItemSkuGT(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldItemSku, v))
}

// ItemSkuGTE applies the GTE predicate on the "item_sku" field.
func ItemSkuGTE(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldItemSku, v))
}

// ItemSkuLT applies the LT predicate on the "item_sku" field.
func ItemSkuLT(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldItemSku, v))
}

// ItemSkuLTE applies the LTE predicate on the "item_sku" field.
func ItemSkuLTE(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldItemSku, v))
}

// ItemSkuContains applies the Contains predicate on the "item_sku" field.
func ItemSkuContains(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldContains(FieldItemSku, v))
}

// ItemSkuHasPrefix applies the HasPrefix predicate on the "item_sku" field.
func ItemSkuHasPrefix(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldHasPrefix(FieldItemSku, v))
}

// ItemSkuHasSuffix applies the HasSuffix predicate on the "item_sku" field.
func ItemSkuHasSuffix(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldHasSuffix(FieldItemSku, v))
}

// ItemSkuEqualFold applies the EqualFold predicate on the "item_sku" field.
func ItemSkuEqualFold(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEqualFold(FieldItemSku, v))
}

// ItemSkuContainsFold applies the ContainsFold predicate on the "item_sku" field.
func ItemSkuContainsFold(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldContainsFold(FieldItemSku, v))
}

// ItemNameEQ applies the EQ predicate on the "item_name" field.
func ItemNameEQ(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldItemName, v))
}

// ItemNameNEQ applies the NEQ predicate on the "item_name" field.
func ItemNameNEQ(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldItemName, v))
}

// ItemNameIn applies the In predicate on the "item_name" field.
func ItemNameIn(vs ...string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldItemName, vs...))
}

// ItemNameNotIn applies the NotIn predicate on the "item_name" field.
func ItemNameNotIn(vs ...string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldItemName, vs...))
}

// ItemNameGT applies the GT predicate on the "item_name" field.
func ItemNameGT(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldItemName, v))
}

// ItemNameGTE applies the GTE predicate on the "item_name" field.
func ItemNameGTE(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldItemName, v))
}

// ItemNameLT applies the LT predicate on the "item_name" field.
func ItemNameLT(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldItemName, v))
}

// ItemNameLTE applies the LTE predicate on the "item_name" field.
func ItemNameLTE(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldItemName, v))
}

// ItemNameContains applies the Contains predicate on the "item_name" field.
func ItemNameContains(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldContains(FieldItemName, v))
}

// ItemNameHasPrefix applies the HasPrefix predicate on the "item_name" field.
func ItemNameHasPrefix(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldHasPrefix(FieldItemName, v))
}

// ItemNameHasSuffix applies the HasSuffix predicate on the "item_name" field.
func ItemNameHasSuffix(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldHasSuffix(FieldItemName, v))
}

// ItemNameEqualFold applies the EqualFold predicate on the "item_name" field.
func ItemNameEqualFold(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEqualFold(FieldItemName, v))
}

// ItemNameContainsFold applies the ContainsFold predicate on the "item_name" field.
func ItemNameContainsFold(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldContainsFold(FieldItemName, v))
}

// QuantityDispensedEQ applies the EQ predicate on the "quantity_dispensed" field.
func QuantityDispensedEQ(v float64) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldQuantityDispensed, v))
}

// QuantityDispensedNEQ applies the NEQ predicate on the "quantity_dispensed" field.
func QuantityDispensedNEQ(v float64) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldQuantityDispensed, v))
}

// QuantityDispensedIn applies the In predicate on the "quantity_dispensed" field.
func QuantityDispensedIn(vs ...float64) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldQuantityDispensed, vs...))
}

// QuantityDispensedNotIn applies the NotIn predicate on the "quantity_dispensed" field.
func QuantityDispensedNotIn(vs ...float64) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldQuantityDispensed, vs...))
}

// QuantityDispensedGT applies the GT predicate on the "quantity_dispensed" field.
func QuantityDispensedGT(v float64) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldQuantityDispensed, v))
}

// QuantityDispensedGTE applies the GTE predicate on the "quantity_dispensed" field.
func QuantityDispensedGTE(v float64) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldQuantityDispensed, v))
}

// QuantityDispensedLT applies the LT predicate on the "quantity_dispensed" field.
func QuantityDispensedLT(v float64) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldQuantityDispensed, v))
}

// QuantityDispensedLTE applies the LTE predicate on the "quantity_dispensed" field.
func QuantityDispensedLTE(v float64) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldQuantityDispensed, v))
}

// DispensedByEQ applies the EQ predicate on the "dispensed_by" field.
func DispensedByEQ(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldDispensedBy, v))
}

// DispensedByNEQ applies the NEQ predicate on the "dispensed_by" field.
func DispensedByNEQ(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldDispensedBy, v))
}

// DispensedByIn applies the In predicate on the "dispensed_by" field.
func DispensedByIn(vs ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldDispensedBy, vs...))
}

// DispensedByNotIn applies the NotIn predicate on the "dispensed_by" field.
func DispensedByNotIn(vs ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldDispensedBy, vs...))
}

// DispensedByGT applies the GT predicate on the "dispensed_by" field.
func DispensedByGT(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldDispensedBy, v))
}

// DispensedByGTE applies the GTE predicate on the "dispensed_by" field.
func DispensedByGTE(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldDispensedBy, v))
}

// DispensedByLT applies the LT predicate on the "dispensed_by" field.
func DispensedByLT(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldDispensedBy, v))
}

// DispensedByLTE applies the LTE predicate on the "dispensed_by" field.
func DispensedByLTE(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldDispensedBy, v))
}

// PatientNameEQ applies the EQ predicate on the "patient_name" field.
func PatientNameEQ(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldPatientName, v))
}

// PatientNameNEQ applies the NEQ predicate on the "patient_name" field.
func PatientNameNEQ(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldPatientName, v))
}

// PatientNameIn applies the In predicate on the "patient_name" field.
func PatientNameIn(vs ...string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldPatientName, vs...))
}

// PatientNameNotIn applies the NotIn predicate on the "patient_name" field.
func PatientNameNotIn(vs ...string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldPatientName, vs...))
}

// PatientNameGT applies the GT predicate on the "patient_name" field.
func PatientNameGT(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldPatientName, v))
}

// PatientNameGTE applies the GTE predicate on the "patient_name" field.
func PatientNameGTE(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldPatientName, v))
}

// PatientNameLT applies the LT predicate on the "patient_name" field.
func PatientNameLT(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldPatientName, v))
}

// PatientNameLTE applies the LTE predicate on the "patient_name" field.
func PatientNameLTE(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldPatientName, v))
}

// PatientNameContains applies the Contains predicate on the "patient_name" field.
func PatientNameContains(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldContains(FieldPatientName, v))
}

// PatientNameHasPrefix applies the HasPrefix predicate on the "patient_name" field.
func PatientNameHasPrefix(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldHasPrefix(FieldPatientName, v))
}

// PatientNameHasSuffix applies the HasSuffix predicate on the "patient_name" field.
func PatientNameHasSuffix(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldHasSuffix(FieldPatientName, v))
}

// PatientNameEqualFold applies the EqualFold predicate on the "patient_name" field.
func PatientNameEqualFold(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEqualFold(FieldPatientName, v))
}

// PatientNameContainsFold applies the ContainsFold predicate on the "patient_name" field.
func PatientNameContainsFold(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldContainsFold(FieldPatientName, v))
}

// PatientIDNumberEQ applies the EQ predicate on the "patient_id_number" field.
func PatientIDNumberEQ(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldPatientIDNumber, v))
}

// PatientIDNumberNEQ applies the NEQ predicate on the "patient_id_number" field.
func PatientIDNumberNEQ(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldPatientIDNumber, v))
}

// PatientIDNumberIn applies the In predicate on the "patient_id_number" field.
func PatientIDNumberIn(vs ...string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldPatientIDNumber, vs...))
}

// PatientIDNumberNotIn applies the NotIn predicate on the "patient_id_number" field.
func PatientIDNumberNotIn(vs ...string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldPatientIDNumber, vs...))
}

// PatientIDNumberGT applies the GT predicate on the "patient_id_number" field.
func PatientIDNumberGT(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldPatientIDNumber, v))
}

// PatientIDNumberGTE applies the GTE predicate on the "patient_id_number" field.
func PatientIDNumberGTE(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldPatientIDNumber, v))
}

// PatientIDNumberLT applies the LT predicate on the "patient_id_number" field.
func PatientIDNumberLT(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldPatientIDNumber, v))
}

// PatientIDNumberLTE applies the LTE predicate on the "patient_id_number" field.
func PatientIDNumberLTE(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldPatientIDNumber, v))
}

// PatientIDNumberContains applies the Contains predicate on the "patient_id_number" field.
func PatientIDNumberContains(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldContains(FieldPatientIDNumber, v))
}

// PatientIDNumberHasPrefix applies the HasPrefix predicate on the "patient_id_number" field.
func PatientIDNumberHasPrefix(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldHasPrefix(FieldPatientIDNumber, v))
}

// PatientIDNumberHasSuffix applies the HasSuffix predicate on the "patient_id_number" field.
func PatientIDNumberHasSuffix(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldHasSuffix(FieldPatientIDNumber, v))
}

// PatientIDNumberIsNil applies the IsNil predicate on the "patient_id_number" field.
func PatientIDNumberIsNil() predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIsNull(FieldPatientIDNumber))
}

// PatientIDNumberNotNil applies the NotNil predicate on the "patient_id_number" field.
func PatientIDNumberNotNil() predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotNull(FieldPatientIDNumber))
}

// PatientIDNumberEqualFold applies the EqualFold predicate on the "patient_id_number" field.
func PatientIDNumberEqualFold(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEqualFold(FieldPatientIDNumber, v))
}

// PatientIDNumberContainsFold applies the ContainsFold predicate on the "patient_id_number" field.
func PatientIDNumberContainsFold(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldContainsFold(FieldPatientIDNumber, v))
}

// WitnessStaffIDEQ applies the EQ predicate on the "witness_staff_id" field.
func WitnessStaffIDEQ(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldWitnessStaffID, v))
}

// WitnessStaffIDNEQ applies the NEQ predicate on the "witness_staff_id" field.
func WitnessStaffIDNEQ(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldWitnessStaffID, v))
}

// WitnessStaffIDIn applies the In predicate on the "witness_staff_id" field.
func WitnessStaffIDIn(vs ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldWitnessStaffID, vs...))
}

// WitnessStaffIDNotIn applies the NotIn predicate on the "witness_staff_id" field.
func WitnessStaffIDNotIn(vs ...uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldWitnessStaffID, vs...))
}

// WitnessStaffIDGT applies the GT predicate on the "witness_staff_id" field.
func WitnessStaffIDGT(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldWitnessStaffID, v))
}

// WitnessStaffIDGTE applies the GTE predicate on the "witness_staff_id" field.
func WitnessStaffIDGTE(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldWitnessStaffID, v))
}

// WitnessStaffIDLT applies the LT predicate on the "witness_staff_id" field.
func WitnessStaffIDLT(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldWitnessStaffID, v))
}

// WitnessStaffIDLTE applies the LTE predicate on the "witness_staff_id" field.
func WitnessStaffIDLTE(v uuid.UUID) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldWitnessStaffID, v))
}

// WitnessStaffIDIsNil applies the IsNil predicate on the "witness_staff_id" field.
func WitnessStaffIDIsNil() predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIsNull(FieldWitnessStaffID))
}

// WitnessStaffIDNotNil applies the NotNil predicate on the "witness_staff_id" field.
func WitnessStaffIDNotNil() predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotNull(FieldWitnessStaffID))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesIsNil applies the IsNil predicate on the "notes" field.
func NotesIsNil() predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIsNull(FieldNotes))
}

// NotesNotNil applies the NotNil predicate on the "notes" field.
func NotesNotNil() predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotNull(FieldNotes))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldContainsFold(FieldNotes, v))
}

// LotNumberEQ applies the EQ predicate on the "lot_number" field.
func LotNumberEQ(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldLotNumber, v))
}

// LotNumberNEQ applies the NEQ predicate on the "lot_number" field.
func LotNumberNEQ(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldLotNumber, v))
}

// LotNumberIn applies the In predicate on the "lot_number" field.
func LotNumberIn(vs ...string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldLotNumber, vs...))
}

// LotNumberNotIn applies the NotIn predicate on the "lot_number" field.
func LotNumberNotIn(vs ...string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldLotNumber, vs...))
}

// LotNumberGT applies the GT predicate on the "lot_number" field.
func LotNumberGT(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldLotNumber, v))
}

// LotNumberGTE applies the GTE predicate on the "lot_number" field.
func LotNumberGTE(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldLotNumber, v))
}

// LotNumberLT applies the LT predicate on the "lot_number" field.
func LotNumberLT(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldLotNumber, v))
}

// LotNumberLTE applies the LTE predicate on the "lot_number" field.
func LotNumberLTE(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldLotNumber, v))
}

// LotNumberContains applies the Contains predicate on the "lot_number" field.
func LotNumberContains(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldContains(FieldLotNumber, v))
}

// LotNumberHasPrefix applies the HasPrefix predicate on the "lot_number" field.
func LotNumberHasPrefix(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldHasPrefix(FieldLotNumber, v))
}

// LotNumberHasSuffix applies the HasSuffix predicate on the "lot_number" field.
func LotNumberHasSuffix(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldHasSuffix(FieldLotNumber, v))
}

// LotNumberIsNil applies the IsNil predicate on the "lot_number" field.
func LotNumberIsNil() predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIsNull(FieldLotNumber))
}

// LotNumberNotNil applies the NotNil predicate on the "lot_number" field.
func LotNumberNotNil() predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotNull(FieldLotNumber))
}

// LotNumberEqualFold applies the EqualFold predicate on the "lot_number" field.
func LotNumberEqualFold(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEqualFold(FieldLotNumber, v))
}

// LotNumberContainsFold applies the ContainsFold predicate on the "lot_number" field.
func LotNumberContainsFold(v string) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldContainsFold(FieldLotNumber, v))
}

// LotExpiryDateEQ applies the EQ predicate on the "lot_expiry_date" field.
func LotExpiryDateEQ(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldLotExpiryDate, v))
}

// LotExpiryDateNEQ applies the NEQ predicate on the "lot_expiry_date" field.
func LotExpiryDateNEQ(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldLotExpiryDate, v))
}

// LotExpiryDateIn applies the In predicate on the "lot_expiry_date" field.
func LotExpiryDateIn(vs ...time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldLotExpiryDate, vs...))
}

// LotExpiryDateNotIn applies the NotIn predicate on the "lot_expiry_date" field.
func LotExpiryDateNotIn(vs ...time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldLotExpiryDate, vs...))
}

// LotExpiryDateGT applies the GT predicate on the "lot_expiry_date" field.
func LotExpiryDateGT(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldLotExpiryDate, v))
}

// LotExpiryDateGTE applies the GTE predicate on the "lot_expiry_date" field.
func LotExpiryDateGTE(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldLotExpiryDate, v))
}

// LotExpiryDateLT applies the LT predicate on the "lot_expiry_date" field.
func LotExpiryDateLT(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldLotExpiryDate, v))
}

// LotExpiryDateLTE applies the LTE predicate on the "lot_expiry_date" field.
func LotExpiryDateLTE(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldLotExpiryDate, v))
}

// LotExpiryDateIsNil applies the IsNil predicate on the "lot_expiry_date" field.
func LotExpiryDateIsNil() predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIsNull(FieldLotExpiryDate))
}

// LotExpiryDateNotNil applies the NotNil predicate on the "lot_expiry_date" field.
func LotExpiryDateNotNil() predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotNull(FieldLotExpiryDate))
}

// DispensedAtEQ applies the EQ predicate on the "dispensed_at" field.
func DispensedAtEQ(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldEQ(FieldDispensedAt, v))
}

// DispensedAtNEQ applies the NEQ predicate on the "dispensed_at" field.
func DispensedAtNEQ(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNEQ(FieldDispensedAt, v))
}

// DispensedAtIn applies the In predicate on the "dispensed_at" field.
func DispensedAtIn(vs ...time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldIn(FieldDispensedAt, vs...))
}

// DispensedAtNotIn applies the NotIn predicate on the "dispensed_at" field.
func DispensedAtNotIn(vs ...time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldNotIn(FieldDispensedAt, vs...))
}

// DispensedAtGT applies the GT predicate on the "dispensed_at" field.
func DispensedAtGT(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGT(FieldDispensedAt, v))
}

// DispensedAtGTE applies the GTE predicate on the "dispensed_at" field.
func DispensedAtGTE(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldGTE(FieldDispensedAt, v))
}

// DispensedAtLT applies the LT predicate on the "dispensed_at" field.
func DispensedAtLT(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLT(FieldDispensedAt, v))
}

// DispensedAtLTE applies the LTE predicate on the "dispensed_at" field.
func DispensedAtLTE(v time.Time) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.FieldLTE(FieldDispensedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ControlledSubstanceLog) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ControlledSubstanceLog) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ControlledSubstanceLog) predicate.ControlledSubstanceLog {
	return predicate.ControlledSubstanceLog(sql.NotPredicates(p))
}
