// Code generated by ent, DO NOT EDIT.

package commissionrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bengobox/pos-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldTenantID, v))
}

// OutletID applies equality check predicate on the "outlet_id" field. It's identical to OutletIDEQ.
func OutletID(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldOutletID, v))
}

// StaffMemberID applies equality check predicate on the "staff_member_id" field. It's identical to StaffMemberIDEQ.
func StaffMemberID(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldStaffMemberID, v))
}

// CatalogItemID applies equality check predicate on the "catalog_item_id" field. It's identical to CatalogItemIDEQ.
func CatalogItemID(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldCatalogItemID, v))
}

// RuleType applies equality check predicate on the "rule_type" field. It's identical to RuleTypeEQ.
func RuleType(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldRuleType, v))
}

// FlatAmount applies equality check predicate on the "flat_amount" field. It's identical to FlatAmountEQ.
func FlatAmount(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldFlatAmount, v))
}

// Percentage applies equality check predicate on the "percentage" field. It's identical to PercentageEQ.
func Percentage(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldPercentage, v))
}

// IsActive applies equality check predicate on the "is_active" field. It's identical to IsActiveEQ.
func IsActive(v bool) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldIsActive, v))
}

// EffectiveFrom applies equality check predicate on the "effective_from" field. It's identical to EffectiveFromEQ.
func EffectiveFrom(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveTo applies equality check predicate on the "effective_to" field. It's identical to EffectiveToEQ.
func EffectiveTo(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldEffectiveTo, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldTenantID, v))
}

// OutletIDEQ applies the EQ predicate on the "outlet_id" field.
func OutletIDEQ(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldOutletID, v))
}

// OutletIDNEQ applies the NEQ predicate on the "outlet_id" field.
func OutletIDNEQ(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldOutletID, v))
}

// OutletIDIn applies the In predicate on the "outlet_id" field.
func OutletIDIn(vs ...uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldOutletID, vs...))
}

// OutletIDNotIn applies the NotIn predicate on the "outlet_id" field.
func OutletIDNotIn(vs ...uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldOutletID, vs...))
}

// OutletIDGT applies the GT predicate on the "outlet_id" field.
func OutletIDGT(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldOutletID, v))
}

// OutletIDGTE applies the GTE predicate on the "outlet_id" field.
func OutletIDGTE(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldOutletID, v))
}

// OutletIDLT applies the LT predicate on the "outlet_id" field.
func OutletIDLT(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldOutletID, v))
}

// OutletIDLTE applies the LTE predicate on the "outlet_id" field.
func OutletIDLTE(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldOutletID, v))
}

// OutletIDIsNil applies the IsNil predicate on the "outlet_id" field.
func OutletIDIsNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIsNull(FieldOutletID))
}

// OutletIDNotNil applies the NotNil predicate on the "outlet_id" field.
func OutletIDNotNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotNull(FieldOutletID))
}

// StaffMemberIDEQ applies the EQ predicate on the "staff_member_id" field.
func StaffMemberIDEQ(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldStaffMemberID, v))
}

// StaffMemberIDNEQ applies the NEQ predicate on the "staff_member_id" field.
func StaffMemberIDNEQ(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldStaffMemberID, v))
}

// StaffMemberIDIn applies the In predicate on the "staff_member_id" field.
func StaffMemberIDIn(vs ...uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldStaffMemberID, vs...))
}

// StaffMemberIDNotIn applies the NotIn predicate on the "staff_member_id" field.
func StaffMemberIDNotIn(vs ...uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldStaffMemberID, vs...))
}

// StaffMemberIDGT applies the GT predicate on the "staff_member_id" field.
func StaffMemberIDGT(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldStaffMemberID, v))
}

// StaffMemberIDGTE applies the GTE predicate on the "staff_member_id" field.
func StaffMemberIDGTE(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldStaffMemberID, v))
}

// StaffMemberIDLT applies the LT predicate on the "staff_member_id" field.
func StaffMemberIDLT(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldStaffMemberID, v))
}

// StaffMemberIDLTE applies the LTE predicate on the "staff_member_id" field.
func StaffMemberIDLTE(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldStaffMemberID, v))
}

// StaffMemberIDIsNil applies the IsNil predicate on the "staff_member_id" field.
func StaffMemberIDIsNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIsNull(FieldStaffMemberID))
}

// StaffMemberIDNotNil applies the NotNil predicate on the "staff_member_id" field.
func StaffMemberIDNotNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotNull(FieldStaffMemberID))
}

// CatalogItemIDEQ applies the EQ predicate on the "catalog_item_id" field.
func CatalogItemIDEQ(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldCatalogItemID, v))
}

// CatalogItemIDNEQ applies the NEQ predicate on the "catalog_item_id" field.
func CatalogItemIDNEQ(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldCatalogItemID, v))
}

// CatalogItemIDIn applies the In predicate on the "catalog_item_id" field.
func CatalogItemIDIn(vs ...uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldCatalogItemID, vs...))
}

// CatalogItemIDNotIn applies the NotIn predicate on the "catalog_item_id" field.
func CatalogItemIDNotIn(vs ...uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldCatalogItemID, vs...))
}

// CatalogItemIDGT applies the GT predicate on the "catalog_item_id" field.
func CatalogItemIDGT(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldCatalogItemID, v))
}

// CatalogItemIDGTE applies the GTE predicate on the "catalog_item_id" field.
func CatalogItemIDGTE(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldCatalogItemID, v))
}

// CatalogItemIDLT applies the LT predicate on the "catalog_item_id" field.
func CatalogItemIDLT(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldCatalogItemID, v))
}

// CatalogItemIDLTE applies the LTE predicate on the "catalog_item_id" field.
func CatalogItemIDLTE(v uuid.UUID) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldCatalogItemID, v))
}

// CatalogItemIDIsNil applies the IsNil predicate on the "catalog_item_id" field.
func CatalogItemIDIsNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIsNull(FieldCatalogItemID))
}

// CatalogItemIDNotNil applies the NotNil predicate on the "catalog_item_id" field.
func CatalogItemIDNotNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotNull(FieldCatalogItemID))
}

// RuleTypeEQ applies the EQ predicate on the "rule_type" field.
func RuleTypeEQ(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldRuleType, v))
}

// RuleTypeNEQ applies the NEQ predicate on the "rule_type" field.
func RuleTypeNEQ(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldRuleType, v))
}

// RuleTypeIn applies the In predicate on the "rule_type" field.
func RuleTypeIn(vs ...string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldRuleType, vs...))
}

// RuleTypeNotIn applies the NotIn predicate on the "rule_type" field.
func RuleTypeNotIn(vs ...string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldRuleType, vs...))
}

// RuleTypeGT applies the GT predicate on the "rule_type" field.
func RuleTypeGT(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldRuleType, v))
}

// RuleTypeGTE applies the GTE predicate on the "rule_type" field.
func RuleTypeGTE(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldRuleType, v))
}

// RuleTypeLT applies the LT predicate on the "rule_type" field.
func RuleTypeLT(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldRuleType, v))
}

// RuleTypeLTE applies the LTE predicate on the "rule_type" field.
func RuleTypeLTE(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldRuleType, v))
}

// RuleTypeContains applies the Contains predicate on the "rule_type" field.
func RuleTypeContains(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldContains(FieldRuleType, v))
}

// RuleTypeHasPrefix applies the HasPrefix predicate on the "rule_type" field.
func RuleTypeHasPrefix(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldHasPrefix(FieldRuleType, v))
}

// RuleTypeHasSuffix applies the HasSuffix predicate on the "rule_type" field.
func RuleTypeHasSuffix(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldHasSuffix(FieldRuleType, v))
}

// RuleTypeEqualFold applies the EqualFold predicate on the "rule_type" field.
func RuleTypeEqualFold(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEqualFold(FieldRuleType, v))
}

// RuleTypeContainsFold applies the ContainsFold predicate on the "rule_type" field.
func RuleTypeContainsFold(v string) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldContainsFold(FieldRuleType, v))
}

// FlatAmountEQ applies the EQ predicate on the "flat_amount" field.
func FlatAmountEQ(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldFlatAmount, v))
}

// FlatAmountNEQ applies the NEQ predicate on the "flat_amount" field.
func FlatAmountNEQ(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldFlatAmount, v))
}

// FlatAmountIn applies the In predicate on the "flat_amount" field.
func FlatAmountIn(vs ...float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldFlatAmount, vs...))
}

// FlatAmountNotIn applies the NotIn predicate on the "flat_amount" field.
func FlatAmountNotIn(vs ...float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldFlatAmount, vs...))
}

// FlatAmountGT applies the GT predicate on the "flat_amount" field.
func FlatAmountGT(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldFlatAmount, v))
}

// FlatAmountGTE applies the GTE predicate on the "flat_amount" field.
func FlatAmountGTE(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldFlatAmount, v))
}

// FlatAmountLT applies the LT predicate on the "flat_amount" field.
func FlatAmountLT(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldFlatAmount, v))
}

// FlatAmountLTE applies the LTE predicate on the "flat_amount" field.
func FlatAmountLTE(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldFlatAmount, v))
}

// FlatAmountIsNil applies the IsNil predicate on the "flat_amount" field.
func FlatAmountIsNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIsNull(FieldFlatAmount))
}

// FlatAmountNotNil applies the NotNil predicate on the "flat_amount" field.
func FlatAmountNotNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotNull(FieldFlatAmount))
}

// PercentageEQ applies the EQ predicate on the "percentage" field.
func PercentageEQ(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldPercentage, v))
}

// PercentageNEQ applies the NEQ predicate on the "percentage" field.
func PercentageNEQ(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldPercentage, v))
}

// PercentageIn applies the In predicate on the "percentage" field.
func PercentageIn(vs ...float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldPercentage, vs...))
}

// PercentageNotIn applies the NotIn predicate on the "percentage" field.
func PercentageNotIn(vs ...float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldPercentage, vs...))
}

// PercentageGT applies the GT predicate on the "percentage" field.
func PercentageGT(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldPercentage, v))
}

// PercentageGTE applies the GTE predicate on the "percentage" field.
func PercentageGTE(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldPercentage, v))
}

// PercentageLT applies the LT predicate on the "percentage" field.
func PercentageLT(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldPercentage, v))
}

// PercentageLTE applies the LTE predicate on the "percentage" field.
func PercentageLTE(v float64) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldPercentage, v))
}

// PercentageIsNil applies the IsNil predicate on the "percentage" field.
func PercentageIsNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIsNull(FieldPercentage))
}

// PercentageNotNil applies the NotNil predicate on the "percentage" field.
func PercentageNotNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotNull(FieldPercentage))
}

// TierRulesIsNil applies the IsNil predicate on the "tier_rules" field.
func TierRulesIsNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIsNull(FieldTierRules))
}

// TierRulesNotNil applies the NotNil predicate on the "tier_rules" field.
func TierRulesNotNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotNull(FieldTierRules))
}

// IsActiveEQ applies the EQ predicate on the "is_active" field.
func IsActiveEQ(v bool) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldIsActive, v))
}

// IsActiveNEQ applies the NEQ predicate on the "is_active" field.
func IsActiveNEQ(v bool) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldIsActive, v))
}

// EffectiveFromEQ applies the EQ predicate on the "effective_from" field.
func EffectiveFromEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveFromNEQ applies the NEQ predicate on the "effective_from" field.
func EffectiveFromNEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldEffectiveFrom, v))
}

// EffectiveFromIn applies the In predicate on the "effective_from" field.
func EffectiveFromIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromNotIn applies the NotIn predicate on the "effective_from" field.
func EffectiveFromNotIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromGT applies the GT predicate on the "effective_from" field.
func EffectiveFromGT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldEffectiveFrom, v))
}

// EffectiveFromGTE applies the GTE predicate on the "effective_from" field.
func EffectiveFromGTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldEffectiveFrom, v))
}

// EffectiveFromLT applies the LT predicate on the "effective_from" field.
func EffectiveFromLT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldEffectiveFrom, v))
}

// EffectiveFromLTE applies the LTE predicate on the "effective_from" field.
func EffectiveFromLTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldEffectiveFrom, v))
}

// EffectiveToEQ applies the EQ predicate on the "effective_to" field.
func EffectiveToEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldEffectiveTo, v))
}

// EffectiveToNEQ applies the NEQ predicate on the "effective_to" field.
func EffectiveToNEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldEffectiveTo, v))
}

// EffectiveToIn applies the In predicate on the "effective_to" field.
func EffectiveToIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldEffectiveTo, vs...))
}

// EffectiveToNotIn applies the NotIn predicate on the "effective_to" field.
func EffectiveToNotIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldEffectiveTo, vs...))
}

// EffectiveToGT applies the GT predicate on the "effective_to" field.
func EffectiveToGT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldEffectiveTo, v))
}

// EffectiveToGTE applies the GTE predicate on the "effective_to" field.
func EffectiveToGTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldEffectiveTo, v))
}

// EffectiveToLT applies the LT predicate on the "effective_to" field.
func EffectiveToLT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldEffectiveTo, v))
}

// EffectiveToLTE applies the LTE predicate on the "effective_to" field.
func EffectiveToLTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldEffectiveTo, v))
}

// EffectiveToIsNil applies the IsNil predicate on the "effective_to" field.
func EffectiveToIsNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIsNull(FieldEffectiveTo))
}

// EffectiveToNotNil applies the NotNil predicate on the "effective_to" field.
func EffectiveToNotNil() predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotNull(FieldEffectiveTo))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.CommissionRule {
	return predicate.CommissionRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CommissionRule) predicate.CommissionRule {
	return predicate.CommissionRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CommissionRule) predicate.CommissionRule {
	return predicate.CommissionRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CommissionRule) predicate.CommissionRule {
	return predicate.CommissionRule(sql.NotPredicates(p))
}
