// Code generated by ent, DO NOT EDIT.

package loyaltyprogram

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the loyaltyprogram type in the database.
	Label = "loyalty_program"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTenantID holds the string denoting the tenant_id field in the database.
	FieldTenantID = "tenant_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldEarnRate holds the string denoting the earn_rate field in the database.
	FieldEarnRate = "earn_rate"
	// FieldRedeemRate holds the string denoting the redeem_rate field in the database.
	FieldRedeemRate = "redeem_rate"
	// FieldMinRedeemPoints holds the string denoting the min_redeem_points field in the database.
	FieldMinRedeemPoints = "min_redeem_points"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldTierThresholds holds the string denoting the tier_thresholds field in the database.
	FieldTierThresholds = "tier_thresholds"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the loyaltyprogram in the database.
	Table = "loyalty_programs"
)

// Columns holds all SQL columns for loyaltyprogram fields.
var Columns = []string{
	FieldID,
	FieldTenantID,
	FieldName,
	FieldDescription,
	FieldEarnRate,
	FieldRedeemRate,
	FieldMinRedeemPoints,
	FieldIsActive,
	FieldTierThresholds,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultEarnRate holds the default value on creation for the "earn_rate" field.
	DefaultEarnRate float64
	// DefaultRedeemRate holds the default value on creation for the "redeem_rate" field.
	DefaultRedeemRate float64
	// DefaultMinRedeemPoints holds the default value on creation for the "min_redeem_points" field.
	DefaultMinRedeemPoints int
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the LoyaltyProgram queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTenantID orders the results by the tenant_id field.
func ByTenantID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTenantID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByEarnRate orders the results by the earn_rate field.
func ByEarnRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEarnRate, opts...).ToFunc()
}

// ByRedeemRate orders the results by the redeem_rate field.
func ByRedeemRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRedeemRate, opts...).ToFunc()
}

// ByMinRedeemPoints orders the results by the min_redeem_points field.
func ByMinRedeemPoints(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinRedeemPoints, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
