// Code generated by ent, DO NOT EDIT.

package staffpayroll

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/bengobox/pos-service/internal/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldTenantID, v))
}

// StaffID applies equality check predicate on the "staff_id" field. It's identical to StaffIDEQ.
func StaffID(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldStaffID, v))
}

// PeriodStart applies equality check predicate on the "period_start" field. It's identical to PeriodStartEQ.
func PeriodStart(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodEnd applies equality check predicate on the "period_end" field. It's identical to PeriodEndEQ.
func PeriodEnd(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldPeriodEnd, v))
}

// GrossAmount applies equality check predicate on the "gross_amount" field. It's identical to GrossAmountEQ.
func GrossAmount(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldGrossAmount, v))
}

// TotalDeductions applies equality check predicate on the "total_deductions" field. It's identical to TotalDeductionsEQ.
func TotalDeductions(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldTotalDeductions, v))
}

// NetAmount applies equality check predicate on the "net_amount" field. It's identical to NetAmountEQ.
func NetAmount(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldNetAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldCurrency, v))
}

// ApprovedBy applies equality check predicate on the "approved_by" field. It's identical to ApprovedByEQ.
func ApprovedBy(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldApprovedBy, v))
}

// ApprovedAt applies equality check predicate on the "approved_at" field. It's identical to ApprovedAtEQ.
func ApprovedAt(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldApprovedAt, v))
}

// PaidAt applies equality check predicate on the "paid_at" field. It's identical to PaidAtEQ.
func PaidAt(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldPaidAt, v))
}

// PayoutReference applies equality check predicate on the "payout_reference" field. It's identical to PayoutReferenceEQ.
func PayoutReference(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldPayoutReference, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldUpdatedAt, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldTenantID, v))
}

// StaffIDEQ applies the EQ predicate on the "staff_id" field.
func StaffIDEQ(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldStaffID, v))
}

// StaffIDNEQ applies the NEQ predicate on the "staff_id" field.
func StaffIDNEQ(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldStaffID, v))
}

// StaffIDIn applies the In predicate on the "staff_id" field.
func StaffIDIn(vs ...uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldStaffID, vs...))
}

// StaffIDNotIn applies the NotIn predicate on the "staff_id" field.
func StaffIDNotIn(vs ...uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldStaffID, vs...))
}

// StaffIDGT applies the GT predicate on the "staff_id" field.
func StaffIDGT(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldStaffID, v))
}

// StaffIDGTE applies the GTE predicate on the "staff_id" field.
func StaffIDGTE(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldStaffID, v))
}

// StaffIDLT applies the LT predicate on the "staff_id" field.
func StaffIDLT(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldStaffID, v))
}

// StaffIDLTE applies the LTE predicate on the "staff_id" field.
func StaffIDLTE(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldStaffID, v))
}

// PeriodStartEQ applies the EQ predicate on the "period_start" field.
func PeriodStartEQ(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldPeriodStart, v))
}

// PeriodStartNEQ applies the NEQ predicate on the "period_start" field.
func PeriodStartNEQ(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldPeriodStart, v))
}

// PeriodStartIn applies the In predicate on the "period_start" field.
func PeriodStartIn(vs ...time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldPeriodStart, vs...))
}

// PeriodStartNotIn applies the NotIn predicate on the "period_start" field.
func PeriodStartNotIn(vs ...time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldPeriodStart, vs...))
}

// PeriodStartGT applies the GT predicate on the "period_start" field.
func PeriodStartGT(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldPeriodStart, v))
}

// PeriodStartGTE applies the GTE predicate on the "period_start" field.
func PeriodStartGTE(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldPeriodStart, v))
}

// PeriodStartLT applies the LT predicate on the "period_start" field.
func PeriodStartLT(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldPeriodStart, v))
}

// PeriodStartLTE applies the LTE predicate on the "period_start" field.
func PeriodStartLTE(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldPeriodStart, v))
}

// PeriodEndEQ applies the EQ predicate on the "period_end" field.
func PeriodEndEQ(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldPeriodEnd, v))
}

// PeriodEndNEQ applies the NEQ predicate on the "period_end" field.
func PeriodEndNEQ(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldPeriodEnd, v))
}

// PeriodEndIn applies the In predicate on the "period_end" field.
func PeriodEndIn(vs ...time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldPeriodEnd, vs...))
}

// PeriodEndNotIn applies the NotIn predicate on the "period_end" field.
func PeriodEndNotIn(vs ...time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldPeriodEnd, vs...))
}

// PeriodEndGT applies the GT predicate on the "period_end" field.
func PeriodEndGT(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldPeriodEnd, v))
}

// PeriodEndGTE applies the GTE predicate on the "period_end" field.
func PeriodEndGTE(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldPeriodEnd, v))
}

// PeriodEndLT applies the LT predicate on the "period_end" field.
func PeriodEndLT(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldPeriodEnd, v))
}

// PeriodEndLTE applies the LTE predicate on the "period_end" field.
func PeriodEndLTE(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldPeriodEnd, v))
}

// GrossAmountEQ applies the EQ predicate on the "gross_amount" field.
func GrossAmountEQ(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldGrossAmount, v))
}

// GrossAmountNEQ applies the NEQ predicate on the "gross_amount" field.
func GrossAmountNEQ(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldGrossAmount, v))
}

// GrossAmountIn applies the In predicate on the "gross_amount" field.
func GrossAmountIn(vs ...float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldGrossAmount, vs...))
}

// GrossAmountNotIn applies the NotIn predicate on the "gross_amount" field.
func GrossAmountNotIn(vs ...float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldGrossAmount, vs...))
}

// GrossAmountGT applies the GT predicate on the "gross_amount" field.
func GrossAmountGT(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldGrossAmount, v))
}

// GrossAmountGTE applies the GTE predicate on the "gross_amount" field.
func GrossAmountGTE(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldGrossAmount, v))
}

// GrossAmountLT applies the LT predicate on the "gross_amount" field.
func GrossAmountLT(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldGrossAmount, v))
}

// GrossAmountLTE applies the LTE predicate on the "gross_amount" field.
func GrossAmountLTE(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldGrossAmount, v))
}

// TotalDeductionsEQ applies the EQ predicate on the "total_deductions" field.
func TotalDeductionsEQ(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldTotalDeductions, v))
}

// TotalDeductionsNEQ applies the NEQ predicate on the "total_deductions" field.
func TotalDeductionsNEQ(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldTotalDeductions, v))
}

// TotalDeductionsIn applies the In predicate on the "total_deductions" field.
func TotalDeductionsIn(vs ...float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldTotalDeductions, vs...))
}

// TotalDeductionsNotIn applies the NotIn predicate on the "total_deductions" field.
func TotalDeductionsNotIn(vs ...float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldTotalDeductions, vs...))
}

// TotalDeductionsGT applies the GT predicate on the "total_deductions" field.
func TotalDeductionsGT(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldTotalDeductions, v))
}

// TotalDeductionsGTE applies the GTE predicate on the "total_deductions" field.
func TotalDeductionsGTE(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldTotalDeductions, v))
}

// TotalDeductionsLT applies the LT predicate on the "total_deductions" field.
func TotalDeductionsLT(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldTotalDeductions, v))
}

// TotalDeductionsLTE applies the LTE predicate on the "total_deductions" field.
func TotalDeductionsLTE(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldTotalDeductions, v))
}

// NetAmountEQ applies the EQ predicate on the "net_amount" field.
func NetAmountEQ(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldNetAmount, v))
}

// NetAmountNEQ applies the NEQ predicate on the "net_amount" field.
func NetAmountNEQ(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldNetAmount, v))
}

// NetAmountIn applies the In predicate on the "net_amount" field.
func NetAmountIn(vs ...float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldNetAmount, vs...))
}

// NetAmountNotIn applies the NotIn predicate on the "net_amount" field.
func NetAmountNotIn(vs ...float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldNetAmount, vs...))
}

// NetAmountGT applies the GT predicate on the "net_amount" field.
func NetAmountGT(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldNetAmount, v))
}

// NetAmountGTE applies the GTE predicate on the "net_amount" field.
func NetAmountGTE(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldNetAmount, v))
}

// NetAmountLT applies the LT predicate on the "net_amount" field.
func NetAmountLT(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldNetAmount, v))
}

// NetAmountLTE applies the LTE predicate on the "net_amount" field.
func NetAmountLTE(v float64) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldNetAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldContainsFold(FieldCurrency, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldStatus, vs...))
}

// ApprovedByEQ applies the EQ predicate on the "approved_by" field.
func ApprovedByEQ(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldApprovedBy, v))
}

// ApprovedByNEQ applies the NEQ predicate on the "approved_by" field.
func ApprovedByNEQ(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldApprovedBy, v))
}

// ApprovedByIn applies the In predicate on the "approved_by" field.
func ApprovedByIn(vs ...uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldApprovedBy, vs...))
}

// ApprovedByNotIn applies the NotIn predicate on the "approved_by" field.
func ApprovedByNotIn(vs ...uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldApprovedBy, vs...))
}

// ApprovedByGT applies the GT predicate on the "approved_by" field.
func ApprovedByGT(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldApprovedBy, v))
}

// ApprovedByGTE applies the GTE predicate on the "approved_by" field.
func ApprovedByGTE(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldApprovedBy, v))
}

// ApprovedByLT applies the LT predicate on the "approved_by" field.
func ApprovedByLT(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldApprovedBy, v))
}

// ApprovedByLTE applies the LTE predicate on the "approved_by" field.
func ApprovedByLTE(v uuid.UUID) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldApprovedBy, v))
}

// ApprovedByIsNil applies the IsNil predicate on the "approved_by" field.
func ApprovedByIsNil() predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIsNull(FieldApprovedBy))
}

// ApprovedByNotNil applies the NotNil predicate on the "approved_by" field.
func ApprovedByNotNil() predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotNull(FieldApprovedBy))
}

// ApprovedAtEQ applies the EQ predicate on the "approved_at" field.
func ApprovedAtEQ(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldApprovedAt, v))
}

// ApprovedAtNEQ applies the NEQ predicate on the "approved_at" field.
func ApprovedAtNEQ(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldApprovedAt, v))
}

// ApprovedAtIn applies the In predicate on the "approved_at" field.
func ApprovedAtIn(vs ...time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldApprovedAt, vs...))
}

// ApprovedAtNotIn applies the NotIn predicate on the "approved_at" field.
func ApprovedAtNotIn(vs ...time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldApprovedAt, vs...))
}

// ApprovedAtGT applies the GT predicate on the "approved_at" field.
func ApprovedAtGT(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldApprovedAt, v))
}

// ApprovedAtGTE applies the GTE predicate on the "approved_at" field.
func ApprovedAtGTE(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldApprovedAt, v))
}

// ApprovedAtLT applies the LT predicate on the "approved_at" field.
func ApprovedAtLT(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldApprovedAt, v))
}

// ApprovedAtLTE applies the LTE predicate on the "approved_at" field.
func ApprovedAtLTE(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldApprovedAt, v))
}

// ApprovedAtIsNil applies the IsNil predicate on the "approved_at" field.
func ApprovedAtIsNil() predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIsNull(FieldApprovedAt))
}

// ApprovedAtNotNil applies the NotNil predicate on the "approved_at" field.
func ApprovedAtNotNil() predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotNull(FieldApprovedAt))
}

// PaidAtEQ applies the EQ predicate on the "paid_at" field.
func PaidAtEQ(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldPaidAt, v))
}

// PaidAtNEQ applies the NEQ predicate on the "paid_at" field.
func PaidAtNEQ(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldPaidAt, v))
}

// PaidAtIn applies the In predicate on the "paid_at" field.
func PaidAtIn(vs ...time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldPaidAt, vs...))
}

// PaidAtNotIn applies the NotIn predicate on the "paid_at" field.
func PaidAtNotIn(vs ...time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldPaidAt, vs...))
}

// PaidAtGT applies the GT predicate on the "paid_at" field.
func PaidAtGT(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldPaidAt, v))
}

// PaidAtGTE applies the GTE predicate on the "paid_at" field.
func PaidAtGTE(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldPaidAt, v))
}

// PaidAtLT applies the LT predicate on the "paid_at" field.
func PaidAtLT(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldPaidAt, v))
}

// PaidAtLTE applies the LTE predicate on the "paid_at" field.
func PaidAtLTE(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldPaidAt, v))
}

// PaidAtIsNil applies the IsNil predicate on the "paid_at" field.
func PaidAtIsNil() predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIsNull(FieldPaidAt))
}

// PaidAtNotNil applies the NotNil predicate on the "paid_at" field.
func PaidAtNotNil() predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotNull(FieldPaidAt))
}

// PayoutReferenceEQ applies the EQ predicate on the "payout_reference" field.
func PayoutReferenceEQ(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldPayoutReference, v))
}

// PayoutReferenceNEQ applies the NEQ predicate on the "payout_reference" field.
func PayoutReferenceNEQ(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldPayoutReference, v))
}

// PayoutReferenceIn applies the In predicate on the "payout_reference" field.
func PayoutReferenceIn(vs ...string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldPayoutReference, vs...))
}

// PayoutReferenceNotIn applies the NotIn predicate on the "payout_reference" field.
func PayoutReferenceNotIn(vs ...string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldPayoutReference, vs...))
}

// PayoutReferenceGT applies the GT predicate on the "payout_reference" field.
func PayoutReferenceGT(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldPayoutReference, v))
}

// PayoutReferenceGTE applies the GTE predicate on the "payout_reference" field.
func PayoutReferenceGTE(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldPayoutReference, v))
}

// PayoutReferenceLT applies the LT predicate on the "payout_reference" field.
func PayoutReferenceLT(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldPayoutReference, v))
}

// PayoutReferenceLTE applies the LTE predicate on the "payout_reference" field.
func PayoutReferenceLTE(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldPayoutReference, v))
}

// PayoutReferenceContains applies the Contains predicate on the "payout_reference" field.
func PayoutReferenceContains(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldContains(FieldPayoutReference, v))
}

// PayoutReferenceHasPrefix applies the HasPrefix predicate on the "payout_reference" field.
func PayoutReferenceHasPrefix(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldHasPrefix(FieldPayoutReference, v))
}

// PayoutReferenceHasSuffix applies the HasSuffix predicate on the "payout_reference" field.
func PayoutReferenceHasSuffix(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldHasSuffix(FieldPayoutReference, v))
}

// PayoutReferenceIsNil applies the IsNil predicate on the "payout_reference" field.
func PayoutReferenceIsNil() predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIsNull(FieldPayoutReference))
}

// PayoutReferenceNotNil applies the NotNil predicate on the "payout_reference" field.
func PayoutReferenceNotNil() predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotNull(FieldPayoutReference))
}

// PayoutReferenceEqualFold applies the EqualFold predicate on the "payout_reference" field.
func PayoutReferenceEqualFold(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEqualFold(FieldPayoutReference, v))
}

// PayoutReferenceContainsFold applies the ContainsFold predicate on the "payout_reference" field.
func PayoutReferenceContainsFold(v string) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldContainsFold(FieldPayoutReference, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasLines applies the HasEdge predicate on the "lines" edge.
func HasLines() predicate.StaffPayroll {
	return predicate.StaffPayroll(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LinesTable, LinesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLinesWith applies the HasEdge predicate on the "lines" edge with a given conditions (other predicates).
func HasLinesWith(preds ...predicate.StaffPayrollLine) predicate.StaffPayroll {
	return predicate.StaffPayroll(func(s *sql.Selector) {
		step := newLinesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.StaffPayroll) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.StaffPayroll) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.StaffPayroll) predicate.StaffPayroll {
	return predicate.StaffPayroll(sql.NotPredicates(p))
}
