// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/bengobox/pos-service/internal/ent"
)

// The BarTabFunc type is an adapter to allow the use of ordinary
// function as BarTab mutator.
type BarTabFunc func(context.Context, *ent.BarTabMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BarTabFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BarTabMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BarTabMutation", m)
}

// The BarTabEventFunc type is an adapter to allow the use of ordinary
// function as BarTabEvent mutator.
type BarTabEventFunc func(context.Context, *ent.BarTabEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f BarTabEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.BarTabEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.BarTabEventMutation", m)
}

// The CashDrawerFunc type is an adapter to allow the use of ordinary
// function as CashDrawer mutator.
type CashDrawerFunc func(context.Context, *ent.CashDrawerMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CashDrawerFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CashDrawerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CashDrawerMutation", m)
}

// The CashDrawerEventFunc type is an adapter to allow the use of ordinary
// function as CashDrawerEvent mutator.
type CashDrawerEventFunc func(context.Context, *ent.CashDrawerEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CashDrawerEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CashDrawerEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CashDrawerEventMutation", m)
}

// The CatalogItemFunc type is an adapter to allow the use of ordinary
// function as CatalogItem mutator.
type CatalogItemFunc func(context.Context, *ent.CatalogItemMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CatalogItemFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CatalogItemMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CatalogItemMutation", m)
}

// The ChannelIntegrationFunc type is an adapter to allow the use of ordinary
// function as ChannelIntegration mutator.
type ChannelIntegrationFunc func(context.Context, *ent.ChannelIntegrationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ChannelIntegrationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ChannelIntegrationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ChannelIntegrationMutation", m)
}

// The ChannelSyncJobFunc type is an adapter to allow the use of ordinary
// function as ChannelSyncJob mutator.
type ChannelSyncJobFunc func(context.Context, *ent.ChannelSyncJobMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ChannelSyncJobFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ChannelSyncJobMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ChannelSyncJobMutation", m)
}

// The FeatureOverrideFunc type is an adapter to allow the use of ordinary
// function as FeatureOverride mutator.
type FeatureOverrideFunc func(context.Context, *ent.FeatureOverrideMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f FeatureOverrideFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.FeatureOverrideMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.FeatureOverrideMutation", m)
}

// The GiftCardFunc type is an adapter to allow the use of ordinary
// function as GiftCard mutator.
type GiftCardFunc func(context.Context, *ent.GiftCardMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GiftCardFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GiftCardMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GiftCardMutation", m)
}

// The GiftCardTransactionFunc type is an adapter to allow the use of ordinary
// function as GiftCardTransaction mutator.
type GiftCardTransactionFunc func(context.Context, *ent.GiftCardTransactionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GiftCardTransactionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GiftCardTransactionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GiftCardTransactionMutation", m)
}

// The IntegrationSettingFunc type is an adapter to allow the use of ordinary
// function as IntegrationSetting mutator.
type IntegrationSettingFunc func(context.Context, *ent.IntegrationSettingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f IntegrationSettingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.IntegrationSettingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.IntegrationSettingMutation", m)
}

// The InventorySnapshotFunc type is an adapter to allow the use of ordinary
// function as InventorySnapshot mutator.
type InventorySnapshotFunc func(context.Context, *ent.InventorySnapshotMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f InventorySnapshotFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.InventorySnapshotMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.InventorySnapshotMutation", m)
}

// The LicenseUsageSnapshotFunc type is an adapter to allow the use of ordinary
// function as LicenseUsageSnapshot mutator.
type LicenseUsageSnapshotFunc func(context.Context, *ent.LicenseUsageSnapshotMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f LicenseUsageSnapshotFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.LicenseUsageSnapshotMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.LicenseUsageSnapshotMutation", m)
}

// The ModifierFunc type is an adapter to allow the use of ordinary
// function as Modifier mutator.
type ModifierFunc func(context.Context, *ent.ModifierMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ModifierFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ModifierMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ModifierMutation", m)
}

// The ModifierGroupFunc type is an adapter to allow the use of ordinary
// function as ModifierGroup mutator.
type ModifierGroupFunc func(context.Context, *ent.ModifierGroupMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ModifierGroupFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ModifierGroupMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ModifierGroupMutation", m)
}

// The OrderLinkFunc type is an adapter to allow the use of ordinary
// function as OrderLink mutator.
type OrderLinkFunc func(context.Context, *ent.OrderLinkMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OrderLinkFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OrderLinkMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OrderLinkMutation", m)
}

// The OutboxEventFunc type is an adapter to allow the use of ordinary
// function as OutboxEvent mutator.
type OutboxEventFunc func(context.Context, *ent.OutboxEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OutboxEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OutboxEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OutboxEventMutation", m)
}

// The OutletFunc type is an adapter to allow the use of ordinary
// function as Outlet mutator.
type OutletFunc func(context.Context, *ent.OutletMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OutletFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OutletMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OutletMutation", m)
}

// The OutletSettingFunc type is an adapter to allow the use of ordinary
// function as OutletSetting mutator.
type OutletSettingFunc func(context.Context, *ent.OutletSettingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f OutletSettingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.OutletSettingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.OutletSettingMutation", m)
}

// The POSDeviceFunc type is an adapter to allow the use of ordinary
// function as POSDevice mutator.
type POSDeviceFunc func(context.Context, *ent.POSDeviceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSDeviceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSDeviceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSDeviceMutation", m)
}

// The POSDeviceSessionFunc type is an adapter to allow the use of ordinary
// function as POSDeviceSession mutator.
type POSDeviceSessionFunc func(context.Context, *ent.POSDeviceSessionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSDeviceSessionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSDeviceSessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSDeviceSessionMutation", m)
}

// The POSLineModifierFunc type is an adapter to allow the use of ordinary
// function as POSLineModifier mutator.
type POSLineModifierFunc func(context.Context, *ent.POSLineModifierMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSLineModifierFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSLineModifierMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSLineModifierMutation", m)
}

// The POSOrderFunc type is an adapter to allow the use of ordinary
// function as POSOrder mutator.
type POSOrderFunc func(context.Context, *ent.POSOrderMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSOrderFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSOrderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSOrderMutation", m)
}

// The POSOrderEventFunc type is an adapter to allow the use of ordinary
// function as POSOrderEvent mutator.
type POSOrderEventFunc func(context.Context, *ent.POSOrderEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSOrderEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSOrderEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSOrderEventMutation", m)
}

// The POSOrderLineFunc type is an adapter to allow the use of ordinary
// function as POSOrderLine mutator.
type POSOrderLineFunc func(context.Context, *ent.POSOrderLineMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSOrderLineFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSOrderLineMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSOrderLineMutation", m)
}

// The POSPaymentFunc type is an adapter to allow the use of ordinary
// function as POSPayment mutator.
type POSPaymentFunc func(context.Context, *ent.POSPaymentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSPaymentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSPaymentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSPaymentMutation", m)
}

// The POSPermissionFunc type is an adapter to allow the use of ordinary
// function as POSPermission mutator.
type POSPermissionFunc func(context.Context, *ent.POSPermissionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSPermissionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSPermissionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSPermissionMutation", m)
}

// The POSRefundFunc type is an adapter to allow the use of ordinary
// function as POSRefund mutator.
type POSRefundFunc func(context.Context, *ent.POSRefundMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSRefundFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSRefundMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSRefundMutation", m)
}

// The POSRoleFunc type is an adapter to allow the use of ordinary
// function as POSRole mutator.
type POSRoleFunc func(context.Context, *ent.POSRoleMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSRoleFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSRoleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSRoleMutation", m)
}

// The POSRolePermissionFunc type is an adapter to allow the use of ordinary
// function as POSRolePermission mutator.
type POSRolePermissionFunc func(context.Context, *ent.POSRolePermissionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSRolePermissionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSRolePermissionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSRolePermissionMutation", m)
}

// The POSRoleV2Func type is an adapter to allow the use of ordinary
// function as POSRoleV2 mutator.
type POSRoleV2Func func(context.Context, *ent.POSRoleV2Mutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSRoleV2Func) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSRoleV2Mutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSRoleV2Mutation", m)
}

// The POSUserRoleAssignmentFunc type is an adapter to allow the use of ordinary
// function as POSUserRoleAssignment mutator.
type POSUserRoleAssignmentFunc func(context.Context, *ent.POSUserRoleAssignmentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f POSUserRoleAssignmentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.POSUserRoleAssignmentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.POSUserRoleAssignmentMutation", m)
}

// The PriceBookFunc type is an adapter to allow the use of ordinary
// function as PriceBook mutator.
type PriceBookFunc func(context.Context, *ent.PriceBookMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PriceBookFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PriceBookMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PriceBookMutation", m)
}

// The PriceBookItemFunc type is an adapter to allow the use of ordinary
// function as PriceBookItem mutator.
type PriceBookItemFunc func(context.Context, *ent.PriceBookItemMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PriceBookItemFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PriceBookItemMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PriceBookItemMutation", m)
}

// The PromotionFunc type is an adapter to allow the use of ordinary
// function as Promotion mutator.
type PromotionFunc func(context.Context, *ent.PromotionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PromotionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PromotionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PromotionMutation", m)
}

// The PromotionApplicationFunc type is an adapter to allow the use of ordinary
// function as PromotionApplication mutator.
type PromotionApplicationFunc func(context.Context, *ent.PromotionApplicationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PromotionApplicationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PromotionApplicationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PromotionApplicationMutation", m)
}

// The PromotionRuleFunc type is an adapter to allow the use of ordinary
// function as PromotionRule mutator.
type PromotionRuleFunc func(context.Context, *ent.PromotionRuleMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PromotionRuleFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PromotionRuleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PromotionRuleMutation", m)
}

// The RateLimitConfigFunc type is an adapter to allow the use of ordinary
// function as RateLimitConfig mutator.
type RateLimitConfigFunc func(context.Context, *ent.RateLimitConfigMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RateLimitConfigFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RateLimitConfigMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RateLimitConfigMutation", m)
}

// The SectionFunc type is an adapter to allow the use of ordinary
// function as Section mutator.
type SectionFunc func(context.Context, *ent.SectionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SectionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SectionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SectionMutation", m)
}

// The ServiceConfigFunc type is an adapter to allow the use of ordinary
// function as ServiceConfig mutator.
type ServiceConfigFunc func(context.Context, *ent.ServiceConfigMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ServiceConfigFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ServiceConfigMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ServiceConfigMutation", m)
}

// The StockAlertSubscriptionFunc type is an adapter to allow the use of ordinary
// function as StockAlertSubscription mutator.
type StockAlertSubscriptionFunc func(context.Context, *ent.StockAlertSubscriptionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StockAlertSubscriptionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StockAlertSubscriptionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StockAlertSubscriptionMutation", m)
}

// The StockConsumptionEventFunc type is an adapter to allow the use of ordinary
// function as StockConsumptionEvent mutator.
type StockConsumptionEventFunc func(context.Context, *ent.StockConsumptionEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StockConsumptionEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StockConsumptionEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StockConsumptionEventMutation", m)
}

// The SyncFailureFunc type is an adapter to allow the use of ordinary
// function as SyncFailure mutator.
type SyncFailureFunc func(context.Context, *ent.SyncFailureMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SyncFailureFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SyncFailureMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SyncFailureMutation", m)
}

// The TableFunc type is an adapter to allow the use of ordinary
// function as Table mutator.
type TableFunc func(context.Context, *ent.TableMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TableFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TableMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TableMutation", m)
}

// The TableAssignmentFunc type is an adapter to allow the use of ordinary
// function as TableAssignment mutator.
type TableAssignmentFunc func(context.Context, *ent.TableAssignmentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TableAssignmentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TableAssignmentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TableAssignmentMutation", m)
}

// The TenantFunc type is an adapter to allow the use of ordinary
// function as Tenant mutator.
type TenantFunc func(context.Context, *ent.TenantMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TenantFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TenantMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TenantMutation", m)
}

// The TenantSyncEventFunc type is an adapter to allow the use of ordinary
// function as TenantSyncEvent mutator.
type TenantSyncEventFunc func(context.Context, *ent.TenantSyncEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TenantSyncEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TenantSyncEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TenantSyncEventMutation", m)
}

// The TenderFunc type is an adapter to allow the use of ordinary
// function as Tender mutator.
type TenderFunc func(context.Context, *ent.TenderMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TenderFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TenderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TenderMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *ent.UserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserMutation", m)
}

// The UserPOSRoleFunc type is an adapter to allow the use of ordinary
// function as UserPOSRole mutator.
type UserPOSRoleFunc func(context.Context, *ent.UserPOSRoleMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserPOSRoleFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserPOSRoleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserPOSRoleMutation", m)
}

// The WebhookSubscriptionFunc type is an adapter to allow the use of ordinary
// function as WebhookSubscription mutator.
type WebhookSubscriptionFunc func(context.Context, *ent.WebhookSubscriptionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f WebhookSubscriptionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.WebhookSubscriptionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.WebhookSubscriptionMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
